class Behavior:
    """行为id"""

    SHARE_BLANKLY = 0
    """ 发呆 """
    MOVE = 1
    """ 移动 """
    WAIT = 2
    """ 等待 """
    CHANGE_CLOTH = 3
    """ 换衣服 """
    CHARA_DIY_INSTRUCT = 5
    """ 角色自定义指令 """
    AI_CHAT_INSTRUCT = 6
    """ AI对话用特殊指令 """
    EMPTY_INSTRUCT = 99
    """ 空白示范指令 """
    CHAT = 101
    """ 聊天 """
    CHAT_FAILED = 102
    """ 谈话次数过多而失败 """
    STROKE = 103
    """ 身体接触 """
    MASSAGE = 104
    """ 按摩 """
    REST = 110
    """ 休息 """
    SLEEP = 111
    """ 睡觉 """
    TAKE_SHOWER = 112
    """ 淋浴 """
    GET_UP = 113
    """ 起床 """
    FOLLOW = 115
    """ 让NPC跟随玩家 """
    END_FOLLOW = 116
    """ 让NPC停止跟随玩家 """
    APOLOGIZE = 117
    """ 道歉 """
    APOLOGIZE_FAILED = 118
    """ 道歉失败 """
    LISTEN_COMPLAINT = 119
    """ 听牢骚 """
    MAKE_COFFEE = 131
    """ 泡咖啡 """
    MAKE_COFFEE_ADD = 132
    """ 泡咖啡（加料） """
    ASK_MAKE_COFFEE = 133
    """ 让对方泡咖啡 """
    MAKE_FOOD = 134
    """ 做饭 """
    EAT = 135
    """ 进食 """
    REFUSE_EAT = 136
    """ 拒绝进食 """
    BUY_FOOD = 137
    """ 购买食物 """
    PEE = 140
    """ 解手 """
    CLOTH_OFF = 141
    """ 脱掉全部衣服 """
    PUT_SHOWER_CLOTH = 142
    """ 换上浴帽和浴巾 """
    PUT_SLEEP_CLOTH = 143
    """ 换上睡衣和内衣 """
    WEAR_TO_LOCKER = 144
    """ 身上衣服脱到衣柜 """
    LOCKER_TO_WEAR = 145
    """ 衣柜衣服穿回身上 """
    READY_TO_SWIM = 146
    """ 脱掉衣服并换上泳衣并进入要游泳状态 """
    FOOT_CLOTH_TO_LOCKER =147
    """ 袜子和鞋子转移到衣柜里 """
    WEAR_TO_LOCKER_AND_GET_SHOWER_CLOTH = 148
    """ 身上衣服脱到衣柜并换上浴帽和浴巾 """
    CLEAN_WEAR_AND_LOCKER_TO_WEAR = 149
    """ 清空身上的衣服然后穿回衣柜的衣服 """
    SINGING = 151
    """ 唱歌 """
    PLAY_INSTRUMENT = 152
    """ 演奏乐器 """
    WATCH_MOVIE = 153
    """ 看电影 """
    PHOTOGRAPHY = 154
    """ 摄影 """
    PLAY_WATER = 155
    """ 玩水 """
    PLAY_CHESS = 156
    """ 下棋 """
    PLAY_MAHJONG = 157
    """ 打麻将 """
    PLAY_CARDS = 158
    """ 打牌 """
    REHEARSE_DANCE = 159
    """ 排演舞剧 """
    PLAY_ARCADE_GAME = 160
    """ 玩街机游戏 """
    SWIMMING = 161
    """ 游泳 """
    TASTE_WINE = 162
    """ 品酒 """
    TASTE_TEA = 163
    """ 品茶 """
    TASTE_COFFEE = 164
    """ 品咖啡 """
    TASTE_DESSERT = 165
    """ 品尝点心 """
    TASTE_FOOD = 166
    """ 品尝美食 """
    PLAY_HOUSE = 167
    """ 过家家 """
    STYLE_HAIR = 168
    """ 修整发型 """
    FULL_BODY_STYLING = 169
    """ 全身造型服务 """
    LISTEN_INFLATION = 171
    """ 听肚子里的动静 """
    PLAY_WITH_CHILD = 172
    """ 一起玩耍 """
    PL_WIN_IN_BOARD_GAME = 173
    """ 博士在桌游中获胜 """
    PL_LOSE_IN_BOARD_GAME = 174
    """ 博士在桌游中输了 """
    SOAK_FEET = 181
    """ 泡脚 """
    STEAM_SAUNA = 182
    """ 蒸桑拿 """
    HYDROTHERAPY_TREATMENT = 183
    """ 水疗护理 """
    ONSEN_BATH = 184
    """ 泡温泉 """
    AROMATHERAPY_1 = 191
    """ 香薰疗愈_回复 """
    AROMATHERAPY_2 = 192
    """ 香薰疗愈_习得 """
    AROMATHERAPY_3 = 193
    """ 香薰疗愈_反感 """
    AROMATHERAPY_4 = 194
    """ 香薰疗愈_快感 """
    AROMATHERAPY_5 = 195
    """ 香薰疗愈_好感 """
    AROMATHERAPY_6 = 196
    """ 香薰疗愈_催眠 """
    OFFICIAL_WORK = 201
    """ 处理公务 """
    BATTLE_COMMAND = 202
    """ 指挥作战 """
    ASSISTANT_ADJUSTMENTS = 204
    """ 助理相关调整 """
    TRAINING = 205
    """ 战斗训练 """
    EXERCISE = 206
    """ 锻炼身体 """
    CURE_PATIENT = 207
    """ 诊疗病人 """
    RECRUIT = 208
    """ 招募干员 """
    INVITE_VISITOR = 209
    """ 邀请访客 """
    READ_BOOK = 210
    """ 读书 """
    TEACH = 213
    """ 授课 """
    ATTENT_CLASS = 214
    """ 上学 """
    MAINTENANCE_FACILITIES = 215
    """ 维护设施 """
    REPAIR_EQUIPMENT = 216
    """ 维修装备 """
    NPC_WORK_COOK = 217
    """ 干员工作做饭 """
    PRODUCE = 218
    """ 制造产品 """
    PLANT_MANAGE_CROP = 219
    """ 种植与养护作物 """
    DEAL_WITH_DIPLOMACY = 221
    """ 处理外交事宜 """
    TRAIN_PRISONER = 222
    """ 训练囚犯 """

    MORNING_SALUTATION_1 = 251
    """ 早安问候：叫起床 """
    MORNING_SALUTATION_2 = 252
    """ 早安问候：早安吻 """
    MORNING_SALUTATION_3 = 253
    """ 早安问候：早安咬 """
    NIGHT_SALUTATION_1 = 254
    """ 晚安问候：催睡觉 """
    NIGHT_SALUTATION_2 = 255
    """ 晚安问候：晚安吻 """
    NIGHT_SALUTATION_3 = 256
    """ 晚安问候：晚安咬 """
    NPC_ASSISTANT_COOK = 261
    """ 干员助理做饭 """

    TOUCH_HEAD = 301
    """ 摸头 """
    TOUCH_BREAST = 302
    """ 摸胸 """
    TOUCH_BUTTOCKS = 303
    """ 摸屁股 """
    TOUCH_EARS = 304
    """ 摸耳朵 """
    TOUCH_HORN = 305
    """ 摸角 """
    TOUCH_TAIL = 306
    """ 摸尾巴 """
    TOUCH_RING = 307
    """ 摸光环 """
    TOUCH_WING = 308
    """ 摸翅膀 """
    TOUCH_TENTACLE = 309
    """ 摸触手 """
    TOUCH_CAR = 310
    """ 摸小车 """
    HAND_IN_HAND = 311
    """ 牵手 """
    EMBRACE = 312
    """ 拥抱 """
    KISS = 313
    """ 亲吻 """
    LAP_PILLOW = 314
    """ 膝枕 """
    RAISE_SKIRT = 315
    """ 掀起裙子 """
    ASK_FOR_PAN = 316
    """ 索要内裤 """
    ASK_FOR_SOCKS = 317
    """ 索要袜子 """
    INVITE_TO_BATH = 318
    """ 一起洗澡 """
    TOUCH_CLITORIS = 331
    """ 阴蒂爱抚 """
    TOUCH_VAGINA = 332
    """ 手指插入（V） """
    TOUCH_ANUS = 333
    """ 手指插入（A） """
    MILK = 336
    """ 挤奶 """
    SMELL_UNDERWEAR = 341
    """ 闻内衣 """
    STEAL_PAN = 342
    """ 偷走内裤 """
    STEAL_SOCKS = 343
    """ 偷走袜子 """
    STEAL_SCENE_ALL_PAN = 344
    """ 偷走所有人内裤 """
    STEAL_SCENE_ALL_SOCKS = 345
    """ 偷走所有人袜子 """
    BAGGING_AND_MOVING = 351
    """ 装袋搬走 """
    PUT_INTO_PRISON = 352
    """ 投入监牢 """
    SET_FREE = 353
    """ 解除囚禁 """
    H = 361
    """ 进入H状态 """
    END_H = 362
    """ 结束H """
    DO_H_FAIL = 363
    """ 邀请H失败 """
    H_HP_0 = 364
    """ H时博士体力为零中断 """
    T_H_HP_0 = 365
    """ H时交互对象体力为零中断 """
    H_INTERRUPT = 366
    """ H时被人目击闯入中断 """
    NO_CONSCIOUS_H_END = 367
    """ 结束无意识H """
    HIDDEN_SEX_INTERRUPT = 368
    """ 隐奸被发现中断 """
    HIDDEN_SEX_TO_GROUP_SEX = 369
    """ 隐奸被发现转群交 """
    CONFESSION = 371
    """ 告白 """
    CONFESSION_FAILED = 372
    """ 告白失败 """
    GIVE_NECKLACE = 373
    """ 戴上项圈 """
    GIVE_NECKLACE_FAILED = 374
    """ 戴上项圈失败 """
    DISCOVER_HIDDEN_SEX_AND_INTERRUPT = 376
    """ 发现隐奸并打断 """
    DISCOVER_HIDDEN_SEX_AND_JOIN = 377
    """ 发现隐奸并加入转群交 """
    ASK_HIDDEN_SEX = 378
    """ 邀请隐奸 """
    ASK_HIDDEN_SEX_FAIL = 379
    """ 邀请隐奸失败 """
    ASK_GROUP_SEX = 380
    """ 邀请群交 """
    ASK_GROUP_SEX_FAIL = 381
    """ 邀请群交失败 """
    GROUP_SEX_END = 382
    """ 结束群交 """
    GROUP_SEX_PL_HP_0_END = 383
    """ 群交时博士体力为零中断 """
    GROUP_SEX_NPC_HP_0_END = 384
    """ 群交时自己体力为零退出 """
    GROUP_SEX_TO_H = 385
    """ 群交时NPC数量不足转为单人H """
    JOIN_GROUP_SEX = 386
    """ 自己加入群交 """
    SEE_H = 396
    """ 目睹玩家与其他角色H """
    KISS_FAIL = 397
    """ 亲吻失败 """
    HIGH_OBSCENITY_ANUS = 398
    """ 重度猥亵失败 """
    LOW_OBSCENITY_ANUS = 399
    """ 轻度猥亵失败 """
    MAKING_OUT = 401
    """ 身体爱抚 """
    KISS_H = 402
    """ 接吻 """
    BREAST_CARESS = 403
    """ 胸爱抚 """
    TWIDDLE_NIPPLES = 404
    """ 玩弄乳头 """
    BREAST_SUCKING = 405
    """ 舔吸乳头 """
    CLIT_CARESS = 406
    """ 阴蒂爱抚 """
    OPEN_LABIA = 407
    """ 掰开阴唇观察 """
    OPEN_ANUS = 408
    """ 掰开肛门观察 """
    CUNNILINGUS = 409
    """ 舔阴 """
    LICK_ANAL = 410
    """ 舔肛 """
    FINGER_INSERTION = 411
    """ 手指插入(V) """
    ANAL_CARESS = 412
    """ 手指插入(A) """
    MAKE_MASTUREBATE = 413
    """ 命令对方自慰 """
    MAKE_LICK_ANAL = 414
    """ 命令对方舔自己肛门 """
    KEEP_ENJOY = 415
    """ 继续享受 """
    SEDECU = 416
    """ 诱惑对方 """
    ASK_PEE = 417
    """ 命令对方小便 """
    MASTUREBATE = 418
    """ 自慰(女) """
    HANDJOB = 420
    """ 手交 """
    BLOWJOB = 421
    """ 口交 """
    PAIZURI = 422
    """ 乳交 """
    FOOTJOB = 423
    """ 足交 """
    HAIRJOB = 424
    """ 发交 """
    AXILLAJOB = 425
    """ 腋交 """
    RUB_BUTTOCK = 426
    """ 素股 """
    HAND_BLOWJOB = 427
    """ 手交口交 """
    TITS_BLOWJOB = 428
    """ 乳交口交 """
    FOCUS_BLOWJOB = 429
    """ 真空口交 """
    DEEP_THROAT = 430
    """ 深喉插入 """
    SIXTY_NINE = 431
    """ 六九式 """
    LEGJOB = 432
    """ 腿交 """
    TAILJOB = 433
    """ 尾交 """
    FACE_RUB = 434
    """ 阴茎蹭脸 """
    HORN_RUB = 435
    """ 阴茎蹭角 """
    EARS_RUB = 436
    """ 阴茎蹭耳朵 """
    CLEAN_BLOWJOB = 437
    """ 清洁口交 """
    BODY_LUBRICANT = 451
    """ 润滑液 """
    BIRTH_CONTROL_PILLS_BEFORE = 452
    """ 事前避孕药 """
    BIRTH_CONTROL_PILLS_AFTER = 453
    """ 事后避孕药 """
    PHILTER = 454
    """ 媚药 """
    ENEMAS = 455
    """ 灌肠液 """
    DIURETICS_ONCE = 456
    """ 一次性利尿剂 """
    DIURETICS_PERSISTENT = 457
    """ 持续性利尿剂 """
    SLEEPING_PILLS = 458
    """ 安眠药 """
    CLOMID = 459
    """ 排卵促进药 """
    PUT_CONDOM = 471
    """ 戴上避孕套 """
    SAFE_CANDLES = 472
    """ 滴蜡 """
    URETHRAL_SWAB = 473
    """ 尿道棉棒 """
    TAKE_CONDOM_OUT = 474
    """ 摘掉避孕套 """
    NIPPLES_LOVE_EGG = 481
    """ 乳头跳蛋 """
    NIPPLE_CLAMP_ON = 482
    """ 戴上乳头夹 """
    CLIT_LOVE_EGG = 483
    """ 阴蒂跳蛋 """
    CLIT_CLAMP_ON = 484
    """ 戴上阴蒂夹 """
    ELECTRIC_MESSAGE_STICK = 485
    """ 电动按摩棒 """
    VIBRATOR_INSERTION = 486
    """ V插入震动棒 """
    BIG_VIBRATOR_INSERTION = 487
    """ 加粗震动棒 """
    HUGE_VIBRATOR_INSERTION = 488
    """ 巨型震动棒 """
    VIBRATOR_INSERTION_ANAL = 489
    """ A插入震动棒 """
    BIG_VIBRATOR_INSERTION_ANAL = 490
    """ 加粗肛门震动棒 """
    HUGE_VIBRATOR_INSERTION_ANAL = 491
    """ 巨型肛门震动棒 """
    CLYSTER = 492
    """ 灌肠 """
    ANAL_PLUG = 493
    """ 肛塞 """
    ANAL_BEADS = 494
    """ 塞入肛门拉珠 """
    CLYSTER_END = 495
    """ 拔出肛塞 """
    NIPPLE_CLAMP_OFF = 496
    """ 取下乳头夹 """
    CLIT_CLAMP_OFF = 497
    """ 取下阴蒂夹 """
    VIBRATOR_INSERTION_OFF = 498
    """ 拔出震动棒 """
    VIBRATOR_INSERTION_ANAL_OFF = 499
    """ 拔出肛门震动棒 """
    ANAL_BEADS_OFF = 500
    """ 拔出肛门拉珠 """
    NORMAL_SEX = 501
    """ 正常位 """
    BACK_SEX = 502
    """ 背后位 """
    RIDING_SEX = 503
    """ 对面骑乘位 """
    FACE_SEAT_SEX = 504
    """ 对面座位 """
    BACK_SEAT_SEX = 505
    """ 背面座位 """
    FACE_STAND_SEX = 506
    """ 对面立位 """
    BACK_STAND_SEX = 507
    """ 背面立位 """
    BACK_RIDING_SEX = 508
    """ 背面骑乘位 """
    STIMULATE_G_POINT = 511
    """ 刺激G点 """
    WOMB_OS_CARESS = 512
    """ 玩弄子宫口 """
    WOMB_INSERTION = 513
    """ 插入子宫口 """
    WOMB_SEX = 514
    """ 子宫姦 """
    EXTERNAL_WOMB_MASSAGE = 515
    """ 体外子宫按摩 """
    NORMAL_ANAL_SEX = 521
    """ 正常位肛交 """
    BACK_ANAL_SEX = 522
    """ 后背位肛交 """
    RIDING_ANAL_SEX = 523
    """ 对面骑乘位肛交 """
    FACE_SEAT_ANAL_SEX = 524
    """ 对面座位肛交 """
    BACK_SEAT_ANAL_SEX = 525
    """ 背面座位肛交 """
    FACE_STAND_ANAL_SEX = 526
    """ 对面立位肛交 """
    BACK_STAND_ANAL_SEX = 527
    """ 背面立位肛交 """
    BACK_RIDING_ANAL_SEX = 528
    """ 背面骑乘位肛交 """
    STIMULATE_SIGMOID_COLON = 530
    """ 玩弄s状结肠 """
    STIMULATE_VAGINA = 531
    """ 隔着刺激阴道 """
    URETHRAL_FINGER_INSERTION = 541
    """ 尿道指姦 """
    URETHRAL_SEX = 542
    """ 尿道姦 """
    FACE_HUG_SEX = 551
    """ 对面抱位 """
    BACK_HUG_SEX = 552
    """ 背面抱位 """
    FACE_LAY_SEX = 553
    """ 对面卧位 """
    BACK_LAY_SEX = 554
    """ 背面卧位 """
    FACE_HUG_ANAL_SEX = 561
    """ 对面抱位肛交 """
    BACK_HUG_ANAL_SEX = 562
    """ 背面抱位肛交 """
    FACE_LAY_ANAL_SEX = 563
    """ 对面卧位肛交 """
    BACK_LAY_ANAL_SEX = 564
    """ 背面卧位肛交 """

    MILKING_MACHINE_ON = 601
    """ 装上搾乳机 """
    URINE_COLLECTOR_ON = 602
    """ 装上采尿器 """
    BIND = 603
    """ 捆绑 """
    PATCH_ON = 604
    """ 戴上眼罩 """
    WHIP = 605
    """ 鞭子 """
    NEEDLE = 606
    """ 针 """
    GAG_ON = 607
    """ 戴上口球 """

    MILKING_MACHINE_OFF = 631
    """ 取下搾乳机 """
    URINE_COLLECTOR_OFF = 632
    """ 取下采尿器 """
    UNBIND = 633
    """ 解除捆绑 """
    PATCH_OFF = 634
    """ 摘下眼罩 """
    GAG_OFF = 635
    """ 摘下口球 """

    EXERCISE_SUCKING_AND_SWALLOWING = 681
    """ 练习吮吸与吞咽力 """
    EXERCISE_ARMPIT_FLEXIBILITY = 682
    """ 练习腋下夹持力 """
    EXERCISE_BREAST_CLAMPING = 683
    """ 练习胸部夹持力 """
    EXERCISE_HANDS_CLAMPING = 684
    """ 练习手部灵活度 """
    EXERCISE_FOOTS_FLEXIBILITY = 685
    """ 练习足部灵活度 """
    EXERCISE_VAGINA_FIRMNESS = 686
    """ 练习阴道紧致度 """
    EXERCISE_INTESTINE_FIRMNESS = 687
    """ 练习肠道紧致度 """
    EXERCISE_TAIL_FLEXIBILITY = 688
    """ 练习尾巴灵活度 """
    EXERCISE_TENTACLE_FLEXIBILITY = 689
    """ 练习触手灵活度 """

    UNDRESS = 701
    """ 脱衣服 """

    HAT_JOB = 710
    """ 帽子交 """
    GLASSES_JOB = 711
    """ 眼镜交 """
    EAR_ORNAMENT_JOB = 712
    """ 耳饰交 """
    NECK_ORNAMENT_JOB = 713
    """ 脖饰交 """
    MOUTH_ORNAMENT_JOB = 714
    """ 口罩交 """
    TOP_JOB = 715
    """ 上衣交 """
    CORSET_JOB = 716
    """ 胸衣交 """
    GLOVES_JOB = 717
    """ 手套交 """
    SKIRT_JOB = 718
    """ 裙子交 """
    UNDERWEAR_JOB = 719
    """ 内裤交 """
    SOCKS_JOB = 720
    """ 袜子交 """
    SHOES_JOB = 721
    """ 鞋子交 """
    WEAPONS_JOB = 722
    """ 武器交 """
    TROUSERS_JOB = 723
    """ 裤子交 """

    ORGASM_EDGE_ON = 751
    """ 绝顶寸止 """
    ORGASM_EDGE_OFF = 752
    """ 绝顶解放 """

    SPANKING = 771
    """ 打屁股 """

    HOLD_CHILD = 801
    """ 抱小孩 """
    SING_CHILDREN_SONG = 802
    """ 哼唱儿歌 """
    NUIRSE_CHILD = 803
    """ 喂奶 """
    CHANGE_DIAPERS = 804
    """ 换尿布 """
    TEACH_TALK = 805
    """ 教说话 """
    GIVE_TOY = 806
    """ 给玩具 """

    EXAMINE_HAIR = 850
    """ 检查头发 """
    EXAMINE_HAIR_SMOOTHNESS = 851
    """ 测试头发柔顺度 """
    EXAMINE_ORAL = 852
    """ 检查口腔内部 """
    EXAMINE_SUCKING_AND_SWALLOWING = 853
    """ 测试口腔吮吸与吞咽力 """
    EXAMINE_ARMPIT = 854
    """ 检查腋下 """
    EXAMINE_ARMPIT_CLAMPING = 855
    """ 测试腋下夹持力 """
    EXAMINE_BREAST = 856
    """ 检查胸部 """
    EXAMINE_NIPPLE_AND_AREOLA = 857
    """ 检查乳头与乳晕 """
    EXAMINE_BREAST_CLAMPING = 858
    """ 测试胸部夹持力 """
    EXAMINE_CILITORIS = 859
    """ 检查阴蒂 """
    EXAMINE_HANDS = 860
    """ 检查手部 """
    EXAMINE_HANDS_FLEXIBILITY = 861
    """ 测试手部灵活度 """
    EXAMINE_FOOT = 862
    """ 检查足部 """
    EXAMINE_FOOTS_FLEXIBILITY = 863
    """ 测试足部灵活度 """
    EXAMINE_VULVA_AND_SHAPE = 871
    """ 检查外阴形状 """
    EXAMINE_VAGINA_AND_FOLDS = 872
    """ 检查内阴褶皱 """
    EXAMINE_HYMEN = 873
    """ 检查处女膜 """
    EXAMINE_ORIFICE = 874
    """ 检查子宫口 """
    EXAMINE_VAGINA_FIRMNESS = 875
    """ 测试阴道紧致度 """
    EXAMINE_ANUS = 876
    """ 检查菊穴 """
    EXAMINE_INTESTINE_FIRMNESS = 877
    """ 测试肠道紧致度 """
    EXAMINE_URETHRA = 878
    """ 检查尿道 """
    EXAMINE_URINATION_STATUS = 879
    """ 测试现场排尿 """
    EXAMINE_TAIL = 881
    """ 检查尾巴 """
    EXAMINE_TAIL_FLEXIBILITY = 882
    """ 测试尾巴灵活度 """
    EXAMINE_HORN = 883
    """ 检查兽角 """
    EXAMINE_EARS = 884
    """ 检查兽耳 """
    EXAMINE_WING = 885
    """ 检查翅膀 """
    EXAMINE_RING = 886
    """ 检查光环 """
    EXAMINE_TENTACLE = 887
    """ 检查触手 """
    EXAMINE_TENTACLE_FLEXIBILITY = 888
    """ 测试触手灵活度 """

    PENETRATING_VISION_ON = 901
    """ 开启透视 """
    PENETRATING_VISION_OFF = 902
    """ 关闭透视 """
    HORMONE_ON = 903
    """ 开启信息素 """
    HORMONE_OFF = 904
    """ 关闭信息素 """
    HYPNOSIS_ONE = 911
    """ 单人催眠 """
    HYPNOSIS_ALL = 912
    """ 集体催眠 """
    HYPNOSIS_CANCEL = 913
    """ 解除催眠 """
    HYPNOSIS_INCREASE_BODY_SENSITIVITY = 921
    """ 体控-敏感度提升 """
    HYPNOSIS_FORCE_CLIMAX = 922
    """ 体控-强制高潮 """
    HYPNOSIS_FORCE_OVULATION = 923
    """ 体控-强制排卵 """
    HYPNOSIS_BLOCKHEAD = 924
    """ 体控-木头人 """
    HYPNOSIS_ACTIVE_H = 925
    """ 体控-逆推 """
    HYPNOSIS_ROLEPLAY = 931
    """ 心控-角色扮演 """
    HYPNOSIS_PAIN_AS_PLEASURE = 932
    """ 心控-苦痛快感化 """
    TIME_STOP_ON = 941
    """ 时间停止流动 """
    TIME_STOP_OFF = 942
    """ 时间重新流动 """
    CARRY_TARGET = 943
    """ 搬运对方 """
    STOP_CARRY_TARGET = 944
    """ 停止搬运对方 """
    TARGET_FREE_IN_TIME_STOP = 945
    """ 对方在时停中获得自由 """
    TARGET_STOP_IN_TIME_STOP = 946
    """ 对方在时停中再次停止 """

