class CharacterStatus:
    """角色状态id"""

    STATUS_ARDER = 0
    """ 空闲状态 """
    STATUS_MOVE = 1
    """ 移动状态 """
    STATUS_WAIT = 2
    """ 等待 """
    STATUS_CHANGE_CLOTH = 3
    """ 换衣服状态 """
    STATUS_CHARA_DIY_INSTRUCT = 5
    """ 角色自定义指令 """
    STATUS_AI_CHAT_INSTRUCT = 6
    """ AI对话用特殊指令 """
    STATUS_EMPTY_INSTRUCT = 99
    """ 空白示范指令 """
    STATUS_CHAT = 101
    """ 聊天状态 """
    STATUS_CHAT_FAILED = 102
    """ 谈话次数过多的状态 """
    STATUS_STROKE = 103
    """ 身体接触 """
    STATUS_MASSAGE = 104
    """ 按摩 """
    STATUS_REST = 110
    """ 休息状态 """
    STATUS_SLEEP = 111
    """ 睡觉 """
    STATUS_TAKE_SHOWER = 112
    """ 淋浴 """
    STATUS_GET_UP = 113
    """ 起床 """
    STATUS_FOLLOW = 115
    """ NPC跟随玩家 """
    STATUS_END_FOLLOW = 116
    """ NPC停止跟随玩家 """
    STATUS_APOLOGIZE = 117
    """ 道歉 """
    STATUS_APOLOGIZE_FAILED = 118
    """ 道歉失败 """
    STATUS_LISTEN_COMPLAINT = 119
    """ 听牢骚 """
    STATUS_MAKE_COFFEE = 131
    """ 泡咖啡 """
    STATUS_MAKE_COFFEE_ADD = 132
    """ 泡咖啡（加料） """
    STATUS_ASK_MAKE_COFFEE = 133
    """ 让对方泡咖啡 """
    STATUS_MAKE_FOOD = 134
    """ 做饭 """
    STATUS_EAT = 135
    """ 进食状态 """
    STATUS_REFUSE_EAT = 136
    """ 拒绝进食 """
    STATUS_BUY_FOOD = 137
    """ 购买食物 """
    STATUS_PEE = 140
    """ 解手 """
    STATUS_CLOTH_OFF = 141
    """ 脱掉全部衣服 """
    STATUS_PUT_SHOWER_CLOTH = 142
    """ 换上浴帽和浴巾 """
    STATUS_PUT_SLEEP_CLOTH = 143
    """ 换上睡衣和内衣 """
    STATUS_WEAR_TO_LOCKER = 144
    """ 身上衣服脱到衣柜 """
    STATUS_LOCKER_TO_WEAR = 145
    """ 衣柜衣服穿回身上 """
    STATUS_READY_TO_SWIM = 146
    """ 脱掉衣服并换上泳衣并进入要游泳状态 """
    STATUS_FOOT_CLOTH_TO_LOCKER =147
    """ 袜子和鞋子转移到衣柜里 """
    STATUS_WEAR_TO_LOCKER_AND_GET_SHOWER_CLOTH = 148
    """ 身上衣服脱到衣柜并换上浴帽和浴巾 """
    STATUS_CLEAN_WEAR_AND_LOCKER_TO_WEAR = 149
    """ 清空身上的衣服然后穿回衣柜的衣服 """
    STATUS_SINGING = 151
    """ 唱歌 """
    STATUS_PLAY_INSTRUMENT = 152
    """ 演奏乐器 """
    STATUS_WATCH_MOVIE = 153
    """ 看电影 """
    STATUS_PHOTOGRAPHY = 154
    """ 摄影 """
    STATUS_PLAY_WATER = 155
    """ 玩水 """
    STATUS_PLAY_CHESS = 156
    """ 下棋 """
    STATUS_PLAY_MAHJONG = 157
    """ 打麻将 """
    STATUS_PLAY_CARDS = 158
    """ 打牌 """
    STATUS_REHEARSE_DANCE = 159
    """ 排演舞剧 """
    STATUS_PLAY_ARCADE_GAME = 160
    """ 玩街机游戏 """
    STATUS_SWIMMING = 161
    """ 游泳 """
    STATUS_TASTE_WINE = 162
    """ 品酒 """
    STATUS_TASTE_TEA = 163
    """ 品茶 """
    STATUS_TASTE_COFFEE = 164
    """ 品咖啡 """
    STATUS_TASTE_DESSERT = 165
    """ 品尝点心 """
    STATUS_TASTE_FOOD = 166
    """ 品尝美食 """
    STATUS_PLAY_HOUSE = 167
    """ 过家家 """
    STATUS_STYLE_HAIR = 168
    """ 修整发型 """
    STATUS_FULL_BODY_STYLING = 169
    """ 全身造型服务 """
    STATUS_LISTEN_INFLATION = 171
    """ 听肚子里的动静 """
    STATUS_PLAY_WITH_CHILD = 172
    """ 一起玩耍 """
    STATUS_PL_WIN_IN_BOARD_GAME = 173
    """ 博士在桌游中获胜 """
    STATUS_PL_LOSE_IN_BOARD_GAME = 174
    """ 博士在桌游中输了 """
    STATUS_SOAK_FEET = 181
    """ 泡脚 """
    STATUS_STEAM_SAUNA = 182
    """ 蒸桑拿 """
    STATUS_HYDROTHERAPY_TREATMENT = 183
    """ 水疗护理 """
    STATUS_ONSEN_BATH = 184
    """ 泡温泉 """
    STATUS_AROMATHERAPY_1 = 191
    """ 香薰疗愈_回复 """
    STATUS_AROMATHERAPY_2 = 192
    """ 香薰疗愈_习得 """
    STATUS_AROMATHERAPY_3 = 193
    """ 香薰疗愈_反感 """
    STATUS_AROMATHERAPY_4 = 194
    """ 香薰疗愈_快感 """
    STATUS_AROMATHERAPY_5 = 195
    """ 香薰疗愈_好感 """
    STATUS_AROMATHERAPY_6 = 196
    """ 香薰疗愈_催眠 """
    STATUS_OFFICIAL_WORK = 201
    """ 处理公务 """
    STATUS_ASSISTANT_ADJUSTMENTS = 204
    """ 助理相关调整 """
    STATUS_TRAINING = 205
    """ 战斗训练 """
    STATUS_EXERCISE = 206
    """ 锻炼身体 """
    STATUS_CURE_PATIENT = 207
    """ 诊疗病人 """
    STATUS_RECRUIT = 208
    """ 招募干员 """
    STATUS_INVITE_VISITOR = 209
    """ 邀请访客 """
    STATUS_READ_BOOK = 210
    """ 读书 """
    STATUS_TEACH = 213
    """ 授课 """
    STATUS_ATTENT_CLASS = 214
    """ 上学 """
    STATUS_MAINTENANCE_FACILITIES = 215
    """ 维护设施 """
    STATUS_REPAIR_EQUIPMENT = 216
    """ 维修装备 """
    STATUS_NPC_WORK_COOK = 217
    """ 干员工作做饭 """
    STATUS_PRODUCE = 218
    """ 制造产品 """
    STATUS_PLANT_MANAGE_CROP = 219
    """ 种植与养护作物 """
    STATUS_DEAL_WITH_DIPLOMACY = 221
    """ 处理外交事宜 """
    STATUS_TRAIN_PRISONER = 222
    """ 训练囚犯 """
    STATUS_MORNING_SALUTATION_1 = 251
    """ 早安问候：叫起床 """
    STATUS_MORNING_SALUTATION_2 = 252
    """ 早安问候：早安吻 """
    STATUS_MORNING_SALUTATION_3 = 253
    """ 早安问候：早安咬 """
    STATUS_NIGHT_SALUTATION_1 = 254
    """ 晚安问候：催睡觉 """
    STATUS_NIGHT_SALUTATION_2 = 255
    """ 晚安问候：晚安吻 """
    STATUS_NIGHT_SALUTATION_3 = 256
    """ 晚安问候：晚安咬 """
    STATUS_NPC_ASSISTANT_COOK = 261
    """ 干员助理做饭 """
    STATUS_TOUCH_HEAD = 301
    """ 摸头 """
    STATUS_TOUCH_BREAST = 302
    """ 摸胸 """
    STATUS_TOUCH_BUTTOCKS = 303
    """ 摸屁股 """
    STATUS_TOUCH_EARS = 304
    """ 摸耳朵 """
    STATUS_TOUCH_HORN = 305
    """ 摸角 """
    STATUS_TOUCH_TAIL = 306
    """ 摸尾巴 """
    STATUS_TOUCH_RING = 307
    """ 摸光环 """
    STATUS_TOUCH_WING = 308
    """ 摸翅膀 """
    STATUS_TOUCH_TENTACLE = 309
    """ 摸触手 """
    STATUS_TOUCH_CAR = 310
    """ 摸小车 """
    STATUS_HAND_IN_HAND = 311
    """ 牵手 """
    STATUS_EMBRACE = 312
    """ 拥抱 """
    STATUS_KISS = 313
    """ 亲吻 """
    STATUS_LAP_PILLOW = 314
    """ 膝枕 """
    STATUS_RAISE_SKIRT = 315
    """ 掀起裙子 """
    STATUS_ASK_FOR_PAN = 316
    """ 索要内裤 """
    STATUS_ASK_FOR_SOCKS = 317
    """ 索要袜子 """
    STATUS_INVITE_TO_BATH = 318
    """ 一起洗澡 """
    STATUS_TOUCH_CLITORIS = 331
    """ 阴蒂爱抚 """
    STATUS_TOUCH_VAGINA = 332
    """ 手指插入（V） """
    STATUS_TOUCH_ANUS = 333
    """ 手指插入（A） """
    STATUS_MILK = 336
    """ 挤奶 """
    STATUS_SMELL_UNDERWEAR = 341
    """ 闻内衣 """
    STATUS_STEAL_PAN = 342
    """ 偷走内裤 """
    STATUS_STEAL_SOCKS = 343
    """ 偷走袜子 """
    STATUS_STEAL_SCENE_ALL_PAN = 344
    """ 偷走所有人内裤 """
    STATUS_STEAL_SCENE_ALL_SOCKS = 345
    """ 偷走所有人袜子 """
    STATUS_BAGGING_AND_MOVING = 351
    """ 装袋搬走 """
    STATUS_PUT_INTO_PRISON = 352
    """ 投入监牢 """
    STATUS_SET_FREE = 353
    """ 解除囚禁 """
    STATUS_H = 361
    """ 进入H状态 """
    STATUS_END_H = 362
    """ 结束H状态 """
    STATUS_DO_H_FAIL = 363
    """ 邀请H失败 """
    STATUS_H_HP_0 = 364
    """ H时博士体力为零中断 """
    STATUS_T_H_HP_0 = 365
    """ H时交互对象体力为零中断 """
    STATUS_H_INTERRUPT = 366
    """ H时被人目击闯入中断 """
    STATUS_NO_CONSCIOUS_H_END = 367
    """ 结束无意识H """
    STATUS_HIDDEN_SEX_INTERRUPT = 368
    """ 隐奸被发现中断 """
    STATUS_HIDDEN_SEX_TO_GROUP_SEX = 369
    """ 隐奸被发现转群交 """
    STATUS_CONFESSION = 371
    """ 告白 """
    STATUS_CONFESSION_FAILED = 372
    """ 告白失败 """
    STATUS_GIVE_NECKLACE = 373
    """ 戴上项圈 """
    STATUS_GIVE_NECKLACE_FAILED = 374
    """ 戴上项圈失败 """
    STATUS_DISCOVER_HIDDEN_SEX_AND_INTERRUPT = 376
    """ 发现隐奸并打断 """
    STATUS_DISCOVER_HIDDEN_SEX_AND_JOIN = 377
    """ 发现隐奸并加入转群交 """
    STATUS_ASK_HIDDEN_SEX = 378
    """ 邀请隐奸 """
    STATUS_ASK_HIDDEN_SEX_FAIL = 379
    """ 邀请隐奸失败 """
    STATUS_ASK_GROUP_SEX = 380
    """ 邀请群交 """
    STATUS_ASK_GROUP_SEX_FAIL = 381
    """ 邀请群交失败 """
    STATUS_GROUP_SEX_END = 382
    """ 结束群交 """
    STATUS_GROUP_SEX_PL_HP_0_END = 383
    """ 群交时博士体力为零中断 """
    STATUS_GROUP_SEX_NPC_HP_0_END = 384
    """ 群交时自己体力为零退出 """
    STATUS_GROUP_SEX_TO_H = 385
    """ 群交时NPC数量不足转为单人H """
    STATUS_JOIN_GROUP_SEX = 386
    """ 自己加入群交 """
    STATUS_SEE_H = 396
    """ 目睹玩家与其他角色H """
    STATUS_KISS_FAIL = 397
    """ 亲吻失败 """
    STATUS_HIGH_OBSCENITY_ANUS = 398
    """ 重度猥亵失败 """
    STATUS_LOW_OBSCENITY_ANUS = 399
    """ 轻度猥亵失败 """
    STATUS_MAKING_OUT = 401
    """ 身体爱抚 """
    STATUS_KISS_H = 402
    """ 接吻 """
    STATUS_BREAST_CARESS = 403
    """ 胸爱抚 """
    STATUS_TWIDDLE_NIPPLES = 404
    """ 玩弄乳头 """
    STATUS_BREAST_SUCKING = 405
    """ 舔吸乳头 """
    STATUS_CLIT_CARESS = 406
    """ 阴蒂爱抚 """
    STATUS_OPEN_LABIA = 407
    """ 掰开阴唇 """
    STATUS_OPEN_ANUS = 408
    """ 掰开肛门 """
    STATUS_CUNNILINGUS = 409
    """ 舔阴 """
    STATUS_LICK_ANAL = 410
    """ 舔肛 """
    STATUS_FINGER_INSERTION = 411
    """ 手指插入(V) """
    STATUS_ANAL_CARESS = 412
    """ 手指插入(A) """
    STATUS_MAKE_MASTUREBATE = 413
    """ 命令对方自慰 """
    STATUS_MAKE_LICK_ANAL = 414
    """ 命令对方舔自己肛门 """
    STATUS_KEEP_ENJOY = 415
    """ 继续享受 """
    STATUS_SEDECU = 416
    """ 诱惑对方 """
    STATUS_ASK_PEE = 417
    """ 命令对方小便 """
    STATUS_MASTUREBATE = 418
    """ 自慰(女) """
    STATUS_HANDJOB = 420
    """ 手交 """
    STATUS_BLOWJOB = 421
    """ 口交 """
    STATUS_PAIZURI = 422
    """ 乳交 """
    STATUS_FOOTJOB = 423
    """ 足交 """
    STATUS_HAIRJOB = 424
    """ 发交 """
    STATUS_AXILLAJOB = 425
    """ 腋交 """
    STATUS_RUB_BUTTOCK = 426
    """ 素股 """
    STATUS_HAND_BLOWJOB = 427
    """ 手交口交 """
    STATUS_TITS_BLOWJOB = 428
    """ 乳交口交 """
    STATUS_FOCUS_BLOWJOB = 429
    """ 真空口交 """
    STATUS_DEEP_THROAT = 430
    """ 深喉插入 """
    STATUS_SIXTY_NINE = 431
    """ 六九式 """
    STATUS_LEGJOB = 432
    """ 腿交 """
    STATUS_TAILJOB = 433
    """ 尾交 """
    STATUS_FACE_RUB = 434
    """ 阴茎蹭脸 """
    STATUS_HORN_RUB = 435
    """ 阴茎蹭角 """
    STATUS_EARS_RUB = 436
    """ 阴茎蹭耳朵 """
    STATUS_CLEAN_BLOWJOB = 437
    """ 清洁口交 """
    STATUS_BODY_LUBRICANT = 451
    """ 润滑液 """
    STATUS_BIRTH_CONTROL_PILLS_BEFORE = 452
    """ 事前避孕药 """
    STATUS_BIRTH_CONTROL_PILLS_AFTER = 453
    """ 事后避孕药 """
    STATUS_PHILTER = 454
    """ 媚药 """
    STATUS_ENEMAS = 455
    """ 灌肠液 """
    STATUS_DIURETICS_ONCE = 456
    """ 一次性利尿剂 """
    STATUS_DIURETICS_PERSISTENT = 457
    """ 持续性利尿剂 """
    STATUS_SLEEPING_PILLS = 458
    """ 安眠药 """
    STATUS_CLOMID = 459
    """ 排卵促进药 """
    STATUS_PUT_CONDOM = 471
    """ 戴上避孕套 """
    STATUS_SAFE_CANDLES = 472
    """ 滴蜡 """
    STATUS_URETHRAL_SWAB = 473
    """ 尿道棉棒 """
    STATUS_TAKE_CONDOM_OUT = 474
    """ 摘掉避孕套 """
    STATUS_NIPPLES_LOVE_EGG = 481
    """ 乳头跳蛋 """
    STATUS_NIPPLE_CLAMP_ON = 482
    """ 戴上乳头夹 """
    STATUS_CLIT_LOVE_EGG = 483
    """ 阴蒂跳蛋 """
    STATUS_CLIT_CLAMP_ON = 484
    """ 戴上阴蒂夹 """
    STATUS_ELECTRIC_MESSAGE_STICK = 485
    """ 电动按摩棒 """
    STATUS_VIBRATOR_INSERTION = 486
    """ 震动棒 """
    STATUS_BIG_VIBRATOR_INSERTION = 487
    """ 加粗震动棒 """
    STATUS_HUGE_VIBRATOR_INSERTION = 488
    """ 巨型震动棒 """
    STATUS_VIBRATOR_INSERTION_ANAL = 489
    """ 肛门振动棒 """
    STATUS_BIG_VIBRATOR_INSERTION_ANAL = 490
    """ 加粗肛门震动棒 """
    STATUS_HUGE_VIBRATOR_INSERTION_ANAL = 491
    """ 巨型肛门震动棒 """
    STATUS_CLYSTER = 492
    """ 灌肠 """
    STATUS_ANAL_PLUG = 493
    """ 肛塞 """
    STATUS_ANAL_BEADS = 494
    """ 塞入肛门拉珠 """
    STATUS_CLYSTER_END = 495
    """ 拔出肛塞 """
    STATUS_NIPPLE_CLAMP_OFF = 496
    """ 取下乳头夹 """
    STATUS_CLIT_CLAMP_OFF = 497
    """ 取下阴蒂夹 """
    STATUS_VIBRATOR_INSERTION_OFF = 498
    """ 拔出振动棒 """
    STATUS_VIBRATOR_INSERTION_ANAL_OFF = 499
    """ 拔出肛门振动棒 """
    STATUS_ANAL_BEADS_OFF = 500
    """ 拔出肛门拉珠 """
    STATUS_NORMAL_SEX = 501
    """ 正常位 """
    STATUS_BACK_SEX = 502
    """ 背后位 """
    STATUS_RIDING_SEX = 503
    """ 对面骑乘位 """
    STATUS_FACE_SEAT_SEX = 504
    """ 对面座位 """
    STATUS_BACK_SEAT_SEX = 505
    """ 背面座位 """
    STATUS_FACE_STAND_SEX = 506
    """ 对面立位 """
    STATUS_BACK_STAND_SEX = 507
    """ 背面立位 """
    STATUS_BACK_RIDING_SEX = 508
    """ 背面骑乘位 """
    STATUS_STIMULATE_G_POINT = 511
    """ 刺激G点 """
    STATUS_WOMB_OS_CARESS = 512
    """ 玩弄子宫口 """
    STATUS_WOMB_INSERTION = 513
    """ 插入子宫口 """
    STATUS_WOMB_SEX = 514
    """ 子宫姦 """
    STATUS_EXTERNAL_WOMB_MASSAGE = 515
    """ 体外子宫按摩 """
    STATUS_NORMAL_ANAL_SEX = 521
    """ 正常位肛交 """
    STATUS_BACK_ANAL_SEX = 522
    """ 后背位肛交 """
    STATUS_RIDING_ANAL_SEX = 523
    """ 对面骑乘位肛交 """
    STATUS_FACE_SEAT_ANAL_SEX = 524
    """ 对面座位肛交 """
    STATUS_BACK_SEAT_ANAL_SEX = 525
    """ 背面座位肛交 """
    STATUS_FACE_STAND_ANAL_SEX = 526
    """ 对面立位肛交 """
    STATUS_BACK_STAND_ANAL_SEX = 527
    """ 背面立位肛交 """
    STATUS_BACK_RIDING_ANAL_SEX = 528
    """ 背面骑乘位肛交 """
    STATUS_STIMULATE_SIGMOID_COLON = 530
    """ 玩弄s状结肠 """
    STATUS_STIMULATE_VAGINA = 531
    """ 隔着刺激阴道 """
    STATUS_URETHRAL_FINGER_INSERTION = 541
    """ 尿道指姦 """
    STATUS_URETHRAL_SEX = 542
    """ 尿道姦 """
    STATUS_FACE_HUG_SEX = 551
    """ 对面抱位 """
    STATUS_BACK_HUG_SEX = 552
    """ 背面抱位 """
    STATUS_FACE_LAY_SEX = 553
    """ 对面卧位 """
    STATUS_BACK_LAY_SEX = 554
    """ 背面卧位 """
    STATUS_FACE_HUG_ANAL_SEX = 561
    """ 对面抱位肛交 """
    STATUS_BACK_HUG_ANAL_SEX = 562
    """ 背面抱位肛交 """
    STATUS_FACE_LAY_ANAL_SEX = 563
    """ 对面卧位肛交 """
    STATUS_BACK_LAY_ANAL_SEX = 564
    """ 背面卧位肛交 """
    STATUS_MILKING_MACHINE_ON = 601
    """ 装上搾乳机 """
    STATUS_URINE_COLLECTOR = 602
    """ 装上采尿器 """
    STATUS_BIND = 603
    """ 捆绑 """
    STATUS_PATCH_ON = 604
    """ 戴上眼罩 """
    STATUS_WHIP = 605
    """ 鞭子 """
    STATUS_NEEDLE = 606
    """ 针 """
    STATUS_GAG_ON = 607
    """ 戴上口球 """
    STATUS_MILKING_MACHINE_OFF = 631
    """ 取下搾乳机 """
    STATUS_URINE_COLLECTOR_OFF = 632
    """ 取下采尿器 """
    STATUS_UNBIND = 633
    """ 解除捆绑 """
    STATUS_PATCH_OFF = 634
    """ 摘下眼罩 """
    STATUS_GAG_OFF = 635
    """ 摘下口球 """
    STATUS_EXERCISE_SUCKING_AND_SWALLOWING = 681
    """ 练习吮吸与吞咽力 """
    STATUS_EXERCISE_ARMPIT_CLAMPING = 682
    """ 练习腋下夹持力 """
    STATUS_EXERCISE_BREAST_CLAMPING = 683
    """ 练习胸部夹持力 """
    STATUS_EXERCISE_HANDS_FLEXIBILITY = 684
    """ 练习手部灵活度 """
    STATUS_EXERCISE_FOOTS_FLEXIBILITY = 685
    """ 练习足部灵活度 """
    STATUS_EXERCISE_VAGINA_FIRMNESS = 686
    """ 练习阴道紧致度 """
    STATUS_EXERCISE_INTESTINE_FIRMNESS = 687
    """ 练习肠道紧致度 """
    STATUS_EXERCISE_TAIL_FLEXIBILITY = 688
    """ 练习尾巴灵活度 """
    STATUS_EXERCISE_TENTACLE_FLEXIBILITY = 689
    """ 练习触手灵活度 """
    STATUS_UNDRESS = 701
    """ 脱衣服 """
    STATUS_HAT_JOB = 710
    """ 帽子交 """
    STATUS_GLASSES_JOB = 711
    """ 眼镜交 """
    STATUS_EAR_ORNAMENT_JOB = 712
    """ 耳饰交 """
    STATUS_NECK_ORNAMENT_JOB = 713
    """ 脖饰交 """
    STATUS_MOUTH_ORNAMENT_JOB = 714
    """ 口罩交 """
    STATUS_TOP_JOB = 715
    """ 上衣交 """
    STATUS_CORSET_JOB = 716
    """ 胸衣交 """
    STATUS_GLOVES_JOB = 717
    """ 手套交 """
    STATUS_SKIRT_JOB = 718
    """ 裙子交 """
    STATUS_UNDERWEAR_JOB = 719
    """ 内裤交 """
    STATUS_SOCKS_JOB = 720
    """ 袜子交 """
    STATUS_SHOES_JOB = 721
    """ 鞋子交 """
    STATUS_WEAPONS_JOB = 722
    """ 武器交 """
    STATUS_TROUSERS_JOB = 723
    """ 裤子交 """
    STATUS_ORGASM_EDGE_ON = 751
    """ 绝顶寸止 """
    STATUS_ORGASM_EDGE_OFF = 752
    """ 绝顶解放 """
    STATUS_SPANKING = 771
    """ 打屁股 """

    STATUS_HOLD_CHILD = 801
    """ 抱小孩 """
    STATUS_SING_CHILDREN_SONG = 802
    """ 哼唱儿歌 """
    STATUS_NUIRSE_CHILD = 803
    """ 喂奶 """
    STATUS_CHANGE_DIAPERS = 804
    """ 换尿布 """
    STATUS_TEACH_TALK = 805
    """ 教说话 """
    STATUS_GIVE_TOY = 806
    """ 给玩具 """

    STATUS_EXAMINE_HAIR = 850
    """ 检查头发 """
    STATUS_EXAMINE_HAIR_SMOOTHNESS = 851
    """ 测试头发柔顺度 """
    STATUS_EXAMINE_ORAL = 852
    """ 检查口腔内部 """
    STATUS_EXAMINE_SUCKING_AND_SWALLOWING = 853
    """ 测试口腔吮吸与吞咽力 """
    STATUS_EXAMINE_ARMPIT = 854
    """ 检查腋下 """
    STATUS_EXAMINE_ARMPIT_CLAMPING = 855
    """ 测试腋下夹持力 """
    STATUS_EXAMINE_BREAST = 856
    """ 检查胸部 """
    STATUS_EXAMINE_NIPPLE_AND_AREOLA = 857
    """ 检查乳头与乳晕 """
    STATUS_EXAMINE_BREAST_CLAMPING = 858
    """ 测试胸部夹持力 """
    STATUS_EXAMINE_CILITORIS = 859
    """ 检查阴蒂 """
    STATUS_EXAMINE_HANDS = 860
    """ 检查手部 """
    STATUS_EXAMINE_HANDS_FLEXIBILITY = 861
    """ 测试手部灵活度 """
    STATUS_EXAMINE_FOOT = 862
    """ 检查足部 """
    STATUS_EXAMINE_FOOTS_FLEXIBILITY = 863
    """ 测试足部灵活度 """
    STATUS_EXAMINE_VULVA_AND_SHAPE = 871
    """ 检查外阴形状 """
    STATUS_EXAMINE_VAGINA_AND_FOLDS = 872
    """ 检查内阴褶皱 """
    STATUS_EXAMINE_HYMEN = 873
    """ 检查处女膜 """
    STATUS_EXAMINE_ORIFICE = 874
    """ 检查子宫口 """
    STATUS_EXAMINE_VAGINA_FIRMNESS = 875
    """ 测试阴道紧致度 """
    STATUS_EXAMINE_ANUS = 876
    """ 检查菊穴 """
    STATUS_EXAMINE_INTESTINE_FIRMNESS = 877
    """ 测试肠道紧致度 """
    STATUS_EXAMINE_URETHRA = 878
    """ 检查尿道 """
    STATUS_EXAMINE_URINATION_STATUS = 879
    """ 测试现场排尿 """
    STATUS_EXAMINE_TAIL = 881
    """ 检查尾巴 """
    STATUS_EXAMINE_TAIL_FLEXIBILITY = 882
    """ 测试尾巴灵活度 """
    STATUS_EXAMINE_HORN = 883
    """ 检查兽角 """
    STATUS_EXAMINE_EARS = 884
    """ 检查兽耳 """
    STATUS_EXAMINE_WING = 885
    """ 检查翅膀 """
    STATUS_EXAMINE_RING = 886
    """ 检查光环 """
    STATUS_EXAMINE_TENTACLE = 887
    """ 检查触手 """
    STATUS_EXAMINE_TENTACLE_FLEXIBILITY = 888
    """ 测试触手灵活度 """

    STATUS_PENETRATING_VISION_ON = 901
    """ 开启透视 """
    STATUS_PENETRATING_VISION_OFF = 902
    """ 关闭透视 """
    STATUS_HORMONE_ON = 903
    """ 开启信息素 """
    STATUS_HORMONE_OFF = 904
    """ 关闭信息素 """
    STATUS_HYPNOSIS_ONE = 911
    """ 单人催眠 """
    STATUS_HYPNOSIS_ALL = 912
    """ 集体催眠 """
    STATUS_HYPNOSIS_CANCEL = 913
    """ 解除催眠 """
    STATUS_HYPNOSIS_INCREASE_BODY_SENSITIVITY = 921
    """ 体控-敏感度提升 """
    STATUS_HYPNOSIS_FORCE_CLIMAX = 922
    """ 体控-强制高潮 """
    STATUS_HYPNOSIS_FORCE_OVULATION = 923
    """ 体控-强制排卵 """
    STATUS_HYPNOSIS_BLOCKHEAD = 924
    """ 体控-木头人 """
    STATUS_HYPNOSIS_ACTIVE_H = 925
    """ 体控-逆推 """
    STATUS_HYPNOSIS_ROLEPLAY = 931
    """ 心控-角色扮演 """
    STATUS_HYPNOSIS_PAIN_AS_PLEASURE = 932
    """ 心控-苦痛快感化 """
    STATUS_TIME_STOP_ON = 941
    """ 时间停止流动 """
    STATUS_TIME_STOP_OFF = 942
    """ 时间重新流动 """
    STATUS_CARRY_TARGET = 943
    """ 搬运对方 """
    STATUS_STOP_CARRY_TARGET = 944
    """ 停止搬运对方 """
    STATUS_TARGET_FREE_IN_TIME_STOP = 945
    """ 在时停中正常行动 """
    STATUS_TARGET_STOP_IN_TIME_STOP = 946
    """ 在时停中再次停止 """

