class Instruct:
    """指令id"""

    #系统#
    MOVE = 0
    """ 移动 """
    SEE_ATTR = 0
    """ 查看属性 """
    ITEM = 0
    """ 道具 """
    ORIGINIUM_ARTS = 0
    """ 源石技艺 """
    TARGET_TO_SELF = 0
    """ 对自己交互 """
    DOOR_LOCK_INNER = 0  
    """ 锁上门内侧锁 """
    DOOR_UNLOCK_INNER = 0  
    """ 解开门内侧锁 """
    SAVE = 0
    """ 读写存档 """
    ABL_UP = 0
    """ 属性升级 """
    OWNER_ABL_UP = 0
    """ 自身属性升级 """
    SEE_DIRTY = 0
    """ 查看污浊情况 """
    SYSTEM_SETTING = 0
    """ 系统设置 """
    CHAT_WITH_AI = 0
    """ 与文本生成AI对话 """
    DEBUG_MODE_ON = 0
    """ 开启debug模式 """
    DEBUG_MODE_OFF = 0
    """ 关闭debug模式 """
    DEBUG_ADJUST = 0
    """ debug数值调整 """
    CHARA_DIY_INSTRUCT = 0
    """ 角色自定义特殊指令 """
    TALK_QUICK_TEST = 0
    """ 快速测试口上 """

    #日常#
    WAIT = 0
    """ 等待五分钟 """
    WAIT_1_HOUR = 0
    """ 等待一个小时 """
    WAIT_6_HOUR = 0
    """ 等待六个小时 """
    CHAT = 0
    """ 聊天 """
    STROKE = 0
    """ 身体接触 """
    MASSAGE = 0
    """ 按摩 """
    MAKE_COFFEE = 0
    """ 泡咖啡 """
    ASK_MAKE_COFFEE = 0
    """ 让对方泡咖啡 """
    MAKE_FOOD = 0
    """ 做饭 """
    EAT = 0
    """ 进食 """
    # GIVE_FOOD = 0
    # """ 让对方食用 """
    PUT_SELFMADE_FOOD_IN = 0
    """ 放入正常食物 """
    REST = 0
    """ 休息 """
    DIRAY = 0
    """ 日记 """
    SLEEP = 0
    """ 睡觉 """
    TAKE_SHOWER = 0
    """ 淋浴 """
    BUY_H_ITEM = 0
    """ 购买成人用品 """
    BUY_FOOD = 0
    """ 购买食物 """
    ALL_NPC_POSITION = 0
    """ 干员位置一览 """
    FOLLOW = 0
    """ 邀请同行 """
    END_FOLLOW = 0
    """ 结束同行 """
    APOLOGIZE = 0
    """ 道歉 """
    LISTEN_COMPLAINT = 0
    """ 听牢骚 """
    COLLCET_PANTY = 0
    """ 收起内裤 """
    ASK_DATE = 0
    """ 邀请约会 """
    DRINK_ALCOHOL = 0
    """ 劝酒 """
    PEE = 0
    """ 解手 """
    COLLECT = 0
    """ 摆放藏品 """
    TAKE_CARE_BABY = 0
    """ 照顾婴儿 """
    ORDER_HOTEL_ROOM = 0
    """ 预定房间 """

    #娱乐#
    SINGING = 0
    """ 唱歌 """
    PLAY_INSTRUMENT = 0
    """ 演奏乐器 """
    LISTEN_INFLATION = 0
    """ 听肚子里的动静 """
    PLAY_WITH_CHILD = 0
    """ 一起玩耍 """
    EXERCISE = 0
    """ 锻炼身体 """
    BORROW_BOOK = 0
    """ 借阅书籍 """
    READ_BOOK = 0
    """ 读书 """
    WATCH_MOVIE = 0
    """ 看电影 """
    PHOTOGRAPHY = 0
    """ 摄影 """
    PLAY_WATER = 0
    """ 玩水 """
    PLAY_GOMOKU = 0
    """ 下五子棋 """
    PLAY_CHESS = 0
    """ 下棋 """
    PLAY_MAHJONG = 0
    """ 打麻将 """
    PLAY_CARDS = 0
    """ 打牌 """
    REHEARSE_DANCE = 0
    """ 排演舞剧 """
    PLAY_ARCADE_GAME = 0
    """ 玩街机游戏 """
    SWIMMING = 0
    """ 游泳 """
    TASTE_WINE = 0
    """ 品酒 """
    TASTE_TEA = 0
    """ 品茶 """
    TASTE_COFFEE = 0
    """ 品咖啡 """
    TASTE_DESSERT = 0
    """ 品尝点心 """
    TASTE_FOOD = 0
    """ 品尝美食 """
    PLAY_HOUSE = 0
    """ 过家家 """
    STYLE_HAIR = 0
    """ 修整发型 """
    FULL_BODY_STYLING = 0
    """ 全身造型服务 """
    SOAK_FEET = 0
    """ 泡脚 """
    STEAM_SAUNA = 0
    """ 蒸桑拿 """
    HYDROTHERAPY_TREATMENT = 0
    """ 水疗护理 """
    ONSEN_BATH = 0
    """ 泡温泉 """
    AROMATHERAPY = 0
    """ 香薰疗愈 """

    #工作#
    OFFICIAL_WORK = 0
    """ 处理公务 """
    BATTLE_COMMAND = 0
    """ 指挥作战 """
    FIELD_COMMISSION = 0
    """ 外勤委托 """
    TRAINING = 0
    """ 战斗训练 """
    CURE_PATIENT = 0
    """ 诊疗病人 """
    RECRUIT = 0
    """ 招募干员 """
    CONFIM_RECRUIT = 0
    """ 确认已招募的干员 """
    RECRUITMENT = 0
    """ 招募情况 """
    TEACH = 0
    """ 授课 """
    MAINTENANCE_FACILITIES = 0
    """ 维护设施 """
    REPAIR_EQUIPMENT = 0
    """ 维修装备 """
    ASSISTANT_ADJUSTMENTS = 0
    """ 助理相关调整 """
    BUILDING = 0
    """ 基建系统 """
    VISITOR_SYSTEM = 0
    """ 访客系统 """
    INVITE_VISITOR = 0
    """ 邀请访客 """
    NATION_DIPLOMACY = 0
    """ 势力外交 """
    DEAL_WITH_DIPLOMACY = 0
    """ 处理外交事宜 """
    PRTS = 0
    """ 普瑞赛斯 """
    MANAGE_LIBRARY = 0
    """ 管理图书馆 """
    MANAGE_ASSEMBLY_LINE = 0
    """ 管理流水线 """
    MANAGE_AGRICULTURE = 0
    """ 管理农业生产 """
    MANAGE_VEHICLE = 0
    """ 管理载具 """
    PHYSICAL_CHECK_AND_MANAGE = 0
    """ 身体检查与管理 """
    MANAGE_CONFINEMENT_AND_TRAINING = 0
    """ 管理监禁调教 """
    RESOURCE_EXCHANGE = 0
    """ 资源交易 """
    NAVIGATION = 0
    """ 导航 """
    SEE_COLLECTION = 0
    """ 查看收藏品 """
    SEE_FRIDGE = 0
    """ 查看冰箱 """
    MANAGE_BASEMENT = 0
    """ 管理罗德岛 """

    #源石技艺#
    HYPNOSIS_ONE = 0
    """ 单人催眠 """
    DEEPENING_HYPNOSIS = 0
    """ 加深催眠 """
    HYPNOSIS_ALL = 0
    """ 集体催眠 """
    CHANGE_HYPNOSIS_MODE = 0
    """ 切换催眠模式 """
    HYPNOSIS_CANCEL = 0
    """ 解除催眠 """
    HYPNOSIS_INCREASE_BODY_SENSITIVITY = 0
    """ 体控-敏感度提升 """
    HYPNOSIS_FORCE_CLIMAX = 0
    """ 体控-强制高潮 """
    HYPNOSIS_FORCE_OVULATION = 0
    """ 体控-强制排卵 """
    HYPNOSIS_BLOCKHEAD = 0
    """ 体控-木头人 """
    HYPNOSIS_ACTIVE_H = 0
    """ 体控-逆推 """
    HYPNOSIS_ROLEPLAY = 0
    """ 心控-角色扮演 """
    HYPNOSIS_PAIN_AS_PLEASURE = 0
    """ 心控-苦痛快感化 """
    PENETRATING_VISION_ON = 0
    """ 开启透视 """
    PENETRATING_VISION_OFF = 0
    """ 关闭透视 """
    HORMONE_ON = 0
    """ 开启信息素 """
    HORMONE_OFF = 0
    """ 关闭信息素 """
    TIME_STOP_ON = 0
    """ 时间停止流动 """
    TIME_STOP_OFF = 0
    """ 时间重新流动 """
    CARRY_TARGET = 0
    """ 搬运对方 """
    STOP_CARRY_TARGET = 0
    """ 停止搬运对方 """
    TARGET_FREE_IN_TIME_STOP = 0
    """ 对方在时停中获得自由 """
    TARGET_STOP_IN_TIME_STOP = 0
    """ 对方在时停中再次停止 """

    #猥亵#
    MAKE_COFFEE_ADD = 0
    """ 泡咖啡（加料） """
    TOUCH_HEAD = 0
    """ 摸头 """
    TOUCH_BREAST = 0
    """ 摸胸 """
    TOUCH_BUTTOCKS = 0
    """ 摸屁股 """
    TOUCH_EARS = 0
    """ 摸耳朵 """
    TOUCH_HORN = 0
    """ 摸角 """
    TOUCH_TAIL = 0
    """ 摸尾巴 """
    TOUCH_RING = 0
    """ 摸光环 """
    TOUCH_WING = 0
    """ 摸翅膀 """
    TOUCH_TENTACLE = 0
    """ 摸触手 """
    TOUCH_CAR = 0
    """ 摸小车 """
    HAND_IN_HAND = 0
    """ 牵手 """
    EMBRACE = 0
    """ 拥抱 """
    KISS = 0
    """ 亲吻 """
    LAP_PILLOW = 0
    """ 膝枕 """
    RAISE_SKIRT = 0
    """ 掀起裙子 """
    ASK_FOR_PAN = 0
    """ 索要内裤 """
    ASK_FOR_SOCKS = 0
    """ 索要袜子 """
    STEAL_PAN = 0
    """ 偷走内裤 """
    STEAL_SOCKS = 0
    """ 偷走袜子 """
    STEAL_SCENE_ALL_PAN = 0
    """ 偷走所有人内裤 """
    STEAL_SCENE_ALL_SOCKS = 0
    """ 偷走所有人袜子 """
    TOUCH_CLITORIS = 0
    """ 阴蒂爱抚 """
    TOUCH_VAGINA = 0
    """ 手指插入（V） """
    TOUCH_ANUS = 0
    """ 手指插入（A） """
    MILK = 0
    """ 挤奶 """
    BAGGING_AND_MOVING = 0
    """ 装袋搬走 """
    PUT_INTO_PRISON = 0
    """ 投入监牢 """
    SET_FREE = 0
    """ 解除囚禁 """
    CHECK_LOCKER = 0
    """ 检查衣柜 """
    CONFESSION = 0
    """ 告白 """
    GIVE_NECKLACE = 0
    """ 戴上项圈 """
    PREPARE_TRAINING = 0
    """ 调教前准备 """
    SWITCH_TO_H_INTERFACE = 0
    """ 切换到H """
    SLEEP_OBSCENITY = 0
    """ 睡眠猥亵 """
    STOP_SLEEP_OBSCENITY = 0
    """ 停止睡眠猥亵 """
    DO_H = 0
    """ 邀请H """
    DO_H_IN_LOVE_HOTEL = 0
    """ 邀请在爱情旅馆H """
    UNCONSCIOUS_H = 0
    """ 无意识奸 """
    ASK_HIDDEN_SEX = 0
    """ 邀请隐奸 """
    ASK_GROUP_SEX = 0
    """ 邀请群交 """

    #性爱#
    WAIT_5_MIN_IN_H = 0
    """ 等待五分钟(H中) """
    END_H = 0
    """ H结束 """
    GROUP_SEX_END = 0
    """ 结束群交 """
    UNDRESS = 0
    """ 脱衣服 """
    CHANGE_TOP_AND_BOTTOM = 0
    """ 交给对方 """
    KEEP_ENJOY = 0
    """ 继续享受 """
    TRY_PL_ACTIVE_H = 0
    """ 尝试掌握主动权 """
    ORGASM_EDGE_ON = 0
    """ 绝顶寸止 """
    ORGASM_EDGE_OFF = 0
    """ 绝顶解放 """
    RUN_GROUP_SEX_TEMPLE = 0
    """ 进行一次当前群交 """
    RUN_ALL_GROUP_SEX_TEMPLE = 0
    """ 进行一次轮流群交 """
    EDIT_GROUP_SEX_TEMPLE = 0
    """ 编辑群交行动 """
    SWITCH_TO_NON_H_INTERFACE = 0
    """ 切换到非H """
    MAKING_OUT = 0
    """ 身体爱抚 """
    KISS_H = 0
    """ 接吻 """
    BREAST_CARESS = 0
    """ 胸爱抚 """
    TWIDDLE_NIPPLES = 0
    """ 玩弄乳头 """
    BREAST_SUCKING = 0
    """ 舔吸乳头 """
    EXTERNAL_WOMB_MASSAGE = 0
    """ 体外子宫按摩 """
    CLIT_CARESS = 0
    """ 阴蒂爱抚 """
    OPEN_LABIA = 0
    """ 掰开阴唇观察 """
    OPEN_ANUS = 0
    """ 掰开肛门观察 """
    CUNNILINGUS = 0
    """ 舔阴 """
    LICK_ANAL = 0
    """ 舔肛 """
    FINGER_INSERTION = 0
    """ 手指插入(V) """
    ANAL_CARESS = 0
    """ 手指插入(A) """
    MAKE_MASTUREBATE = 0
    """ 命令对方自慰 """
    MAKE_LICK_ANAL = 0
    """ 命令对方舔自己肛门 """
    ASK_PEE = 0
    """ 命令对方小便 """
    SEDECU = 0
    """ 诱惑 """
    HANDJOB = 0
    """ 手交 """
    BLOWJOB = 0
    """ 口交 """
    PAIZURI = 0
    """ 乳交 """
    FOOTJOB = 0
    """ 足交 """
    HAIRJOB = 0
    """ 发交 """
    AXILLAJOB = 0
    """ 腋交 """
    RUB_BUTTOCK = 0
    """ 素股 """
    HAND_BLOWJOB = 0
    """ 手交口交 """
    TITS_BLOWJOB = 0
    """ 乳交口交 """
    FOCUS_BLOWJOB = 0
    """ 真空口交 """
    DEEP_THROAT = 0
    """ 深喉插入 """
    CLEAN_BLOWJOB = 0
    """ 清洁口交 """
    SIXTY_NINE = 0
    """ 六九式 """
    LEGJOB = 0
    """ 腿交 """
    TAILJOB = 0
    """ 尾交 """
    FACE_RUB = 0
    """ 阴茎蹭脸 """
    HORN_RUB = 0
    """ 阴茎蹭角 """
    EARS_RUB = 0
    """ 阴茎蹭耳朵 """
    HAT_JOB = 0
    """ 帽子交 """
    GLASSES_JOB = 0
    """ 眼镜交 """
    EAR_ORNAMENT_JOB = 0
    """ 耳饰交 """
    NECK_ORNAMENT_JOB = 0
    """ 脖饰交 """
    MOUTH_ORNAMENT_JOB = 0
    """ 口罩交 """
    TOP_JOB = 0
    """ 上衣交 """
    CORSET_JOB = 0
    """ 胸衣交 """
    GLOVES_JOB = 0
    """ 手套交 """
    SKIRT_JOB = 0
    """ 裙子交 """
    TROUSERS_JOB = 0
    """ 裤子交 """
    UNDERWEAR_JOB = 0
    """ 内裤交 """
    SOCKS_JOB = 0
    """ 袜子交 """
    SHOES_JOB = 0
    """ 鞋子交 """
    WEAPONS_JOB = 0
    """ 武器交 """
    BODY_LUBRICANT = 0
    """ 润滑液 """
    BIRTH_CONTROL_PILLS = 0
    """ 避孕药 """
    PHILTER = 0
    """ 媚药 """
    ENEMAS = 0
    """ 灌肠液_已废弃 """
    DIURETICS_ONCE = 0
    """ 一次性利尿剂 """
    DIURETICS_PERSISTENT = 0
    """ 持续性利尿剂 """
    SLEEPING_PILLS = 0
    """ 安眠药 """
    CLOMID = 0
    """ 排卵促进药 """
    BIRTH_CONTROL_PILLS_BEFORE = 0
    """ 事前避孕药 """
    BIRTH_CONTROL_PILLS_AFTER = 0
    """ 事后避孕药 """
    PUT_CONDOM = 0
    """ 戴上避孕套 """
    TAKE_CONDOM_OUT = 0
    """ 摘掉避孕套 """
    URETHRAL_SWAB = 0
    """ 尿道棉棒 """
    NIPPLES_LOVE_EGG = 0
    """ 乳头跳蛋 """
    NIPPLE_CLAMP_ON = 0
    """ 戴上乳头夹 """
    NIPPLE_CLAMP_OFF = 0
    """ 取下乳头夹 """
    CLIT_LOVE_EGG = 0
    """ 阴蒂跳蛋 """
    CLIT_CLAMP_ON = 0
    """ 戴上阴蒂夹 """
    CLIT_CLAMP_OFF = 0
    """ 取下阴蒂夹 """
    ELECTRIC_MESSAGE_STICK = 0
    """ 电动按摩棒 """
    VIBRATOR_INSERTION = 0
    """ 插入震动棒 """
    BIG_VIBRATOR_INSERTION = 0
    """ 加粗震动棒 """
    HUGE_VIBRATOR_INSERTION = 0
    """ 巨型震动棒 """
    VIBRATOR_INSERTION_OFF = 0
    """ 拔出振动棒 """
    VIBRATOR_INSERTION_ANAL = 0
    """ 肛门插入振动棒 """
    BIG_VIBRATOR_INSERTION_ANAL = 0
    """ 加粗肛门震动棒 """
    HUGE_VIBRATOR_INSERTION_ANAL = 0
    """ 巨型肛门震动棒 """
    VIBRATOR_INSERTION_ANAL_OFF = 0
    """ 拔出肛门振动棒 """
    ANAL_BEADS = 0
    """ 塞入肛门拉珠 """
    ANAL_BEADS_OFF = 0
    """ 拔出肛门拉珠 """
    MILKING_MACHINE_ON = 0
    """ 装上搾乳机 """
    MILKING_MACHINE_OFF = 0
    """ 取下搾乳机 """
    URINE_COLLECTOR_ON = 0
    """ 装上采尿器 """
    URINE_COLLECTOR_OFF = 0
    """ 取下采尿器 """
    BEAT_BREAST = 0
    """ 打胸部 """
    SPANKING = 0
    """ 打屁股 """
    BONDAGE = 0
    """ 绳艺 """
    PATCH_ON = 0
    """ 戴上眼罩 """
    PATCH_OFF = 0
    """ 摘下眼罩 """
    GAG_ON = 0
    """ 戴上口球 """
    GAG_OFF = 0
    """ 摘下口球 """
    CLYSTER = 0
    """ 灌肠 """
    CONTINUE_CLYSTER = 0
    """ 继续灌肠 """
    ANAL_PLUG = 0
    """ 肛塞_已废弃 """
    CLYSTER_END = 0
    """ 拔出肛塞 """
    SAFE_CANDLES = 0
    """ 滴蜡 """
    WHIP = 0
    """ 鞭子 """
    NEEDLE = 0
    """ 针 """
    NORMAL_SEX = 0
    """ 正常位 """
    BACK_SEX = 0
    """ 背后位 """
    RIDING_SEX = 0
    """ 对面骑乘位 """
    BACK_RIDING_SEX = 0
    """ 背面骑乘位 """
    FACE_SEAT_SEX = 0
    """ 对面座位 """
    BACK_SEAT_SEX = 0
    """ 背面座位 """
    FACE_STAND_SEX = 0
    """ 对面立位 """
    BACK_STAND_SEX = 0
    """ 背面立位 """
    FACE_HUG_SEX = 0
    """ 对面抱位 """
    BACK_HUG_SEX = 0
    """ 背面抱位 """
    FACE_LAY_SEX = 0
    """ 对面卧位 """
    BACK_LAY_SEX = 0
    """ 背面卧位 """
    STIMULATE_G_POINT = 0
    """ 刺激G点 """
    WOMB_OS_CARESS = 0
    """ 玩弄子宫口 """
    WOMB_INSERTION = 0
    """ 插入子宫口 """
    WOMB_SEX = 0
    """ 子宫姦 """
    NORMAL_ANAL_SEX = 0
    """ 正常位肛交 """
    BACK_ANAL_SEX = 0
    """ 后背位肛交 """
    RIDING_ANAL_SEX = 0
    """ 对面骑乘位肛交 """
    BACK_RIDING_ANAL_SEX = 0
    """ 背面骑乘位肛交 """
    FACE_SEAT_ANAL_SEX = 0
    """ 对面座位肛交 """
    BACK_SEAT_ANAL_SEX = 0
    """ 背面座位肛交 """
    FACE_STAND_ANAL_SEX = 0
    """ 对面立位肛交 """
    BACK_STAND_ANAL_SEX = 0
    """ 背面立位肛交 """
    FACE_HUG_ANAL_SEX = 0
    """ 对面抱位肛交 """
    BACK_HUG_ANAL_SEX = 0
    """ 背面抱位肛交 """
    FACE_LAY_ANAL_SEX = 0
    """ 对面卧位肛交 """
    BACK_LAY_ANAL_SEX = 0
    """ 背面卧位肛交 """
    STIMULATE_SIGMOID_COLON = 0
    """ 玩弄s状结肠 """
    STIMULATE_VAGINA = 0
    """ 隔着刺激阴道 """
    DOUBLE_PENETRATION = 0
    """ 二穴插入 """
    URETHRAL_FINGER_INSERTION = 0
    """ 尿道指姦 """
    URETHRAL_SEX = 0
    """ 尿道姦 """
    SHAME_PLAY = 0
    """ 羞耻play """
    TAKE_SHOWER_H = 0
    """ 淋浴 """
    BUBBLE_BATH = 0
    """ 泡泡浴 """
    GIVE_BLOWJOB = 0
    """ 给对方口交 """

