class SecondBehavior:
    """二段结算行为函数"""

    N_orgasm_small = 1000
    """ 结算N小绝顶 """
    N_orgasm_normal = 1001
    """ 结算N普绝顶 """
    N_orgasm_strong = 1002
    """ 结算N强绝顶 """
    B_orgasm_small = 1003
    """ 结算B小绝顶 """
    B_orgasm_normal = 1004
    """ 结算B普绝顶 """
    B_orgasm_strong = 1005
    """ 结算B强绝顶 """
    C_orgasm_small = 1006
    """ 结算C小绝顶 """
    C_orgasm_normal = 1007
    """ 结算C普绝顶 """
    C_orgasm_strong = 1008
    """ 结算C强绝顶 """
    P_orgasm_small = 1009
    """ 结算射精 """
    P_orgasm_normal = 1010
    """ 结算大量射精 """
    P_orgasm_strong = 1011
    """ 结算超大量射精 """
    V_orgasm_small = 1012
    """ 结算V小绝顶 """
    V_orgasm_normal = 1013
    """ 结算V普绝顶 """
    V_orgasm_strong = 1014
    """ 结算V强绝顶 """
    A_orgasm_small = 1015
    """ 结算A小绝顶 """
    A_orgasm_normal = 1016
    """ 结算A普绝顶 """
    A_orgasm_strong = 1017
    """ 结算A强绝顶 """
    U_orgasm_small = 1018
    """ 结算U小绝顶 """
    U_orgasm_normal = 1019
    """ 结算U普绝顶 """
    U_orgasm_strong = 1020
    """ 结算U强绝顶 """
    W_orgasm_small = 1021
    """ 结算W小绝顶 """
    W_orgasm_normal = 1022
    """ 结算W普绝顶 """
    W_orgasm_strong = 1023
    """ 结算W强绝顶 """
    EXTRA_ORGASM = 1026
    """ 结算额外绝顶 """
    SEMEN_DRINKING_CLIMAX = 1027
    """ 结算饮精绝顶 """
    HAPPY_MARK_1 = 1030
    """ 结算快乐刻印1 """
    HAPPY_MARK_2 = 1031
    """ 结算快乐刻印2 """
    HAPPY_MARK_3 = 1032
    """ 结算快乐刻印3 """
    YIELD_MARK_1 = 1033
    """ 结算屈服刻印1 """
    YIELD_MARK_2 = 1034
    """ 结算屈服刻印2 """
    YIELD_MARK_3 = 1035
    """ 结算屈服刻印3 """
    PAIN_MARK_1 = 1036
    """ 结算苦痛刻印1 """
    PAIN_MARK_2 = 1037
    """ 结算苦痛刻印2 """
    PAIN_MARK_3 = 1038
    """ 结算苦痛刻印3 """
    TIME_MARK_1 = 1039
    """ 结算时姦刻印1 """
    TIME_MARK_2 = 1040
    """ 结算时姦刻印2 """
    TIME_MARK_3 = 1041
    """ 结算时姦刻印3 """
    TERROR_MARK_1 = 1042
    """ 结算恐怖刻印1 """
    TERROR_MARK_2 = 1043
    """ 结算恐怖刻印2 """
    TERROR_MARK_3 = 1044
    """ 结算恐怖刻印3 """
    HATE_MARK_1 = 1045
    """ 结算反发刻印1 """
    HATE_MARK_2 = 1046
    """ 结算反发刻印2 """
    HATE_MARK_3 = 1047
    """ 结算反发刻印3 """
    FIRST_KISS = 1050
    """ 结算初吻 """
    FIRST_SEX = 1051
    """ 结算处女 """
    FIRST_A_SEX = 1052
    """ 结算A处女 """
    UNCONSCIOUS_MARK_1 = 1061
    """ 结算无觉刻印1 """
    UNCONSCIOUS_MARK_2 = 1062
    """ 结算无觉刻印2 """
    UNCONSCIOUS_MARK_3 = 1063
    """ 结算无觉刻印3 """
    UNCONSCIOUS_MARK_4 = 1064
    """ 结算无觉刻印4 """
    UNCONSCIOUS_MARK_5 = 1065
    """ 结算无觉刻印5 """
    UNCONSCIOUS_MARK_6 = 1066
    """ 结算无觉刻印6 """

    B_ORGASM_TO_MILK = 1071
    """ 结算因B绝顶而被迫喷乳 """
    U_ORGASM_TO_PEE = 1072
    """ 结算因U绝顶而被迫漏尿 """

    DOUBLE_ORGASM = 1081
    """ 结算双重绝顶 """
    TRIPLE_ORGASM = 1082
    """ 结算三重绝顶 """
    QUADRUPLE_ORGASM = 1083
    """ 结算四重绝顶 """
    QUINTUPLE_ORGASM = 1084
    """ 结算五重绝顶 """
    SEXTUPLE_ORGASM = 1085
    """ 结算六重绝顶 """
    SEPTUPLE_ORGASM = 1086
    """ 结算七重绝顶 """

    N_ORGASM_SUPER = 1090
    """ 结算N超强绝顶 """
    B_ORGASM_SUPER = 1091
    """ 结算B超强绝顶 """
    C_ORGASM_SUPER = 1092
    """ 结算C超强绝顶 """
    V_ORGASM_SUPER = 1094
    """ 结算V超强绝顶 """
    A_ORGASM_SUPER = 1095
    """ 结算A超强绝顶 """
    U_ORGASM_SUPER = 1096
    """ 结算U超强绝顶 """
    W_ORGASM_SUPER = 1097
    """ 结算W超强绝顶 """

    NIPPLE_CLAMP = 1100
    """ 结算乳头夹 """
    CLIT_CLAMP = 1101
    """ 结算阴蒂夹 """
    VIBRATOR_INSERTION = 1102
    """ 结算震动棒 """
    VIBRATOR_INSERTION_ANAL = 1103
    """ 结算肛门振动棒 """
    MILKING_MACHINE = 1104
    """ 结算搾乳机 """
    URINE_COLLECTOR = 1105
    """ 结算采尿器 """
    PATCH = 1106
    """ 结算眼罩 """
    ANAL_BEADS = 1107
    """ 结算肛门拉珠 """
    DIURETICS = 1108
    """ 结算利尿剂 """
    SLEEPING_PILLS = 1109
    """ 结算安眠药 """
    SLEEPING_CLOMID = 1110
    """ 结算排卵促进药 """
    SLEEPING_BIRTH_CONTROL_PILLS_BEFORE = 1111
    """ 结算事前避孕药 """
    SLEEPING_BIRTH_CONTROL_PILLS_AFTER = 1112
    """ 结算事后避孕药 """
    GAG = 1114
    """ 结算口球 """

    CONDAGE = 1161
    """ 结算绳子捆绑 """

    PENIS_IN_HAIR = 1201
    """ 结算发交中 """
    PENIS_IN_FACE = 1202
    """ 结算阴茎蹭脸中 """
    PENIS_IN_MOUSE = 1203
    """ 结算口交中 """
    PENIS_IN_BREAST = 1204
    """ 结算乳交中 """
    PENIS_IN_AXILLA = 1205
    """ 结算腋交中 """
    PENIS_IN_HAND = 1206
    """ 结算手交中 """
    PENIS_IN_VAGINA = 1207
    """ 结算V插入中 """
    PENIS_IN_WOMB = 1208
    """ 结算W插入中 """
    PENIS_IN_ANAL = 1209
    """ 结算A插入中 """
    PENIS_IN_URETHRAL = 1210
    """ 结算U插入中 """
    PENIS_IN_LEG = 1211
    """ 结算腿交中 """
    PENIS_IN_FOOT = 1212
    """ 结算足交中 """
    PENIS_IN_TAIL = 1213
    """ 结算尾交中 """
    PENIS_IN_HORN = 1214
    """ 结算阴茎蹭角中 """
    PENIS_IN_EARS = 1215
    """ 结算阴茎蹭耳朵中 """
    PENIS_IN_RUB_BUTTOCK = 1216
    """ 结算素股中 """

    PENIS_IN_HAT_JOB = 1221
    """ 结算帽子交中 """
    PENIS_IN_GLASSES_JOB = 1222
    """ 结算眼镜交中 """
    PENIS_IN_EAR_ORNAMENT_JOB = 1223
    """ 结算耳饰交中 """
    PENIS_IN_NECK_ORNAMENT_JOB = 1224
    """ 结算脖饰交中 """
    PENIS_IN_MOUTH_ORNAMENT_JOB = 1225
    """ 结算口罩交中 """
    PENIS_IN_TOP_JOB = 1226
    """ 结算上衣交中 """
    PENIS_IN_CORSET_JOB = 1227
    """ 结算胸衣交中 """
    PENIS_IN_GLOVES_JOB = 1228
    """ 结算手套交中 """
    PENIS_IN_SKIRT_JOB = 1229
    """ 结算裙子交中 """
    PENIS_IN_UNDERWEAR_JOB = 1230
    """ 结算内裤交中 """
    PENIS_IN_SOCKS_JOB = 1231
    """ 结算袜子交中 """
    PENIS_IN_SHOES_JOB = 1232
    """ 结算鞋子交中 """
    PENIS_IN_WEAPONS_JOB = 1233
    """ 结算武器交中 """
    PENIS_IN_TROUSERS_JOB = 1234
    """ 结算裤子交中 """

    N_ORGASM_SUPER = 1250
    """ 结算N绝顶被寸止 """
    B_ORGASM_SUPER = 1251
    """ 结算B绝顶被寸止 """
    C_ORGASM_SUPER = 1252
    """ 结算C绝顶被寸止 """
    P_ORGASM_SUPER = 1253
    """ 结算射精被寸止 """
    V_ORGASM_SUPER = 1254
    """ 结算V绝顶被寸止 """
    A_ORGASM_SUPER = 1255
    """ 结算A绝顶被寸止 """
    U_ORGASM_SUPER = 1256
    """ 结算U绝顶被寸止 """
    W_ORGASM_SUPER = 1257
    """ 结算W绝顶被寸止 """

    IN_UNCONSCIOUS_CUM_ON_HAIR = 1260
    """ 恢复意识后发现头发出现精液 """
    IN_UNCONSCIOUS_CUM_ON_FACE = 1261
    """ 恢复意识后发现脸部出现精液 """
    IN_UNCONSCIOUS_CUM_ON_MOUTH = 1262
    """ 恢复意识后发现口腔出现精液 """
    IN_UNCONSCIOUS_CUM_ON_CHEST = 1263
    """ 恢复意识后发现胸部出现精液 """
    IN_UNCONSCIOUS_CUM_ON_ARMPIT = 1264
    """ 恢复意识后发现腋部出现精液 """
    IN_UNCONSCIOUS_CUM_ON_HAND = 1265
    """ 恢复意识后发现手部出现精液 """
    IN_UNCONSCIOUS_CUM_ON_VAGINA = 1266
    """ 恢复意识后发现小穴出现精液 """
    IN_UNCONSCIOUS_CUM_ON_WOMB = 1267
    """ 恢复意识后发现子宫出现精液 """
    IN_UNCONSCIOUS_CUM_ON_ANUS = 1268
    """ 恢复意识后发现后穴出现精液 """
    IN_UNCONSCIOUS_CUM_ON_URETHRA = 1269
    """ 恢复意识后发现尿道出现精液 """
    IN_UNCONSCIOUS_CUM_ON_LEG = 1270
    """ 恢复意识后发现腿部出现精液 """
    IN_UNCONSCIOUS_CUM_ON_FOOT = 1271
    """ 恢复意识后发现脚部出现精液 """
    IN_UNCONSCIOUS_CUM_ON_TAIL = 1272
    """ 恢复意识后发现尾巴出现精液 """
    IN_UNCONSCIOUS_CUM_ON_HORN = 1273
    """ 恢复意识后发现兽角出现精液 """
    IN_UNCONSCIOUS_CUM_ON_EARS = 1274
    """ 恢复意识后发现兽耳出现精液 """
    IN_UNCONSCIOUS_CUM_ON_STOMACH = 1275
    """ 恢复意识后发现胃部出现精液 """
    IN_UNCONSCIOUS_CUM_ON_CROTCH = 1276
    """ 恢复意识后发现胯部出现精液 """
    IN_UNCONSCIOUS_CUM_ON_BELLY = 1277
    """ 恢复意识后发现腹部出现精液 """
    IN_UNCONSCIOUS_CUM_ON_BACK = 1278
    """ 恢复意识后发现背部出现精液 """

    IN_UNCONSCIOUS_CUM_ON_HAT = 1280
    """ 恢复意识后发现帽子出现精液 """
    IN_UNCONSCIOUS_CUM_ON_GLASSES = 1281
    """ 恢复意识后发现眼镜出现精液 """
    IN_UNCONSCIOUS_CUM_ON_EAR_ORNAMENT = 1282
    """ 恢复意识后发现耳饰出现精液 """
    IN_UNCONSCIOUS_CUM_ON_NECK_ORNAMENT = 1283
    """ 恢复意识后发现脖饰出现精液 """
    IN_UNCONSCIOUS_CUM_ON_MOUTH_ORNAMENT = 1284
    """ 恢复意识后发现口饰出现精液 """
    IN_UNCONSCIOUS_CUM_ON_TOP = 1285
    """ 恢复意识后发现上衣出现精液 """
    IN_UNCONSCIOUS_CUM_ON_CORSET = 1286
    """ 恢复意识后发现胸衣出现精液 """
    IN_UNCONSCIOUS_CUM_ON_GLOVES = 1287
    """ 恢复意识后发现手套出现精液 """
    IN_UNCONSCIOUS_CUM_ON_SKIRT = 1288
    """ 恢复意识后发现下衣出现精液 """
    IN_UNCONSCIOUS_CUM_ON_UNDERWEAR = 1289
    """ 恢复意识后发现内裤出现精液 """
    IN_UNCONSCIOUS_CUM_ON_SOCKS = 1290
    """ 恢复意识后发现袜子出现精液 """
    IN_UNCONSCIOUS_CUM_ON_SHOES = 1291
    """ 恢复意识后发现鞋子出现精液 """
    IN_UNCONSCIOUS_CUM_ON_WEAPONS = 1292
    """ 恢复意识后发现武器出现精液 """
    IN_UNCONSCIOUS_CUM_ON_ACCESSORY = 1293
    """ 恢复意识后发现附属物出现精液 """

    IN_UNCONSCIOUS_STOLEN_PANTY = 1296
    """ 恢复意识后发现内裤被偷 """
    IN_UNCONSCIOUS_STOLEN_SOCKS = 1297
    """ 恢复意识后发现袜子被偷 """

    LOVE_1 = 1301
    """ 结算获得思慕 """
    LOVE_2 = 1302
    """ 结算获得恋慕 """
    LOVE_3 = 1303
    """ 结算获得恋人(含赠予信物) """
    LOVE_4 = 1304
    """ 结算获得爱侣 """
    OBEY_1 = 1305
    """ 结算获得屈从 """
    OBEY_2 = 1306
    """ 结算获得驯服 """
    OBEY_3 = 1307
    """ 结算获得宠物(含赠予信物)  """
    OBEY_4 = 1308
    """ 结算获得奴隶 """

    FERTILIZATION = 1311
    """ 结算获得受精 """
    FERTILIZATION_FAILD = 1312
    """ 结算受精失败 """
    PREGNANCY = 1313
    """ 结算获得妊娠 """
    PARTURIENT = 1314
    """ 结算获得临盆 """
    BORN = 1315
    """ 生产前的对话 """
    POSTPARTUM = 1317
    """ 生产后的对话+获得产后 """
    REARING = 1318
    """ 结算获得育儿 """
    REARING_COMPLETE = 1319
    """ 结算育儿完成 """
    CHILD_TO_LOLI = 1320
    """ 结算幼女长成萝莉 """
    LOLI_TO_GIRL = 1321
    """ 结算萝莉长成少女 """

    FIRST_MEET = 1331
    """ 初次见面 """
    DAY_HELLO = 1332
    """ 每日打招呼 """

    NEW_ROUND_FAREWELL = 1351
    """ 新周目告别 """

    START_FIELD_COMMISSION_AS_LEADER = 1361
    """ 以队长身份出发执行外勤委托 """
    END_FIELD_COMMISSION_AS_LEADER = 1362
    """ 以队长身份完成外勤委托归舰 """

    BE_INVITED_JOIN_GROUP_SEX = 1366
    """ 被邀请加入群交，开始前往群交地点 """

    APPOINNTED_AS_DIPLOMAT_LOCAL = 1371
    """ 被任命为本地外交官 """
    RELIEVED_OF_DIPLOMAT_LOCAL = 1372
    """ 被解除本地外交官的任命 """
    APPOINNTED_AS_DIPLOMAT_OUT = 1373
    """ 被任命为外派外交官 """
    RELIEVED_OF_DIPLOMAT_OUT = 1374
    """ 被解除外派外交官的任命 """

    CHOSEN_AS_ASSISTANT = 1401
    """ 被选为助理 """
    NOT_AS_ASSISTANT = 1402
    """ 不再为助理 """
    AI_FOLLOW_OFF = 1403
    """ 关闭智能跟随 """
    AI_FOLLOW_ON = 1404
    """ 开启智能跟随 """
    COME_TO_OFFICE = 1405
    """ 要求前往办公室 """
    SUPPORT_SERVICE_OFF = 1406
    """ 关闭辅佐服务 """
    SUPPORT_SERVICE_ON = 1407
    """ 开启辅佐服务 """
    SEND_FOOD_SERVICE_OFF = 1408
    """ 关闭送饭服务 """
    BUY_LUNGCH = 1409
    """ 开启帮忙买午饭服务 """
    MAKE_LUNGCH = 1410
    """ 开启亲手做午饭服务 """
    MAKE_THREE_MEALS = 1411
    """ 开启亲手做三餐服务 """
    MORNING_SERVICE_OFF = 1412
    """ 关闭早安服务 """
    MORNING_SALUTATION = 1413
    """ 开启早上叫起床服务 """
    MORNING_KISS = 1414
    """ 开启早安吻服务 """
    MORNING_BLOWJOB = 1415
    """ 开启早安咬服务 """
    NIGHT_SERVICE_OFF = 1416
    """ 关闭晚安服务 """
    NIGHT_SALUTATION = 1417
    """ 开启晚上催睡觉服务 """
    NIGHT_KISS = 1418
    """ 开启晚安吻服务 """
    NIGHT_BLOWJOB = 1419
    """ 开启晚安咬服务 """
    COHABITATION_OFF = 1420
    """ 关闭同居服务 """
    COHABITATION_ON = 1421
    """ 开启同居服务 """
    LOVE_SUPPORT_OFF = 1422
    """ 关闭助攻服务 """
    LOVE_SUPPORT_ON = 1423
    """ 开启助攻服务 """

    ASK_GIVE_PAN_EVERYDAY = 1451
    """ 被要求每天上交内裤 """
    ASK_GIVE_SOCKS_EVERYDAY = 1452
    """ 被要求每天上交袜子 """
    ASK_NOT_WEAR_CORSET = 1453
    """ 被要求以后不再穿胸衣 """
    ASK_NOT_WEAR_CLOTH_IN_SLEEP = 1454
    """ 被要求以后睡觉时不穿衣服裸睡 """
    GIVE_PAN_IN_DAY_FIRST_MEET = 1455
    """ 在每日招呼时上交今天的内裤 """
    GIVE_SOCKS_IN_DAY_FIRST_MEET = 1456
    """ 在每日招呼时上交今天的袜子 """
    ASK_WEAR_DIFFERENT_SOCKS_EVERYDAY = 1457
    """ 被要求每天穿不同的袜子 """
    ASK_EQUP_NIPPLE_CLAMP_IN_DAY = 1461
    """ 被要求白天时戴着乳头夹 """
    ASK_EQUP_CLIT_CLAMP_IN_DAY = 1462
    """ 被要求白天时戴着阴蒂夹 """
    ASK_EQUP_V_VIBRATOR_IN_DAY = 1463
    """ 被要求白天时V里插着振动棒 """
    ASK_EQUP_A_VIBRATOR_IN_DAY = 1464
    """ 被要求白天时A里插着振动棒 """
    ASK_EQUP_NIPPLE_CLAMP_IN_SLEEP = 1465
    """ 被要求睡觉时戴着乳头夹 """
    ASK_EQUP_CLIT_CLAMP_IN_SLEEP = 1466
    """ 被要求睡觉时戴着阴蒂夹 """
    ASK_EQUP_V_VIBRATOR_IN_SLEEP = 1467
    """ 被要求睡觉时V里插着振动棒 """
    ASK_EQUP_A_VIBRATOR_IN_SLEEP = 1468
    """ 被要求睡觉时A里插着振动棒 """
    ASK_NOT_WASH_SEMEN = 1471
    """ 被要求洗澡时不再清洗阴道内的精液 """
    ASK_MASTURBATION_BEFORE_SLEEP = 1472
    """ 被要求每天晚上睡前都要自慰 """
    ASK_NOT_MASTURBATION = 1473
    """ 被要求禁止自慰 """
    ASK_NOT_LOCK_DOOR_BEFORE_SLEEPING = 1474
    """ 被要求晚上睡觉不锁门 """
    ASK_SUCKING_AND_SWALLOWING_EXERCISES = 1481
    """ 被要求进行吮吸与吞咽力练习 """
    ASK_ARMPIT_CLAMPING_EXERCISES = 1482
    """ 被要求进行腋下夹持力练习 """
    ASK_BREAST_CLAMPING_EXERCISES = 1483
    """ 被要求进行胸部夹持力练习 """
    ASK_HANDS_FLEXIBILITY_EXERCISES = 1484
    """ 被要求进行手部灵活度练习 """
    ASK_FOOTS_FLEXIBILITY_EXERCISES = 1485
    """ 被要求进行足部灵活度练习 """
    ASK_VAGINA_FIRMNESS_EXERCISES = 1486
    """ 被要求进行阴道紧致度练习 """
    ASK_INTESTINE_FIRMNESS_EXERCISES = 1487
    """ 被要求进行肠道紧致度练习 """
    ASK_TAIL_FLEXIBILITY_EXERCISES = 1488
    """ 被要求进行尾巴灵活度练习 """
    ASK_TENTACLE_FLEXIBILITY_EXERCISES = 1489
    """ 被要求进行触手灵活度练习 """

    HAS_BEEN_PRIMARY_HYPNOSIS = 1501
    """ 获得被浅层催眠素质 """
    HAS_BEEN_DEEP_HYPNOSIS = 1502
    """ 获得被深层催眠素质 """
    HAS_BEEN_COMPLETE_HYPNOSIS = 1503
    """ 获得被完全催眠素质 """

