class Premise:
    """前提id"""

    DEBUG_MODE_ON = "debug_mode_on"
    """ 系统状态 现在是debug模式 """
    DEBUG_MODE_OFF = "debug_mode_off"
    """ 系统状态 现在不是debug模式 """
    IS_H = "is_h"
    """ 系统状态 当前为H模式 """
    NOT_H = "not_h"
    """ 系统状态 当前不是H模式 """
    # OPTION_FATER = "option_fater"
    # """ 系统状态 选项的父事件 """
    OPTION_SON = "option_son"
    """ 系统状态 选项的子事件 """

    IS_PLAYER = "sys_0"
    """ 指令_触发与交互 玩家触发的该指令 """
    NO_PLAYER = "sys_1"
    """ 指令_触发与交互 NPC触发的该指令 """
    HAVE_TARGET = "sys_2"
    """ 指令_触发与交互 拥有交互对象 """
    HAVE_NO_TARGET = "sys_3"
    """ 指令_触发与交互 没有交互对象 """
    TARGET_IS_PLAYER = "sys_4"
    """ 指令_触发与交互 交互对象是玩家角色 """
    TARGET_NO_PLAYER = "sys_5"
    """ 指令_触发与交互 交互对象不是玩家 """
    IS_MAN = "sex_0"
    """ 指令_触发与交互 触发该指令的是男性 """
    IS_WOMAN = "sex_1"
    """ 指令_触发与交互 触发该指令的是女性 """
    INSTRUCT_JUDGE_LOW_OBSCENITY = "instruct_judge_low_obscenity"
    """ 指令_触发与交互 当前实行值足以轻度性骚扰 """
    INSTRUCT_JUDGE_HIGH_OBSCENITY = "instruct_judge_high_obscenity"
    """ 指令_触发与交互 当前实行值足以重度性骚扰 """
    INSTRUCT_JUDGE_H = "instruct_judge_h"
    """ 指令_触发与交互 当前实行值足以H """

    HIGH_1 = "high_1"
    """ 指令_权重 优先度为1的空白前提 """
    HIGH_2 = "high_2"
    """ 指令_权重 优先度为2的空白前提 """
    HIGH_5 = "high_5"
    """ 指令_权重 优先度为5的空白前提 """
    HIGH_10 = "high_10"
    """ 指令_权重 优先度为10的空白前提 """
    HIGH_999 = "high_999"
    """ 指令_权重 优先度为999的空白前提 """

    LAST_CMD_MAKING_OUT = "last_cmd_makeing_out"
    """ 指令_前指令 前一指令为身体爱抚_口上触发用 """
    LAST_CMD_KISS_H = "last_cmd_kiss_h"
    """ 指令_前指令 前一指令为接吻（H）_口上触发用 """
    LAST_CMD_BREAST_CARESS = "last_cmd_breast_caress"
    """ 指令_前指令 前一指令为胸爱抚_口上触发用 """
    LAST_CMD_TWIDDLE_NIPPLES = "last_cmd_twiddle_nipples"
    """ 指令_前指令 前一指令为玩弄乳头_口上触发用 """
    LAST_CMD_BREAST_SUCKING = "last_cmd_breast_sucking"
    """ 指令_前指令 前一指令为舔吸乳头_口上触发用 """
    LAST_CMD_CLIT_CARESS = "last_cmd_clit_caress"
    """ 指令_前指令 前一指令为阴蒂爱抚_口上触发用 """
    LAST_CMD_OPEN_LABIA = "last_cmd_open_labia"
    """ 指令_前指令 前一指令为掰开阴唇观察_口上触发用 """
    LAST_CMD_CUNNILINGUS = "last_cmd_cunnilingus"
    """ 指令_前指令 前一指令为舔阴_口上触发用 """
    LAST_CMD_FINGER_INSERTION = "last_cmd_finger_insertion"
    """ 指令_前指令 前一指令为手指插入(V)_口上触发用 """
    LAST_CMD_ANAL_CARESS = "last_cmd_anal_caress"
    """ 指令_前指令 前一指令为手指插入(A)_口上触发用 """
    LAST_CMD_MAKE_MASTUREBATE = "last_cmd_make_masturebate"
    """ 指令_前指令 前一指令为让对方自慰（H）_口上触发用 """
    LAST_CMD_HANDJOB = "last_cmd_handjob"
    """ 指令_前指令 前一指令为手交_口上触发用 """
    LAST_CMD_BLOWJOB = "last_cmd_blowjob"
    """ 指令_前指令 前一指令为口交_口上触发用 """
    LAST_CMD_PAIZURI = "last_cmd_paizuri"
    """ 指令_前指令 前一指令为乳交_口上触发用 """
    LAST_CMD_FOOTJOB = "last_cmd_footjob"
    """ 指令_前指令 前一指令为足交_口上触发用 """
    LAST_CMD_HAIRJOB = "last_cmd_hairjob"
    """ 指令_前指令 前一指令为发交_口上触发用 """
    LAST_CMD_AXILLAJOB = "last_cmd_axillajob"
    """ 指令_前指令 前一指令为腋交_口上触发用 """
    LAST_CMD_RUB_BUTTOCK = "last_cmd_rub_buttock"
    """ 指令_前指令 前一指令为素股_口上触发用 """
    LAST_CMD_LEGJOB = "last_cmd_legjob"
    """ 指令_前指令 前一指令为腿交_口上触发用 """
    LAST_CMD_TAILJOB = "last_cmd_tailjob"
    """ 指令_前指令 前一指令为尾交_口上触发用 """
    LAST_CMD_FACE_RUB = "last_cmd_face_rub"
    """ 指令_前指令 前一指令为阴茎蹭脸_口上触发用 """
    LAST_CMD_HORN_RUB = "last_cmd_horn_rub"
    """ 指令_前指令 前一指令为阴茎蹭角_口上触发用 """
    LAST_CMD_EARS_RUB = "last_cmd_ears_rub"
    """ 指令_前指令 前一指令为阴茎蹭耳朵_口上触发用 """
    LAST_CMD_HAND_BLOWJOB = "last_cmd_hand_blowjob"
    """ 指令_前指令 前一指令为手交口交_口上触发用 """
    LAST_CMD_TITS_BLOWJOB = "last_cmd_tits_blowjob"
    """ 指令_前指令 前一指令为乳交口交_口上触发用 """
    LAST_CMD_DEEP_THROAT = "last_cmd_deep_throat"
    """ 指令_前指令 前一指令为深喉插入_口上触发用 """
    LAST_CMD_FOCUS_BLOWJOB = "last_cmd_focus_blowjob"
    """ 指令_前指令 前一指令为真空口交_口上触发用 """
    LAST_CMD_NORMAL_SEX = "last_cmd_normal_sex"
    """ 指令_前指令 前一指令为正常位_口上触发用 """
    LAST_CMD_BACK_SEX = "last_cmd_back_sex"
    """ 指令_前指令 前一指令为背后位_口上触发用 """
    LAST_CMD_RIDING_SEX = "last_cmd_riding_sex"
    """ 指令_前指令 前一指令为骑乘位_口上触发用 """
    LAST_CMD_FACE_SEAT_SEX = "last_cmd_face_seat_sex"
    """ 指令_前指令 前一指令为对面座位_口上触发用 """
    LAST_CMD_BACK_SEAT_SEX = "last_cmd_back_seat_sex"
    """ 指令_前指令 前一指令为背面座位_口上触发用 """
    LAST_CMD_FACE_STAND_SEX = "last_cmd_face_stand_sex"
    """ 指令_前指令 前一指令为对面立位_口上触发用 """
    LAST_CMD_BACK_STAND_SEX = "last_cmd_back_stand_sex"
    """ 指令_前指令 前一指令为背面立位_口上触发用 """
    LAST_CMD_STIMULATE_G_POINT = "last_cmd_stimulate_g_point"
    """ 指令_前指令 前一指令为刺激G点_口上触发用 """
    LAST_CMD_WOMB_OS_CARESS = "last_cmd_womb_os_caress"
    """ 指令_前指令 前一指令为玩弄子宫口_口上触发用 """

    LAST_CMD_PENIS_POSITION = "last_cmd_penis_position"
    """ 指令_前指令 前一指令为阴茎位置相关指令_指令触发用 """
    LAST_CMD_BLOWJOB_OR_HANDJOB = "last_cmd_blowjob_or_handjob"
    """ 指令_前指令 前一指令为口交或手交_指令触发用 """
    LAST_CMD_BLOWJOB_OR_PAIZURI = "last_cmd_blowjob_or_paizuri"
    """ 指令_前指令 前一指令为口交或乳交_指令触发用 """
    LAST_CMD_BLOWJOB_OR_CUNNILINGUS = "last_cmd_blowjob_or_cunnilingus"
    """ 指令_前指令 前一指令为口交或舔阴_指令触发用 """
    LAST_CMD_SEX = "last_cmd_sex"
    """ 指令_前指令 前一指令为V性交_指令触发用 """
    LAST_CMD_W_SEX = "last_cmd_w_sex"
    """ 指令_前指令 前一指令为W性交_指令触发用 """
    LAST_CMD_A_SEX = "last_cmd_a_sex"
    """ 指令_前指令 前一指令为A性交_指令触发用 """
    LAST_CMD_U_SEX = "last_cmd_u_sex"
    """ 指令_前指令 前一指令为U性交_指令触发用 """
    LAST_CMD_BREAST_CARESS_TYPE = "last_cmd_breast_caress_type"
    """ 指令_前指令 前一指令为胸部爱抚类(403，404，405) """
    LAST_CMD_HANDJOB_TYPE = "last_cmd_handjob_type"
    """ 指令_前指令 前一指令为手交类(420，427) """
    LAST_CMD_BLOWJOB_TYPE = "last_cmd_blowjob_type"
    """ 指令_前指令 前一指令为口交类(421，427，428，429，430，431) """
    LAST_CMD_PAIZURI_TYPE = "last_cmd_paizuri_type"
    """ 指令_前指令 前一指令为乳交类(422，428) """

    IN_PLAYER_SCENE = "place_0"
    """ 地点_角色 与玩家处于相同地点 """
    NOT_IN_PLAYER_SCENE = "place_1"
    """ 地点_角色 与玩家不处于相同地点 """
    # IN_PLAYER_ZONE = "place_1"
    """ 地点_角色 与玩家处于相同大区域 """
    PLAYER_COME_SCENE = "place_2"
    """ 地点_角色 玩家来到该角色所在的地点 """
    # PLAYER_COME_ZONE = "place_3"
    """ 地点_角色 玩家来到该角色所在的区域 """
    PLAYER_LEAVE_SCENE = "place_4"
    """ 地点_角色 玩家离开该角色所在的地点 """
    # PLAYER_LEAVE_ZONE = "place_5"
    """ 地点_角色 玩家离开该角色所在的区域 """
    TATGET_COME_SCENE = "place_6"
    """ 地点_角色 该角色来到玩家所在的地点 """
    # TATGET_COME_ZONE = "place_7"
    """ 地点_角色 该角色来到玩家所在的区域 """
    TATGET_LEAVE_SCENE = "place_8"
    """ 地点_角色 该角色离开玩家所在的地点 """
    # TATGET_LEAVE_ZONE = "place_9"
    """ 地点_角色 该角色离开玩家所在的区域 """
    SCENE_ONLY_TWO = "place_10"
    """ 地点_角色 该地点仅有玩家和该角色 """
    SCENE_OVER_TWO = "place_11"
    """ 地点_角色 该地点里有除了玩家和该角色之外的人 """
    SCENE_ONLY_ONE = "place_12"
    """ 地点_角色 该地点里没有自己外的其他角色 """
    SCENE_SOMEONE_IS_H = "place_is_h"
    """ 地点_角色 该地点有其他角色在和玩家H """
    SCENE_SOMEONE_NO_FALL = "place_someone_no_fall"
    """ 地点_角色 该地点有未拥有陷落素质的角色 """
    SCENE_OVER_ONE = "place_over_one"
    """ 地点_角色 该地点里有除了自己之外的人 """

    PLACE_EXPOSED = "place_exposed"
    """ 地点_属性 当前地点暴露 """
    PLACE_COVERT = "place_covert"
    """ 地点_属性 当前地点隐蔽 """
    PLACE_HAVE_FURNITURE = "place_have_furniture"
    """ 地点_属性 当前地点有家具 """
    PLACE_NOT_FURNITURE = "place_not_furniture"
    """ 地点_属性 当前地点没家具 """
    IN_FUNCTIONAL_ROOM = "in_functional_room"
    """ 地点_属性 在功能性地点中 """
    PLACE_DOOR_OPEN = "place_door_open"
    """ 地点_属性 地点的门是开着的（不含内隔间关门） """
    PLACE_LADIES_ONLY = "place_ladies_only"
    """ 地点_属性 该地点男士止步（女洗手间/更衣室/浴室等） """

    IN_KITCHEN = "in_kit"
    """ 地点_定位 在厨房 """
    IN_DINING_HALL = "in_din"
    """ 地点_定位 在食堂 """
    NOT_IN_DINING_HALL = "not_in_din"
    """ 地点_定位 不在食堂 """
    IN_FOOD_SHOP = "in_food_shop"
    """ 地点_定位 在食物商店（取餐区） """
    NOT_IN_FOOD_SHOP = "not_in_food_shop"
    """ 地点_定位 不在食物商店（取餐区） """
    IN_DR_OFFICE = "in_dr_off"
    """ 地点_定位 在博士办公室 """
    NOT_IN_DR_OFFICE = "not_in_dr_off"
    """ 地点_定位 不在博士办公室 """
    IN_DR_OFFICE_OR_DEBUG = "in_dr_off_or_debug"
    """ 地点_定位 在博士办公室或处于debug模式 """
    IN_COMMAND_ROOM = "in_command_room"
    """ 地点_定位 在指挥室 """
    IN_DORMITORY = "in_dor"
    """ 地点_定位 在自己宿舍中 """
    NOT_IN_DORMITORY = "not_in_dor"
    """ 地点_定位 不在自己宿舍中 """
    IN_BATHROOM = "in_bathroom"
    """ 地点_定位 在浴室中 """
    IN_TOILET_MAN = "in_toilet_man"
    """ 地点_定位 在男士洗手间 """
    IN_TOILET_FEMALE = "in_toilet_female"
    """ 地点_定位 在女士洗手间 """
    NOT_IN_TOILET = "not_in_toilet"
    """ 地点_定位 不在洗手间 """
    IN_REST_ROOM = "in_restroom"
    """ 地点_定位 在休息室中 """
    NOT_IN_REST_ROOM = "not_in_restroom"
    """ 地点_定位 不在休息室中 """
    IN_MUSIC_ROOM = "in_music_room"
    """ 地点_定位 在音乐室中 """
    IN_COLLECTION_ROOM = "in_collection_room"
    """ 地点_定位 在藏品馆中 """
    IN_GYM_ROOM = "in_gym_room"
    """ 地点_定位 在健身区中 """
    IN_TRAINING_ROOM = "in_training_room"
    """ 地点_定位 在训练室中（包括木桩房和射击房） """
    NOT_IN_TRAINING_ROOM = "not_in_training_room"
    """ 地点_定位 不在训练室中（包括木桩房和射击房） """
    IN_FIGHT_ROOM = "in_fight_room"
    """ 地点_定位 在木桩房中 """
    IN_SHOOT_ROOM = "in_shoot_room"
    """ 地点_定位 在射击房中 """
    IN_BUILDING_ROOM = "in_building_room"
    """ 地点_定位 在基建部中 """
    IN_CLINIC = "in_clinic"
    """ 地点_定位 在门诊室中（含急诊室） """
    NOT_IN_CLINIC = "not_in_clinic"
    """ 地点_定位 不在门诊室中（含急诊室） """
    IN_BATHROOM = "in_bathroom"
    """ 地点_定位 在淋浴区 """
    NOT_IN_BATHROOM = "not_in_bathroom"
    """ 地点_定位 不在淋浴区 """
    IN_BATHZONE_LOCKER_ROOM = "in_bathzone_locker_room"
    """ 地点_定位 在大浴场的更衣室 """
    NOT_IN_BATHZONE_LOCKER_ROOM = "not_in_bathzone_locker_room"
    """ 地点_定位 不在大浴场的更衣室 """
    IN_LOCKER_ROOM_OR_DORMITORY = "in_locker_room_or_dormitory"
    """ 地点_定位 在更衣室或宿舍 """

    MOVE_TO_TOILET_FEMALE = "move_to_toilet_female"
    """ 地点_移动 角色抵达女士洗手间 """
    MOVE_TO_LOCKER_ROOM = "move_to_locker_room"
    """ 地点_移动 角色抵达更衣室 """
    MOVE_TO_DORMITORY = "move_to_dormitory"
    """ 地点_移动 角色抵达宿舍 """
    MOVE_FROM_DORMITORY = "move_from_dormitory"
    """ 地点_移动 角色离开宿舍 """
    MOVE_TO_LADIES_ONLY = "move_to_ladies_only"
    """ 地点_移动 角色抵达男士止步的地点 """

    HAVE_MOVED = "ai_moved"
    """ 时间_角色 NPC距离上次移动已经至少经过了1小时 """
    AI_WAIT = "ai_wait"
    """ 时间_角色 NPC需要进行一次5分钟的等待（wait_flag=1） """
    HAVE_TRAINED = "ai_trained"
    """ 时间_角色 NPC距离上次战斗训练已经超过两天了 """
    NOT_SHOWER = "ai_not_shower"
    """ 时间_角色 NPC今天还没有洗澡 """
    HAVE_SHOWERED = "ai_have_showered"
    """ 时间_角色 NPC今天已经洗过澡了 """

    TIME_DAY = "time_day"
    """ 时间_当前 时间:白天（6点~18点） """
    TIME_NIGHT = "time_night"
    """ 时间_当前 时间:夜晚（18点~6点） """
    TIME_MIDNIGHT = "time_midnight"
    """ 时间_当前 时间:深夜（22点~2点） """
    TIME_MORNING = "time_morning"
    """ 时间_当前 时间:清晨（4点~8点） """
    TIME_MOON = "time_moon"
    """ 时间_当前 时间:中午（10点~14点） """
    EAT_TIME = "eat_time"
    """ 时间_当前 饭点（早上7~8点、中午12~13点、晚上17~18点） """
    SHOWER_TIME = "shower_time"
    """ 时间_当前 淋浴时间（晚上8点到晚上12点） """
    SLEEP_TIME = "sleep_time"
    """ 时间_当前 睡觉时间（晚上10点到早上6点） """
    SLEEP_GE_75_OR_SLEEP_TIME = "sleep_ge_75_or_sleep_time"
    """ 时间_当前 困倦条≥75%或到了睡觉的时间 """
    WORK_TIME = "work_time"
    """ 时间_当前 工作时间（早上9:00~下午4:59） """

    IS_ASSISTANT = "is_assistant"
    """ 属性_助理与跟随 自己是当前的助理干员 """
    NOT_ASSISTANT = "not_assistant"
    """ 属性_助理与跟随 自己不是当前的助理干员 """
    TARGET_IS_ASSISTANT = "t_is_assistant"
    """ 属性_助理与跟随 交互对象是当前的助理干员 """
    TARGET_NOT_ASSISTANT = "t_not_assistant"
    """ 属性_助理与跟随 交互对象不是当前的助理干员 """
    IS_FOLLOW = "is_follow"
    """ 属性_助理与跟随 当前正跟随玩家 """
    NOT_FOLLOW = "not_follow"
    """ 属性_助理与跟随 当前没跟随玩家 """
    IS_FOLLOW_1 = "is_follow_1"
    """ 属性_助理与跟随 当前正智能跟随玩家 """
    NOT_FOLLOW_1 = "not_follow_1"
    """ 属性_助理与跟随 当前没智能跟随玩家 """
    IS_FOLLOW_3 = "is_follow_3"
    """ 属性_助理与跟随 当前正前往博士办公室 """
    TARGET_IS_FOLLOW = "t_is_follow"
    """ 属性_助理与跟随 交互对象当前正跟随玩家 """
    TARGET_NOT_FOLLOW = "t_not_follow"
    """ 属性_助理与跟随 交互对象当前没跟随玩家 """

    HP_1 = "hp_1"
    """ 属性_基础 自身疲劳（体力=1） """
    HP_LOW = "hp_low"
    """ 属性_基础 自身体力低于30% """
    HP_HIGH = "hp_high"
    """ 属性_基础 自身体力高于70% """
    MP_0 = "mp_0"
    """ 属性_基础 自身气力为0 """
    MP_LOW = "mp_low"
    """ 属性_基础 自身气力低于30% """
    MP_HIGH = "mp_high"
    """ 属性_基础 自身气力高于70% """
    TARGET_HP_LOW = "t_hp_low"
    """ 属性_基础 交互对象体力低于30% """
    TARGET_HP_HIGH = "t_hp_high"
    """ 属性_基础 交互对象体力高于70% """
    TARGET_MP_0 = "t_mp_0"
    """ 属性_基础 交互对象气力为0 """
    TARGET_MP_LOW = "t_mp_low"
    """ 属性_基础 交互对象气力低于30% """
    TARGET_MP_HIGH = "t_mp_high"
    """ 属性_基础 交互对象气力高于70% """
    SLEEP_GE_50 = "sleep_ge_50"
    """ 属性_基础 困倦条≥50% """
    SLEEP_LE_74 = "sleep_le_74"
    """ 属性_基础 困倦条≤74%，全指令自由 """
    SLEEP_GE_75 = "sleep_ge_75"
    """ 属性_基础 困倦条≥75%，部分指令受限 """
    SLEEP_LE_89 = "sleep_le_89"
    """ 属性_基础 困倦条≤89%，自由活动的极限 """
    SLEEP_GE_90 = "sleep_ge_90"
    """ 属性_基础 困倦条≥90%，必须回去睡觉 """
    SLEEP_100 = "sleep_100"
    """ 属性_基础 困倦条100%，当场爆睡 """
    URINATE_LE_79 = "urinate_le_79"
    """ 属性_基础 尿意条≤79%，不需要排尿 """
    URINATE_GE_80 = "urinate_ge_80"
    """ 属性_基础 尿意条≥80%，需要排尿 """
    TARGET_URINATE_LE_79 = "t_urinate_le_79"
    """ 属性_基础 交互对象尿意条≤79%，不需要排尿 """
    TARGET_URINATE_GE_80 = "t_urinate_ge_80"
    """ 属性_基础 交互对象尿意条≥80%，需要排尿 """
    HUNGER_LE_79 = "hunger_le_79"
    """ 属性_基础 饥饿值≤79%，不需要吃饭 """
    HUNGER_GE_80 = "hunger_ge_80"
    """ 属性_基础 饥饿值≥80%，需要吃饭 """
    TARGET_HUNGER_LE_79 = "t_hunger_le_79"
    """ 属性_基础 交互对象饥饿值≤79%，不需要吃饭 """
    TARGET_HUNGER_GE_80 = "t_hunger_ge_80"
    """ 属性_基础 交互对象饥饿值≥80%，需要吃饭 """

    TARGET_GOOD_MOOD = "good_mood"
    """ 属性_心情 交互对象心情愉快 """
    TARGET_NORMAL_MOOD = "normal_mood"
    """ 属性_心情 交互对象心情普通 """
    TARGET_BAD_MOOD = "bad_mood"
    """ 属性_心情 交互对象心情不好 """
    TARGET_ANGRY_MOOD = "angry_mood"
    """ 属性_心情 交互对象心情愤怒 """
    TARGET_ABD_OR_ANGRY_MOOD = "bad_or_angry_mood"
    """ 属性_心情 交互对象心情不好或愤怒 """
    TARGET_ANGRY_WITH_PLAYER = "angry_with_player"
    """ 属性_心情 交互对象被玩家惹火了 """
    TARGET_NOT_ANGRY_WITH_PLAYER = "not_angry_with_player"
    """ 属性_心情 交互对象没有被玩家惹火 """

    T_LUBRICATION_L_1 = "t_lubrication_l_1"
    """ 属性_状态 交互对象润滑<1 """
    T_LUBRICATION_L_3 = "t_lubrication_l_3"
    """ 属性_状态 交互对象润滑<3 """
    T_LUBRICATION_L_7 = "t_lubrication_l_7"
    """ 属性_状态 交互对象润滑<7 """
    T_LUBRICATION_GE_1 = "t_lubrication_ge_1"
    """ 属性_状态 交互对象润滑>=1 """
    T_LUBRICATION_GE_3 = "t_lubrication_ge_3"
    """ 属性_状态 交互对象润滑>=3 """
    T_LUBRICATION_GE_5 = "t_lubrication_ge_5"
    """ 属性_状态 交互对象润滑>=5 """
    T_LUBRICATION_GE_7 = "t_lubrication_ge_7"
    """ 属性_状态 交互对象润滑>=7 """

    T_NFEEL_GE_1 = "t_nfeel_ge_1"
    """ 属性_能力 交互对象Ｎ感觉>=1 """
    T_NFEEL_GE_3 = "t_nfeel_ge_3"
    """ 属性_能力 交互对象Ｎ感觉>=3 """
    T_NFEEL_GE_5 = "t_nfeel_ge_5"
    """ 属性_能力 交互对象Ｎ感觉>=5 """
    T_NFEEL_GE_7 = "t_nfeel_ge_7"
    """ 属性_能力 交互对象Ｎ感觉>=7 """
    T_NFEEL_L_1 = "t_nfeel_l_1"
    """ 属性_能力 交互对象Ｎ感觉<1 """
    T_NFEEL_L_3 = "t_nfeel_l_3"
    """ 属性_能力 交互对象Ｎ感觉<3 """
    T_NFEEL_L_5 = "t_nfeel_l_5"
    """ 属性_能力 交互对象Ｎ感觉<5 """
    T_BFEEL_GE_1 = "t_bfeel_ge_1"
    """ 属性_能力 交互对象Ｂ感觉>=1 """
    T_BFEEL_GE_3 = "t_bfeel_ge_3"
    """ 属性_能力 交互对象Ｂ感觉>=3 """
    T_BFEEL_GE_5 = "t_bfeel_ge_5"
    """ 属性_能力 交互对象Ｂ感觉>=5 """
    T_BFEEL_GE_7 = "t_bfeel_ge_7"
    """ 属性_能力 交互对象Ｂ感觉>=7 """
    T_BFEEL_L_1 = "t_bfeel_l_1"
    """ 属性_能力 交互对象Ｂ感觉<1 """
    T_BFEEL_L_3 = "t_bfeel_l_3"
    """ 属性_能力 交互对象Ｂ感觉<3 """
    T_BFEEL_L_5 = "t_bfeel_l_5"
    """ 属性_能力 交互对象Ｂ感觉<5 """
    T_CFEEL_GE_1 = "t_cfeel_ge_1"
    """ 属性_能力 交互对象Ｃ感觉>=1 """
    T_CFEEL_GE_3 = "t_cfeel_ge_3"
    """ 属性_能力 交互对象Ｃ感觉>=3 """
    T_CFEEL_GE_5 = "t_cfeel_ge_5"
    """ 属性_能力 交互对象Ｃ感觉>=5 """
    T_CFEEL_GE_7 = "t_cfeel_ge_7"
    """ 属性_能力 交互对象Ｃ感觉>=7 """
    T_CFEEL_L_1 = "t_cfeel_l_1"
    """ 属性_能力 交互对象Ｃ感觉<1 """
    T_CFEEL_L_3 = "t_cfeel_l_3"
    """ 属性_能力 交互对象Ｃ感觉<3 """
    T_CFEEL_L_5 = "t_cfeel_l_5"
    """ 属性_能力 交互对象Ｃ感觉<5 """
    PFEEL_GE_1 = "pfeel_ge_1"
    """ 属性_能力 Ｐ感觉>=1 """
    PFEEL_GE_3 = "pfeel_ge_3"
    """ 属性_能力 Ｐ感觉>=3 """
    PFEEL_GE_5 = "pfeel_ge_5"
    """ 属性_能力 Ｐ感觉>=5 """
    PFEEL_GE_7 = "pfeel_ge_7"
    """ 属性_能力 Ｐ感觉>=7 """
    PFEEL_L_1 = "pfeel_l_1"
    """ 属性_能力 Ｐ感觉<1 """
    PFEEL_L_3 = "pfeel_l_3"
    """ 属性_能力 Ｐ感觉<3 """
    PFEEL_L_5 = "pfeel_l_5"
    """ 属性_能力 Ｐ感觉<5 """
    T_VFEEL_GE_1 = "t_vfeel_ge_1"
    """ 属性_能力 交互对象Ｖ感觉>=1 """
    T_VFEEL_GE_3 = "t_vfeel_ge_3"
    """ 属性_能力 交互对象Ｖ感觉>=3 """
    T_VFEEL_GE_5 = "t_vfeel_ge_5"
    """ 属性_能力 交互对象Ｖ感觉>=5 """
    T_VFEEL_GE_7 = "t_vfeel_ge_7"
    """ 属性_能力 交互对象Ｖ感觉>=7 """
    T_VFEEL_L_1 = "t_vfeel_l_1"
    """ 属性_能力 交互对象Ｖ感觉<1 """
    T_VFEEL_L_3 = "t_vfeel_l_3"
    """ 属性_能力 交互对象Ｖ感觉<3 """
    T_VFEEL_L_5 = "t_vfeel_l_5"
    """ 属性_能力 交互对象Ｖ感觉<5 """
    T_AFEEL_GE_1 = "t_afeel_ge_1"
    """ 属性_能力 交互对象Ａ感觉>=1 """
    T_AFEEL_GE_3 = "t_afeel_ge_3"
    """ 属性_能力 交互对象Ａ感觉>=3 """
    T_AFEEL_GE_5 = "t_afeel_ge_5"
    """ 属性_能力 交互对象Ａ感觉>=5 """
    T_AFEEL_GE_7 = "t_afeel_ge_7"
    """ 属性_能力 交互对象Ａ感觉>=7 """
    T_AFEEL_L_1 = "t_afeel_l_1"
    """ 属性_能力 交互对象Ａ感觉<1 """
    T_AFEEL_L_3 = "t_afeel_l_3"
    """ 属性_能力 交互对象Ａ感觉<3 """
    T_AFEEL_L_5 = "t_afeel_l_5"
    """ 属性_能力 交互对象Ａ感觉<5 """
    T_UFEEL_GE_1 = "t_ufeel_ge_1"
    """ 属性_能力 交互对象Ｕ感觉>=1 """
    T_UFEEL_GE_3 = "t_ufeel_ge_3"
    """ 属性_能力 交互对象Ｕ感觉>=3 """
    T_UFEEL_GE_5 = "t_ufeel_ge_5"
    """ 属性_能力 交互对象Ｕ感觉>=5 """
    T_UFEEL_GE_7 = "t_ufeel_ge_7"
    """ 属性_能力 交互对象Ｕ感觉>=7 """
    T_UFEEL_L_1 = "t_ufeel_l_1"
    """ 属性_能力 交互对象Ｕ感觉<1 """
    T_UFEEL_L_3 = "t_ufeel_l_3"
    """ 属性_能力 交互对象Ｕ感觉<3 """
    T_UFEEL_L_5 = "t_ufeel_l_5"
    """ 属性_能力 交互对象Ｕ感觉<5 """
    T_WFEEL_GE_1 = "t_wfeel_ge_1"
    """ 属性_能力 交互对象Ｗ感觉>=1 """
    T_WFEEL_GE_3 = "t_wfeel_ge_3"
    """ 属性_能力 交互对象Ｗ感觉>=3 """
    T_WFEEL_GE_5 = "t_wfeel_ge_5"
    """ 属性_能力 交互对象Ｗ感觉>=5 """
    T_WFEEL_GE_7 = "t_wfeel_ge_7"
    """ 属性_能力 交互对象Ｗ感觉>=7 """
    T_WFEEL_L_1 = "t_wfeel_l_1"
    """ 属性_能力 交互对象Ｗ感觉<1 """
    T_WFEEL_L_3 = "t_wfeel_l_3"
    """ 属性_能力 交互对象Ｗ感觉<3 """
    T_WFEEL_L_5 = "t_wfeel_l_5"
    """ 属性_能力 交互对象Ｗ感觉<5 """
    TECHNIQUE_GE_3 = "technique_ge_3"
    """ 属性_能力 自身技巧技能>=3 """
    TECHNIQUE_GE_5 = "technique_ge_5"
    """ 属性_能力 自身技巧技能>=5 """
    TARGET_TECHNIQUE_GE_3 = "t_technique_ge_3"
    """ 属性_能力 交互对象技巧技能>=3 """
    TARGET_TECHNIQUE_GE_5 = "t_technique_ge_5"
    """ 属性_能力 交互对象技巧技能>=5 """
    T_SUBMIT_GE_1 = "t_submit_ge_1"
    """ 属性_能力 交互对象顺从>=1 """
    T_SUBMIT_GE_3 = "t_submit_ge_3"
    """ 属性_能力 交互对象顺从>=3 """
    T_SUBMIT_GE_5 = "t_submit_ge_5"
    """ 属性_能力 交互对象顺从>=5 """
    T_SUBMIT_GE_7 = "t_submit_ge_7"
    """ 属性_能力 交互对象顺从>=7 """
    T_SUBMIT_L_1 = "t_submit_l_1"
    """ 属性_能力 交互对象顺从<1 """
    T_SUBMIT_L_3 = "t_submit_l_3"
    """ 属性_能力 交互对象顺从<3 """
    T_SUBMIT_L_5 = "t_submit_l_5"
    """ 属性_能力 交互对象顺从<5 """
    TARGET_INTIMACY_8 = "t_intimacy_8"
    """ 属性_能力 交互对象亲密==8 """
    TARGET_INTIMACY_LE_1 = "t_intimacy_le_1"
    """ 属性_能力 交互对象亲密<=1 """
    TARGET_INTIMACY_GE_3 = "t_intimacy_ge_3"
    """ 属性_能力 交互对象亲密>=3 """
    TARGET_INTIMACY_GE_5 = "t_intimacy_ge_5"
    """ 属性_能力 交互对象亲密>=5 """
    TARGET_DESIRE_GE_5 = "t_desire_ge_5"
    """ 属性_能力 交互对象欲望>=5 """
    TARGET_DESIRE_GE_7 = "t_desire_ge_7"
    """ 属性_能力 交互对象欲望>=7 """
    T_EXHIBIT_GE_1 = "t_exhibit_ge_1"
    """ 属性_能力 交互对象露出>=1 """
    T_EXHIBIT_GE_3 = "t_exhibit_ge_3"
    """ 属性_能力 交互对象露出>=3 """
    T_EXHIBIT_GE_5 = "t_exhibit_ge_5"
    """ 属性_能力 交互对象露出>=5 """
    T_EXHIBIT_GE_7 = "t_exhibit_ge_7"
    """ 属性_能力 交互对象露出>=7 """
    T_EXHIBIT_L_1 = "t_exhibit_l_1"
    """ 属性_能力 交互对象露出<1 """
    T_EXHIBIT_L_3 = "t_exhibit_l_3"
    """ 属性_能力 交互对象露出<3 """
    T_EXHIBIT_L_5 = "t_exhibit_l_5"
    """ 属性_能力 交互对象露出<5 """
    S_GE_1 = "s_ge_1"
    """ 属性_能力 施虐>=1 """
    S_GE_3 = "s_ge_3"
    """ 属性_能力 施虐>=3 """
    S_GE_5 = "s_ge_5"
    """ 属性_能力 施虐>=5 """
    S_GE_7 = "s_ge_7"
    """ 属性_能力 施虐>=7 """
    S_L_1 = "s_l_1"
    """ 属性_能力 施虐<1 """
    S_L_3 = "s_l_3"
    """ 属性_能力 施虐<3 """
    S_L_5 = "s_l_5"
    """ 属性_能力 施虐<5 """
    T_S_GE_1 = "t_s_ge_1"
    """ 属性_能力 交互对象施虐>=1 """
    T_S_GE_3 = "t_s_ge_3"
    """ 属性_能力 交互对象施虐>=3 """
    T_S_GE_5 = "t_s_ge_5"
    """ 属性_能力 交互对象施虐>=5 """
    T_S_GE_7 = "t_s_ge_7"
    """ 属性_能力 交互对象施虐>=7 """
    T_S_L_1 = "t_s_l_1"
    """ 属性_能力 交互对象施虐<1 """
    T_S_L_3 = "t_s_l_3"
    """ 属性_能力 交互对象施虐<3 """
    T_S_L_5 = "t_s_l_5"
    """ 属性_能力 交互对象施虐<5 """
    M_GE_1 = "m_ge_1"
    """ 属性_能力 受虐>=1 """
    M_GE_3 = "m_ge_3"
    """ 属性_能力 受虐>=3 """
    M_GE_5 = "m_ge_5"
    """ 属性_能力 受虐>=5 """
    M_GE_7 = "m_ge_7"
    """ 属性_能力 受虐>=7 """
    M_L_1 = "m_l_1"
    """ 属性_能力 受虐<1 """
    M_L_3 = "m_l_3"
    """ 属性_能力 受虐<3 """
    M_L_5 = "m_l_5"
    """ 属性_能力 受虐<5 """
    T_M_GE_1 = "t_m_ge_1"
    """ 属性_能力 交互对象受虐>=1 """
    T_M_GE_3 = "t_m_ge_3"
    """ 属性_能力 交互对象受虐>=3 """
    T_M_GE_5 = "t_m_ge_5"
    """ 属性_能力 交互对象受虐>=5 """
    T_M_GE_7 = "t_m_ge_7"
    """ 属性_能力 交互对象受虐>=7 """
    T_M_L_1 = "t_m_l_1"
    """ 属性_能力 交互对象受虐<1 """
    T_M_L_3 = "t_m_l_3"
    """ 属性_能力 交互对象受虐<3 """
    T_M_L_5 = "t_m_l_5"
    """ 属性_能力 交互对象受虐<5 """
    T_HAPPY_MARK_1 = "t_happy_mark_1"
    """ 属性_能力 交互对象快乐刻印==1 """
    T_HAPPY_MARK_2 = "t_happy_mark_2"
    """ 属性_能力 交互对象快乐刻印==2 """
    T_HAPPY_MARK_3 = "t_happy_mark_3"
    """ 属性_能力 交互对象快乐刻印==3 """
    T_HAPPY_MARK_GE_1 = "t_happy_mark_ge_1"
    """ 属性_能力 交互对象快乐刻印>=1 """
    T_HAPPY_MARK_LE_2 = "t_happy_mark_le_2"
    """ 属性_能力 交互对象快乐刻印<=2 """
    T_YIELD_MARK_1 = "t_yield_mark_1"
    """ 属性_能力 交互对象屈服刻印==1 """
    T_YIELD_MARK_2 = "t_yield_mark_2"
    """ 属性_能力 交互对象屈服刻印==2 """
    T_YIELD_MARK_3 = "t_yield_mark_3"
    """ 属性_能力 交互对象屈服刻印==3 """
    T_YIELD_MARK_GE_1 = "t_yield_mark_ge_1"
    """ 属性_能力 交互对象屈服刻印>=1 """
    T_YIELD_MARK_LE_2 = "t_yield_mark_le_2"
    """ 属性_能力 交互对象屈服刻印<=2 """
    TALK_LE_1 = "talk_le_1"
    """ 属性_能力 话术技能<=1 """
    TALK_GE_3 = "talk_ge_3"
    """ 属性_能力 话术技能>=3 """
    TALK_GE_5 = "talk_ge_5"
    """ 属性_能力 话术技能>=5 """
    T_TALK_LE_1 = "t_talk_le_1"
    """ 属性_能力 交互对象话术技能<=1 """
    T_TALK_GE_3 = "t_talk_ge_3"
    """ 属性_能力 交互对象话术技能>=3 """
    T_TALK_GE_5 = "t_talk_ge_5"
    """ 属性_能力 交互对象话术技能>=5 """
    COOK_1 = "cook_1"
    """ 属性_能力 自身料理技能==1 """
    COOK_2 = "cook_2"
    """ 属性_能力 自身料理技能==2 """
    COOK_3 = "cook_3"
    """ 属性_能力 自身料理技能==3 """
    COOK_4 = "cook_4"
    """ 属性_能力 自身料理技能==4 """
    COOK_LE_1 = "cook_le_1"
    """ 属性_能力 自身料理技能<=1 """
    COOK_GE_3 = "cook_ge_3"
    """ 属性_能力 自身料理技能>=3 """
    COOK_GE_5 = "cook_ge_5"
    """ 属性_能力 自身料理技能>=5 """
    TARGET_COOK_1 = "t_cook_1"
    """ 属性_能力 交互对象料理技能==1 """
    TARGET_COOK_2 = "t_cook_2"
    """ 属性_能力 交互对象料理技能==2 """
    TARGET_COOK_3 = "t_cook_3"
    """ 属性_能力 交互对象料理技能==3 """
    TARGET_COOK_4 = "t_cook_4"
    """ 属性_能力 交互对象料理技能==4 """
    TARGET_COOK_LE_1 = "t_cook_le_1"
    """ 属性_能力 交互对象料理技能<=1 """
    TARGET_COOK_LE_3 = "t_cook_le_3"
    """ 属性_能力 交互对象料理技能<=3 """
    TARGET_COOK_GE_3 = "t_cook_ge_3"
    """ 属性_能力 交互对象料理技能>=3 """
    TARGET_COOK_G_3 = "t_cook_g_3"
    """ 属性_能力 交互对象料理技能>3 """
    TARGET_COOK_GE_5 = "t_cook_ge_5"
    """ 属性_能力 交互对象料理技能>=5 """
    MUSIC_1 = "music_1"
    """ 属性_能力 自身音乐技能==1 """
    MUSIC_2 = "music_2"
    """ 属性_能力 自身音乐技能==2 """
    MUSIC_3 = "music_3"
    """ 属性_能力 自身音乐技能==3 """
    MUSIC_4 = "music_4"
    """ 属性_能力 自身音乐技能==4 """
    MUSIC_LE_1 = "music_le_1"
    """ 属性_能力 自身音乐技能<=1 """
    MUSIC_GE_3 = "music_ge_3"
    """ 属性_能力 自身音乐技能>=3 """
    MUSIC_GE_5 = "music_ge_5"
    """ 属性_能力 自身音乐技能>=5 """
    TARGET_MUSIC_1 = "t_music_1"
    """ 属性_能力 交互对象音乐技能==1 """
    TARGET_MUSIC_2 = "t_music_2"
    """ 属性_能力 交互对象音乐技能==2 """
    TARGET_MUSIC_3 = "t_music_3"
    """ 属性_能力 交互对象音乐技能==3 """
    TARGET_MUSIC_4 = "t_music_4"
    """ 属性_能力 交互对象音乐技能==4 """
    TARGET_MUSIC_LE_1 = "t_music_le_1"
    """ 属性_能力 交互对象音乐技能<=1 """
    TARGET_MUSIC_GE_3 = "t_music_ge_3"
    """ 属性_能力 交互对象音乐技能>=3 """
    TARGET_MUSIC_GE_5 = "t_music_ge_5"
    """ 属性_能力 交互对象音乐技能>=5 """
    T_FINGER_TEC_GE_1 = "t_finger_tec_ge_1"
    """ 属性_能力 交互对象指技>=1 """
    T_FINGER_TEC_GE_3 = "t_finger_tec_ge_3"
    """ 属性_能力 交互对象指技>=3 """
    T_FINGER_TEC_GE_5 = "t_finger_tec_ge_5"
    """ 属性_能力 交互对象指技>=5 """
    T_FINGER_TEC_GE_7 = "t_finger_tec_ge_7"
    """ 属性_能力 交互对象指技>=7 """
    T_FINGER_TEC_0 = "t_finger_tec_0"
    """ 属性_能力 交互对象指技==0 """
    T_FINGER_TEC_L_3 = "t_finger_tec_l_3"
    """ 属性_能力 交互对象指技<3 """

    KISS_0 = "kiss_0"
    """ 属性_经验 自身亲吻经验==0 """
    KISS_GE_10 = "kiss_ge_10"
    """ 属性_经验 自身亲吻经验>=10 """
    TARGET_KISS_0 = "t_kiss_0"
    """ 属性_经验 交互对象亲吻经验==0 """
    TARGET_KISS_GE_10 = "t_kiss_ge_10"
    """ 属性_经验 交互对象亲吻经验>=10 """

    TARGET_NOT_FALL = "not_fall"
    """ 属性_素质 交互对象无陷落素质 """
    TARGET_LOVE_1 = "love_1"
    """ 属性_素质 交互对象拥有思慕（爱情系第一阶段） """
    TARGET_LOVE_2 = "love_2"
    """ 属性_素质 交互对象拥有恋慕（爱情系第二阶段） """
    TARGET_LOVE_3 = "love_3"
    """ 属性_素质 交互对象拥有恋人（爱情系第三阶段） """
    TARGET_LOVE_4 = "love_4"
    """ 属性_素质 交互对象拥有爱侣（爱情系第四阶段） """
    TARGET_LOVE_GE_1 = "love_ge_1"
    """ 属性_素质 交互对象爱情系>=思慕 """
    TARGET_LOVE_GE_2 = "love_ge_2"
    """ 属性_素质 交互对象爱情系>=恋慕 """
    TARGET_LOVE_GE_3 = "love_ge_3"
    """ 属性_素质 交互对象爱情系>=恋人 """
    TARGET_LOVE_LE_2 = "love_le_2"
    """ 属性_素质 交互对象爱情系<=恋慕 """
    TARGET_OBEY_1 = "obey_1"
    """ 属性_素质 交互对象拥有屈从（隶属系第一阶段） """
    TARGET_OBEY_2 = "obey_2"
    """ 属性_素质 交互对象拥有驯服（隶属系第二阶段） """
    TARGET_OBEY_3 = "obey_3"
    """ 属性_素质 交互对象拥有宠物（隶属系第三阶段） """
    TARGET_OBEY_4 = "obey_4"
    """ 属性_素质 交互对象拥有奴隶（隶属系第四阶段） """
    TARGET_OBEY_GE_1 = "obey_ge_1"
    """ 属性_素质 交互对象隶属系>=屈从 """
    TARGET_OBEY_GE_2 = "obey_ge_2"
    """ 属性_素质 交互对象隶属系>=驯服 """
    TARGET_OBEY_GE_3 = "obey_ge_3"
    """ 属性_素质 交互对象隶属系>=宠物 """
    TARGET_OBEY_LE_2 = "obey_le_2"
    """ 属性_素质 交互对象隶属系<=驯服 """
    NO_FIRST_KISS = "kiss_0"
    """ 属性_素质 玩家未保有初吻 """
    HAVE_FIRST_KISS = "kiss_1"
    """ 属性_素质 玩家保有初吻 """
    NO_VIRGIN = "virgin_0"
    """ 属性_素质 玩家非童贞 """
    HAVE_VIRGIN = "virgin_1"
    """ 属性_素质 玩家是童贞 """
    NO_A_VIRGIN = "a_virgin_0"
    """ 属性_素质 玩家非A处 """
    HAVE_A_VIRGIN = "a_virgin_1"
    """ 属性_素质 玩家是A处 """
    TARGET_NO_FIRST_KISS = "t_kiss_0"
    """ 属性_素质 交互对象未保有初吻 """
    TARGET_HAVE_FIRST_KISS = "t_kiss_1"
    """ 属性_素质 交互对象保有初吻 """
    TARGET_NO_VIRGIN = "t_virgin_0"
    """ 属性_素质 交互对象非处女 """
    TARGET_HAVE_VIRGIN = "t_virgin_1"
    """ 属性_素质 交互对象是处女 """
    TARGET_NO_A_VIRGIN = "t_a_virgin_0"
    """ 属性_素质 交互对象非A处女 """
    TARGET_HAVE_A_VIRGIN = "t_a_virgin_1"
    """ 属性_素质 交互对象是A处女 """
    T_LOVE_SENSE_TASTE_0 = "t_love_sense_taste_0"
    """ 属性_素质 交互对象精爱味觉==0 """
    T_LOVE_SENSE_TASTE_1 = "t_love_sense_taste_1"
    """ 属性_素质 交互对象精爱味觉==1 """
    T_SADISM_0 = "t_sadism_0"
    """ 属性_素质 交互对象施虐狂==0 """
    T_SADISM_1 = "t_sadism_1"
    """ 属性_素质 交互对象施虐狂==1 """
    T_MASOCHISM_0 = "t_masochism_0"
    """ 属性_素质 交互对象受虐狂==0 """
    T_MASOCHISM_1 = "t_masochism_1"
    """ 属性_素质 交互对象受虐狂==1 """
    T_OESTRUS_0 = "t_oestrus_0"
    """ 属性_素质 交互对象发情期==0 """
    T_OESTRUS_1 = "t_oestrus_1"
    """ 属性_素质 交互对象发情期==1 """
    IS_MEDICAL = "is_medical"
    """ 属性_素质 自己的职业为医疗 """
    T_LACTATION_0 = "t_lactation_0"
    """ 属性_素质 交互对象泌乳==0 """
    T_LACTATION_1 = "t_lactation_1"
    """ 属性_素质 交互对象泌乳==1 """

    TARGET_CHEST_IS_CLIFF = "breast_0"
    """ 属性_素质 交互对象胸部大小是绝壁 """
    TARGET_CHEST_IS_SMALL = "breast_1"
    """ 属性_素质 交互对象胸部大小是贫乳 """
    TARGET_CHEST_IS_NORMAL = "breast_2"
    """ 属性_素质 交互对象胸部大小是普乳 """
    TARGET_CHEST_IS_BIG = "breast_3"
    """ 属性_素质 交互对象胸部大小是巨乳 """
    TARGET_CHEST_IS_SUPER = "breast_4"
    """ 属性_素质 交互对象胸部大小是爆乳 """
    TARGET_BUTTOCKS_IS_SMALL = "buttock_0"
    """ 属性_素质 交互对象臀部大小是小尻 """
    TARGET_BUTTOCKS_IS_NORMAL = "buttock_1"
    """ 属性_素质 交互对象臀部大小是普尻 """
    TARGET_BUTTOCKS_IS_BIG = "buttock_2"
    """ 属性_素质 交互对象臀部大小是巨尻 """

    TARGET_HAVE_NO_EARS = "ear_0"
    """ 属性_素质 交互对象没有兽耳 """
    TARGET_HAVE_EARS = "ear_1"
    """ 属性_素质 交互对象有兽耳 """
    TARGET_HAVE_NO_HORN = "horn_0"
    """ 属性_素质 交互对象没有兽角 """
    TARGET_HAVE_HORN = "horn_1"
    """ 属性_素质 交互对象有兽角 """
    TARGET_HAVE_NO_TAIL = "tail_0"
    """ 属性_素质 交互对象没有兽尾 """
    TARGET_HAVE_TAIL = "tail_1"
    """ 属性_素质 交互对象有兽尾 """
    TARGET_HAVE_NO_RING = "ring_0"
    """ 属性_素质 交互对象没有光环 """
    TARGET_HAVE_RING = "ring_1"
    """ 属性_素质 交互对象有光环 """
    TARGET_HAVE_NO_WING = "wing_0"
    """ 属性_素质 交互对象没有光翼 """
    TARGET_HAVE_WING = "wing_1"
    """ 属性_素质 交互对象有光翼 """
    TARGET_HAVE_NO_TENTACLE = "tentacle_0"
    """ 属性_素质 交互对象没有触手 """
    TARGET_HAVE_TENTACLE = "tentacle_1"
    """ 属性_素质 交互对象有触手 """
    TARGET_HAVE_NO_CAR = "car_0"
    """ 属性_素质 交互对象没有小车 """
    TARGET_HAVE_CAR = "car_1"
    """ 属性_素质 交互对象有小车 """
    TARGET_NOT_PATIENT = "patient_0"
    """ 属性_素质 交互对象不是源石病感染者 """
    TARGET_IS_PATIENT = "patient_1"
    """ 属性_素质 交互对象是源石病感染者 """
    TARGET_HAVE_NO_CRYSTAL = "crystal_0"
    """ 属性_素质 交互对象没有体表源石结晶 """
    TARGET_HAVE_CRYSTAL = "crystal_1"
    """ 属性_素质 交互对象有体表源石结晶 """
    TARGET_HAVE_NO_DILIGENT = "diligent_0"
    """ 属性_素质 交互对象非勤劳 """
    TARGET_HAVE_DILIGENT = "diligent_1"
    """ 属性_素质 交互对象勤劳 """
    TARGET_HAVE_NO_LAZY = "lazy_0"
    """ 属性_素质 交互对象非懒散 """
    TARGET_HAVE_LAZY = "lazy_1"
    """ 属性_素质 交互对象懒散 """
    TARGET_HAVE_NO_FRAGILE = "fragile_0"
    """ 属性_素质 交互对象非脆弱 """
    TARGET_HAVE_FRAGILE = "fragile_1"
    """ 属性_素质 交互对象脆弱 """
    TARGET_HAVE_NO_FORCEFUL = "forceful_0"
    """ 属性_素质 交互对象非坚强 """
    TARGET_HAVE_FORCEFUL = "forceful_1"
    """ 属性_素质 交互对象坚强 """
    TARGET_HAVE_NO_ENTHUSIACTIC = "enthusiactic_0"
    """ 属性_素质 交互对象非热情 """
    TARGET_HAVE_ENTHUSIACTIC = "enthusiactic_1"
    """ 属性_素质 交互对象热情 """
    TARGET_HAVE_NO_ALONE = "alone_0"
    """ 属性_素质 交互对象非孤僻 """
    TARGET_HAVE_ALONE = "alone_1"
    """ 属性_素质 交互对象孤僻 """
    TARGET_HAVE_NO_SHAME = "shame_0"
    """ 属性_素质 交互对象非羞耻 """
    TARGET_HAVE_SHAME = "shame_1"
    """ 属性_素质 交互对象羞耻 """
    TARGET_HAVE_NO_OPEN = "open_0"
    """ 属性_素质 交互对象非开放 """
    TARGET_HAVE_OPEN = "open_1"
    """ 属性_素质 交互对象开放 """

    WEAR_BRA = "wear_bra"
    """ 属性_服装 穿着胸衣 """
    TARGET_WEAR_BRA = "t_wear_bra"
    """ 属性_服装 交互对象穿着胸衣 """
    TARGET_NOT_WEAR_BRA = "t_not_wear_bra"
    """ 属性_服装 交互对象没有穿着胸衣 """
    TARGET_WEAR_GLOVES = "t_wear_gloves"
    """ 属性_服装 交互对象戴着手套 """
    TARGET_NOT_WEAR_GLOVES = "t_not_wear_gloves"
    """ 属性_服装 交互对象没有戴着手套 """
    WEAR_SKIRT = "wear_skirt"
    """ 属性_服装 穿着裙子 """
    TARGET_WEAR_SKIRT = "t_wear_skirt"
    """ 属性_服装 交互对象穿着裙子 """
    TARGET_WEAR_TROUSERS = "t_wear_trousers"
    """ 属性_服装 交互对象穿着裤子 """
    WEAR_PAN = "wear_pan"
    """ 属性_服装 穿着内裤 """
    TARGET_WEAR_PAN = "t_wear_pan"
    """ 属性_服装 交互对象穿着内裤 """
    TARGET_NOT_WEAR_PAN = "t_not_wear_pan"
    """ 属性_服装 交互对象没有穿着内裤 """
    WEAR_SOCKS = "wear_socks"
    """ 属性_服装 穿着袜子 """
    TARGET_WEAR_SOCKS = "t_wear_socks"
    """ 属性_服装 交互对象穿着袜子 """
    CLOTH_OFF = "cloth_off"
    """ 属性_服装 当前全裸 """
    NOT_CLOTH_OFF = "not_cloth_off"
    """ 属性_服装 当前不是全裸 """
    SHOWER_CLOTH = "shower_cloth"
    """ 属性_服装 围着浴巾 """
    NOT_SHOWER_CLOTH = "not_shower_cloth"
    """ 属性_服装 没有围着浴巾 """

    A_SHIT = "a_shit"
    """ 属性_污浊 肠内脏污 """
    ENEMA = "enema"
    """ 属性_污浊 正在灌肠中（含全种类灌肠） """
    NOT_ENEMA = "not_enema"
    """ 属性_污浊 非灌肠中（含全种类灌肠） """
    ENEMA_END = "enema_end"
    """ 属性_污浊 已灌肠（含全种类灌肠） """
    NORMAL_ENEMA = "normal_enema"
    """ 属性_污浊 普通灌肠中 """
    SEMEN_ENEMA = "semen_enema"
    """ 属性_污浊 精液灌肠中 """
    NORMAL_ENEMA_END = "normal_enema_end"
    """ 属性_污浊 已普通灌肠 """
    SEMEN_ENEMA_END = "semen_enema_end"
    """ 属性_污浊 已精液灌肠 """
    T_HAIR_SEMEN = "t_hair_semen"
    """ 属性_污浊 交互对象当前头发有精液 """
    T_WOMB_SEMEN = "t_womb_semen"
    """ 属性_污浊 交互对象当前子宫有精液 """
    T_UP_CLOTH_SEMEN = "t_up_cloth_semen"
    """ 属性_污浊 交互对象当前上衣有精液 """
    T_GLOVE_SEMEN = "t_glove_semen"
    """ 属性_污浊 交互对象当前手套有精液 """
    T_BOTTOM_CLOTH_SEMEN = "t_botton_cloth_semen"
    """ 属性_污浊 交互对象当前下衣有精液 """
    T_PAN_SEMEN = "t_pan_semen"
    """ 属性_污浊 交互对象当前内裤有精液 """
    T_SOCKS_SEMEN = "t_socks_semen"
    """ 属性_污浊 交互对象当前袜子有精液 """

    PENIS_IN_T_HAIR = "penis_in_t_hair"
    """ H_射精与绝顶 当前阴茎位置为交互对象_发交中 """
    PENIS_IN_T_FACE = "penis_in_t_face"
    """ H_射精与绝顶 当前阴茎位置为交互对象_阴茎蹭脸中 """
    PENIS_IN_T_MOUSE = "penis_in_t_mouse"
    """ H_射精与绝顶 当前阴茎位置为交互对象_口交中 """
    PENIS_IN_T_BREAST = "penis_in_t_breast"
    """ H_射精与绝顶 当前阴茎位置为交互对象_乳交中 """
    PENIS_IN_T_AXILLA = "penis_in_t_axilla"
    """ H_射精与绝顶 当前阴茎位置为交互对象_腋交中 """
    PENIS_IN_T_HAND = "penis_in_t_hand"
    """ H_射精与绝顶 当前阴茎位置为交互对象_手交中 """
    PENIS_IN_T_VAGINA = "penis_in_t_vagina"
    """ H_射精与绝顶 当前阴茎位置为交互对象_V插入中 """
    PENIS_IN_T_WOMB = "penis_in_t_womb"
    """ H_射精与绝顶 当前阴茎位置为交互对象_W插入中 """
    PENIS_IN_T_ANAL = "penis_in_t_anal"
    """ H_射精与绝顶 当前阴茎位置为交互对象_A插入中 """
    PENIS_IN_T_URETHRAL = "penis_in_t_nrethral"
    """ H_射精与绝顶 当前阴茎位置为交互对象_U插入中 """
    PENIS_IN_T_LEG = "penis_in_t_leg"
    """ H_射精与绝顶 当前阴茎位置为交互对象_腿交中 """
    PENIS_IN_T_FOOT = "penis_in_t_foot"
    """ H_射精与绝顶 当前阴茎位置为交互对象_足交中 """
    PENIS_IN_T_TAIL = "penis_in_t_tail"
    """ H_射精与绝顶 当前阴茎位置为交互对象_尾交中 """
    PENIS_IN_T_HORN = "penis_in_t_horn"
    """ H_射精与绝顶 当前阴茎位置为交互对象_阴茎蹭角中 """
    PENIS_IN_T_EARS = "penis_in_t_ears"
    """ H_射精与绝顶 当前阴茎位置为交互对象_阴茎蹭耳朵中 """
    SHOOT_IN_T_BODY = "shoot_in_t_body"
    """ H_射精与绝顶 在交互对象的身体上射精（即含全部位） """
    SHOOT_IN_T_HAIR = "shoot_in_t_hair"
    """ H_射精与绝顶 在交互对象的头发射精 """
    SHOOT_IN_T_FACE = "shoot_in_t_face"
    """ H_射精与绝顶 在交互对象的脸部射精 """
    SHOOT_IN_T_MOUSE = "shoot_in_t_mouse"
    """ H_射精与绝顶 在交互对象的口腔射精 """
    SHOOT_IN_T_BREAST = "shoot_in_t_breast"
    """ H_射精与绝顶 在交互对象的胸部射精 """
    SHOOT_IN_T_AXILLA = "shoot_in_t_axilla"
    """ H_射精与绝顶 在交互对象的腋部射精 """
    SHOOT_IN_T_HAND = "shoot_in_t_hand"
    """ H_射精与绝顶 在交互对象的手部射精 """
    SHOOT_IN_T_VAGINA = "shoot_in_t_vagina"
    """ H_射精与绝顶 在交互对象的小穴射精 """
    SHOOT_IN_T_WOMB = "shoot_in_t_womb"
    """ H_射精与绝顶 在交互对象的子宫射精 """
    SHOOT_IN_T_ANAL = "shoot_in_t_anal"
    """ H_射精与绝顶 在交互对象的后穴射精 """
    SHOOT_IN_T_URETHRAL = "shoot_in_t_nrethral"
    """ H_射精与绝顶 在交互对象的尿道射精 """
    SHOOT_IN_T_LEG = "shoot_in_t_leg"
    """ H_射精与绝顶 在交互对象的腿部射精 """
    SHOOT_IN_T_FOOT = "shoot_in_t_foot"
    """ H_射精与绝顶 在交互对象的脚部射精 """
    SHOOT_IN_T_TAIL = "shoot_in_t_tail"
    """ H_射精与绝顶 在交互对象的尾巴射精 """
    SHOOT_IN_T_HORN = "shoot_in_t_horn"
    """ H_射精与绝顶 在交互对象的兽角射精 """
    SHOOT_IN_T_EARS = "shoot_in_t_ears"
    """ H_射精与绝顶 在交互对象的兽耳射精 """
    SHOOT_IN_T_CLOTH = "shoot_in_t_cloth"
    """ H_射精与绝顶 在交互对象的衣服上射精（含全部位） """
    T_TURN_ORGASM_0 = "t_turn_orgasm_0"
    """ H_射精与绝顶 交互对象本次H中还没有绝顶 """
    T_TURN_ORGASM_G_1 = "t_turn_orgasm_g_1"
    """ H_射精与绝顶 交互对象本次H中绝顶次数>1 """
    T_TURN_ORGASM_G_5 = "t_turn_orgasm_g_5"
    """ H_射精与绝顶 交互对象本次H中绝顶次数>5 """
    T_TURN_ORGASM_G_10 = "t_turn_orgasm_g_10"
    """ H_射精与绝顶 交互对象本次H中绝顶次数>10 """
    T_TURN_N_ORGASM_G_3 = "t_turn_n_orgasm_g_3"
    """ H_射精与绝顶 交互对象本次H中N绝顶次数>3 """
    T_TURN_B_ORGASM_G_3 = "t_turn_b_orgasm_g_3"
    """ H_射精与绝顶 交互对象本次H中B绝顶次数>3 """
    T_TURN_C_ORGASM_G_3 = "t_turn_c_orgasm_g_3"
    """ H_射精与绝顶 交互对象本次H中C绝顶次数>3 """
    TURN_P_ORGASM_G_1 = "turn_p_orgasm_g_1"
    """ H_射精与绝顶 玩家本次H中射精次数>1 """
    TURN_P_ORGASM_G_3 = "turn_p_orgasm_g_3"
    """ H_射精与绝顶 玩家本次H中射精次数>3 """
    T_TURN_V_ORGASM_G_3 = "t_turn_v_orgasm_g_3"
    """ H_射精与绝顶 交互对象本次H中V绝顶次数>3 """
    T_TURN_A_ORGASM_G_3 = "t_turn_a_orgasm_g_3"
    """ H_射精与绝顶 交互对象本次H中A绝顶次数>3 """
    T_TURN_U_ORGASM_G_3 = "t_turn_u_orgasm_g_3"
    """ H_射精与绝顶 交互对象本次H中U绝顶次数>3 """
    T_TURN_W_ORGASM_G_3 = "t_turn_w_orgasm_g_3"
    """ H_射精与绝顶 交互对象本次H中W绝顶次数>3 """
    T_TURN_M_ORGASM_G_3 = "t_turn_m_orgasm_g_3"
    """ H_射精与绝顶 交互对象本次H中M绝顶次数>3 """

    HAVE_FOOD = "have_food"
    """ 道具_持有 拥有食物 """
    NOT_HAVE_FOOD = "not_have_food"
    """ 道具_持有 未拥有食物 """
    HAVE_CAMERA = "have_camera"
    """ 道具_持有 已持有相机 """
    HAVE_VIDEO_RECORDER = "have_video_recorder"
    """ 道具_持有 已持有录像机 """
    HAVE_INSTRUMENT = "have_instrument"
    """ 道具_持有 已持有乐器 """
    HAVE_NIPPLE_CLAMP = "have_nipple_clamp"
    """ 道具_持有 已持有乳头夹 """
    HAVE_LOVE_EGG = "have_love_egg"
    """ 道具_持有 已持有跳蛋 """
    HAVE_CLIT_CLAMP = "have_clit_clamp"
    """ 道具_持有 已持有阴蒂夹 """
    HAVE_ELECTRIC_MESSAGE_STICK = "have_electric_message_stick"
    """ 道具_持有 已持有电动按摩棒 """
    HAVE_VIBRATOR = "have_vibrator"
    """ 道具_持有 已持有震动棒 """
    HAVE_MILKING_MACHINE = "have_milking_machine"
    """ 道具_持有 已持有搾乳机 """
    HAVE_URINE_COLLECTOR = "have_urine_collector"
    """ 道具_持有 已持有采尿器 """
    HAVE_BONDAGE = "have_bondage"
    """ 道具_持有 已持有绳子 """
    HAVE_PATCH = "have_patch"
    """ 道具_持有 已持有眼罩 """
    HAVE_BIG_VIBRATOR = "have_big_vibrator"
    """ 道具_持有 已持有加粗震动棒 """
    HAVE_HUGE_VIBRATOR = "have_huge_vibrator"
    """ 道具_持有 已持有巨型震动棒 """
    HAVE_CLYSTER_TOOLS = "have_clyster_tools"
    """ 道具_持有 已持有灌肠套装 """
    HAVE_ANAL_BEADS = "have_anal_beads"
    """ 道具_持有 已持有拉珠 """
    HAVE_ANAL_PLUG = "have_anal_plug"
    """ 道具_持有 已持有肛塞 """
    HAVE_WHIP = "have_whip"
    """ 道具_持有 已持有鞭子 """
    HAVE_NEEDLE = "have_needle"
    """ 道具_持有 已持有针 """
    HAVE_COLLAR = "have_collar"
    """ 道具_持有 已持有项圈 """
    HAVE_CONDOM = "have_condom"
    """ 道具_持有 已持有避孕套 """
    HAVE_SAFE_CANDLES = "have_safe_candles"
    """ 道具_持有 已持有低温蜡烛 """
    HAVE_COTTON_STICK = "have_cotton_stick"
    """ 道具_持有 已持有无菌棉签 """
    HAVE_BIRTH_CONTROL_PILLS_BEFORE = "have_birth_control_pills_before"
    """ 道具_持有 已持有事前避孕药 """
    HAVE_BIRTH_CONTROL_PILLS_AFTER = "have_birth_control_pills_after"
    """ 道具_持有 已持有事后避孕药 """
    HAVE_BODY_LUBRICANT = "have_body_lubricant"
    """ 道具_持有 已持有润滑液 """
    HAVE_PHILTER = "have_philter"
    """ 道具_持有 已持有媚药 """
    HAVE_ENEMAS = "have_enemas"
    """ 道具_持有 已持有灌肠液 """
    HAVE_DIURETICS_ONCE = "have_diuretics_once"
    """ 道具_持有 已持有一次性利尿剂 """
    HAVE_DIURETICS_PERSISTENT = "have_diuretics_persistent"
    """ 道具_持有 已持有持续性利尿剂 """
    HAVE_SLEEPING_PILLS = "have_sleeping_pills"
    """ 道具_持有 已持有睡眠药 """
    HAVE_CLOMID = "have_clomid"
    """ 道具_持有 已持有排卵促进药 """

    TARGET_NOW_NIPPLE_CLAMP = "target_now_nipple_clamp"
    """ 道具_使用 交互对象正在乳头夹 """
    TARGET_NOT_NIPPLE_CLAMP = "target_not_nipple_clamp"
    """ 道具_使用 交互对象没有在乳头夹 """
    TARGET_NOW_CLIT_CLAMP = "target_now_clit_clamp"
    """ 道具_使用 交互对象正在阴蒂夹 """
    TARGET_NOT_CLIT_CLAMP = "target_not_clit_clamp"
    """ 道具_使用 交互对象没有在阴蒂夹 """
    TARGET_NOW_ANAL_BEADS = "target_now_anal_beads"
    """ 道具_使用 交互对象正在肛门拉珠 """
    TARGET_NOT_ANAL_BEADS = "target_not_anal_beads"
    """ 道具_使用 交互对象没有在肛门拉珠 """
    TARGET_NOW_VIBRATOR_INSERTION = "target_now_vibrator_insertion"
    """ 道具_使用 交互对象V正插入震动棒 """
    TARGET_NOT_VIBRATOR_INSERTION = "target_not_vibrator_insertion"
    """ 道具_使用 交互对象V没有在插入震动棒 """
    TARGET_NOW_VIBRATOR_INSERTION_ANAL = "target_now_vibrator_insertion_anal"
    """ 道具_使用 交互对象A正插入震动棒 """
    TARGET_NOT_VIBRATOR_INSERTION_ANAL = "target_not_vibrator_insertion"
    """ 道具_使用 交互对象A没有在插入震动棒 """

    HAVE_COLLECTION = "have_collection"
    """ 收集 持有藏品 """
    COLLECT_BONUS_103 = "c_bonus_103"
    """ 收集 收藏奖励_103_解锁索要内裤 """
    COLLECT_BONUS_203 = "c_bonus_203"
    """ 收集 收藏奖励_203_解锁索要袜子 """

    PATIENT_WAIT = "patient_wait"
    """ 经营 有患者正等待就诊 """

    TO_DO = "to_do"
    """ 未分类 未实装 """


