from typing import Dict, List, Set
from types import FunctionType
from Script.Core import get_text
_: FunctionType = get_text._
""" 翻译api """


class CharacterStatus:
    """角色状态id"""

    STATUS_ARDER = 0
    """ 空闲状态 """
    STATUS_MOVE = 1
    """ 移动状态 """
    STATUS_WAIT = 2
    """ 等待 """
    STATUS_CHANGE_CLOTH = 3
    """ 换衣服状态 """
    STATUS_CHARA_DIY_INSTRUCT = 5
    """ 角色自定义指令 """
    STATUS_EMPTY_INSTRUCT = 99
    """ 空白示范指令 """
    STATUS_CHAT = 101
    """ 聊天状态 """
    STATUS_CHAT_FAILED = 102
    """ 谈话次数过多的状态 """
    STATUS_STROKE = 103
    """ 身体接触 """
    STATUS_MASSAGE = 104
    """ 按摩 """
    STATUS_REST = 110
    """ 休息状态 """
    STATUS_SLEEP = 111
    """ 睡觉 """
    STATUS_TAKE_SHOWER = 112
    """ 淋浴 """
    STATUS_GET_UP = 113
    """ 起床 """
    STATUS_FOLLOW = 115
    """ NPC跟随玩家 """
    STATUS_END_FOLLOW = 116
    """ NPC停止跟随玩家 """
    STATUS_APOLOGIZE = 117
    """ 道歉 """
    STATUS_APOLOGIZE_FAILED = 118
    """ 道歉失败 """
    STATUS_LISTEN_COMPLAINT = 119
    """ 听牢骚 """
    STATUS_MAKE_COFFEE = 131
    """ 泡咖啡 """
    STATUS_MAKE_COFFEE_ADD = 132
    """ 泡咖啡（加料） """
    STATUS_ASK_MAKE_COFFEE = 133
    """ 让对方泡咖啡 """
    STATUS_MAKE_FOOD = 134
    """ 做饭 """
    STATUS_EAT = 135
    """ 进食状态 """
    STATUS_REFUSE_EAT = 136
    """ 拒绝进食 """
    STATUS_BUY_FOOD = 137
    """ 购买食物 """
    STATUS_PEE = 140
    """ 解手 """
    STATUS_CLOTH_OFF = 141
    """ 脱掉全部衣服 """
    STATUS_PUT_SHOWER_CLOTH = 142
    """ 换上浴帽和浴巾 """
    STATUS_PUT_SLEEP_CLOTH = 143
    """ 换上睡衣和内衣 """
    STATUS_WEAR_TO_LOCKER = 144
    """ 身上衣服脱到衣柜 """
    STATUS_LOCKER_TO_WEAR = 145
    """ 衣柜衣服穿回身上 """
    STATUS_READY_TO_SWIM = 146
    """ 脱掉衣服并换上泳衣并进入要游泳状态 """
    STATUS_FOOT_CLOTH_TO_LOCKER =147
    """ 袜子和鞋子转移到衣柜里 """
    STATUS_WEAR_TO_LOCKER_AND_GET_SHOWER_CLOTH = 148
    """ 身上衣服脱到衣柜并换上浴帽和浴巾 """
    STATUS_CLEAN_WEAR_AND_LOCKER_TO_WEAR = 149
    """ 清空身上的衣服然后穿回衣柜的衣服 """
    STATUS_SINGING = 151
    """ 唱歌 """
    STATUS_PLAY_INSTRUMENT = 152
    """ 演奏乐器 """
    STATUS_WATCH_MOVIE = 153
    """ 看电影 """
    STATUS_PHOTOGRAPHY = 154
    """ 摄影 """
    STATUS_PLAY_WATER = 155
    """ 玩水 """
    STATUS_PLAY_CHESS = 156
    """ 下棋 """
    STATUS_PLAY_MAHJONG = 157
    """ 打麻将 """
    STATUS_PLAY_CARDS = 158
    """ 打牌 """
    STATUS_REHEARSE_DANCE = 159
    """ 排演舞剧 """
    STATUS_PLAY_ARCADE_GAME = 160
    """ 玩街机游戏 """
    STATUS_SWIMMING = 161
    """ 游泳 """
    STATUS_TASTE_WINE = 162
    """ 品酒 """
    STATUS_TASTE_TEA = 163
    """ 品茶 """
    STATUS_TASTE_COFFEE = 164
    """ 品咖啡 """
    STATUS_TASTE_DESSERT = 165
    """ 品尝点心 """
    STATUS_TASTE_FOOD = 166
    """ 品尝美食 """
    STATUS_PLAY_HOUSE = 167
    """ 过家家 """
    STATUS_STYLE_HAIR = 168
    """ 修整发型 """
    STATUS_FULL_BODY_STYLING = 169
    """ 全身造型服务 """
    STATUS_LISTEN_INFLATION = 171
    """ 听肚子里的动静 """
    STATUS_PLAY_WITH_CHILD = 172
    """ 一起玩耍 """
    STATUS_PL_WIN_IN_BOARD_GAME = 173
    """ 博士在桌游中获胜 """
    STATUS_PL_LOSE_IN_BOARD_GAME = 174
    """ 博士在桌游中输了 """
    STATUS_SOAK_FEET = 181
    """ 泡脚 """
    STATUS_STEAM_SAUNA = 182
    """ 蒸桑拿 """
    STATUS_HYDROTHERAPY_TREATMENT = 183
    """ 水疗护理 """
    STATUS_ONSEN_BATH = 184
    """ 泡温泉 """
    STATUS_AROMATHERAPY_1 = 191
    """ 香薰疗愈_回复 """
    STATUS_AROMATHERAPY_2 = 192
    """ 香薰疗愈_习得 """
    STATUS_AROMATHERAPY_3 = 193
    """ 香薰疗愈_反感 """
    STATUS_AROMATHERAPY_4 = 194
    """ 香薰疗愈_快感 """
    STATUS_AROMATHERAPY_5 = 195
    """ 香薰疗愈_好感 """
    STATUS_AROMATHERAPY_6 = 196
    """ 香薰疗愈_催眠 """
    STATUS_OFFICIAL_WORK = 201
    """ 处理公务 """
    STATUS_ASSISTANT_ADJUSTMENTS = 204
    """ 助理相关调整 """
    STATUS_TRAINING = 205
    """ 战斗训练 """
    STATUS_EXERCISE = 206
    """ 锻炼身体 """
    STATUS_CURE_PATIENT = 207
    """ 诊疗病人 """
    STATUS_RECRUIT = 208
    """ 招募干员 """
    STATUS_INVITE_VISITOR = 209
    """ 邀请访客 """
    STATUS_READ_BOOK = 210
    """ 读书 """
    STATUS_TEACH = 213
    """ 授课 """
    STATUS_ATTENT_CLASS = 214
    """ 上学 """
    STATUS_MAINTENANCE_FACILITIES = 215
    """ 维护设施 """
    STATUS_REPAIR_EQUIPMENT = 216
    """ 维修装备 """
    STATUS_NPC_WORK_COOK = 217
    """ 干员工作做饭 """
    STATUS_PRODUCE = 218
    """ 制造产品 """
    STATUS_PLANT_MANAGE_CROP = 219
    """ 种植与养护作物 """
    STATUS_DEAL_WITH_DIPLOMACY = 221
    """ 处理外交事宜 """
    STATUS_MORNING_SALUTATION_1 = 251
    """ 早安问候：叫起床 """
    STATUS_MORNING_SALUTATION_2 = 252
    """ 早安问候：早安吻 """
    STATUS_MORNING_SALUTATION_3 = 253
    """ 早安问候：早安咬 """
    STATUS_NIGHT_SALUTATION_1 = 254
    """ 晚安问候：催睡觉 """
    STATUS_NIGHT_SALUTATION_2 = 255
    """ 晚安问候：晚安吻 """
    STATUS_NIGHT_SALUTATION_3 = 256
    """ 晚安问候：晚安咬 """
    STATUS_NPC_ASSISTANT_COOK = 261
    """ 干员助理做饭 """
    STATUS_TOUCH_HEAD = 301
    """ 摸头 """
    STATUS_TOUCH_BREAST = 302
    """ 摸胸 """
    STATUS_TOUCH_BUTTOCKS = 303
    """ 摸屁股 """
    STATUS_TOUCH_EARS = 304
    """ 摸耳朵 """
    STATUS_TOUCH_HORN = 305
    """ 摸角 """
    STATUS_TOUCH_TAIL = 306
    """ 摸尾巴 """
    STATUS_TOUCH_RING = 307
    """ 摸光环 """
    STATUS_TOUCH_WING = 308
    """ 摸光翼 """
    STATUS_TOUCH_TENTACLE = 309
    """ 摸触手 """
    STATUS_TOUCH_CAR = 310
    """ 摸小车 """
    STATUS_HAND_IN_HAND = 311
    """ 牵手 """
    STATUS_EMBRACE = 312
    """ 拥抱 """
    STATUS_KISS = 313
    """ 亲吻 """
    STATUS_LAP_PILLOW = 314
    """ 膝枕 """
    STATUS_RAISE_SKIRT = 315
    """ 掀起裙子 """
    STATUS_ASK_FOR_PAN = 316
    """ 索要内裤 """
    STATUS_ASK_FOR_SOCKS = 317
    """ 索要袜子 """
    STATUS_TOUCH_CLITORIS = 331
    """ 阴蒂爱抚 """
    STATUS_TOUCH_VAGINA = 332
    """ 手指插入（V） """
    STATUS_TOUCH_ANUS = 333
    """ 手指插入（A） """
    STATUS_MILK = 336
    """ 挤奶 """
    STATUS_SMELL_UNDERWEAR = 341
    """ 闻内衣 """
    STATUS_STEAL_PAN = 342
    """ 偷走内裤 """
    STATUS_STEAL_SOCKS = 343
    """ 偷走袜子 """
    STATUS_STEAL_SCENE_ALL_PAN = 344
    """ 偷走所有人内裤 """
    STATUS_STEAL_SCENE_ALL_SOCKS = 345
    """ 偷走所有人袜子 """
    STATUS_BAGGING_AND_MOVING = 351
    """ 装袋搬走 """
    STATUS_PUT_INTO_PRISON = 352
    """ 投入监牢 """
    STATUS_SET_FREE = 353
    """ 解除囚禁 """
    STATUS_H = 361
    """ 进入H状态 """
    STATUS_END_H = 362
    """ 结束H状态 """
    STATUS_DO_H_FAIL = 363
    """ 邀请H失败 """
    STATUS_H_HP_0 = 364
    """ H时博士体力为零中断 """
    STATUS_T_H_HP_0 = 365
    """ H时交互对象体力为零中断 """
    STATUS_H_INTERRUPT = 366
    """ H时被人目击闯入中断 """
    STATUS_NO_CONSCIOUS_H_END = 367
    """ 结束无意识H """
    STATUS_ASK_GROUP_SEX = 368
    """ 邀请多P """
    STATUS_GROUP_SEX_END = 369
    """ 结束多P """
    STATUS_ASK_GROUP_SEX_FAIL = 370
    """ 邀请多P失败 """
    STATUS_CONFESSION = 371
    """ 告白 """
    STATUS_CONFESSION_FAILED = 372
    """ 告白失败 """
    STATUS_GIVE_NECKLACE = 373
    """ 戴上项圈 """
    STATUS_GIVE_NECKLACE_FAILED = 374
    """ 戴上项圈失败 """
    STATUS_SEE_H = 396
    """ 目睹玩家与其他角色H """
    STATUS_KISS_FAIL = 397
    """ 亲吻失败 """
    STATUS_HIGH_OBSCENITY_ANUS = 398
    """ 重度猥亵失败 """
    STATUS_LOW_OBSCENITY_ANUS = 399
    """ 轻度猥亵失败 """
    STATUS_MAKING_OUT = 401
    """ 身体爱抚 """
    STATUS_KISS_H = 402
    """ 接吻 """
    STATUS_BREAST_CARESS = 403
    """ 胸爱抚 """
    STATUS_TWIDDLE_NIPPLES = 404
    """ 玩弄乳头 """
    STATUS_BREAST_SUCKING = 405
    """ 舔吸乳头 """
    STATUS_CLIT_CARESS = 406
    """ 阴蒂爱抚 """
    STATUS_OPEN_LABIA = 407
    """ 掰开阴唇 """
    STATUS_OPEN_ANUS = 408
    """ 掰开肛门 """
    STATUS_CUNNILINGUS = 409
    """ 舔阴 """
    STATUS_LICK_ANAL = 410
    """ 舔肛 """
    STATUS_FINGER_INSERTION = 411
    """ 手指插入(V) """
    STATUS_ANAL_CARESS = 412
    """ 手指插入(A) """
    STATUS_MAKE_MASTUREBATE = 413
    """ 命令对方自慰 """
    STATUS_MAKE_LICK_ANAL = 414
    """ 命令对方舔自己肛门 """
    STATUS_KEEP_ENJOY = 415
    """ 继续享受 """
    STATUS_SEDECU = 416
    """ 诱惑对方 """
    STATUS_ASK_PEE = 417
    """ 命令对方小便 """
    STATUS_MASTUREBATE = 418
    """ 自慰(女) """
    STATUS_HANDJOB = 420
    """ 手交 """
    STATUS_BLOWJOB = 421
    """ 口交 """
    STATUS_PAIZURI = 422
    """ 乳交 """
    STATUS_FOOTJOB = 423
    """ 足交 """
    STATUS_HAIRJOB = 424
    """ 发交 """
    STATUS_AXILLAJOB = 425
    """ 腋交 """
    STATUS_RUB_BUTTOCK = 426
    """ 素股 """
    STATUS_HAND_BLOWJOB = 427
    """ 手交口交 """
    STATUS_TITS_BLOWJOB = 428
    """ 乳交口交 """
    STATUS_FOCUS_BLOWJOB = 429
    """ 真空口交 """
    STATUS_DEEP_THROAT = 430
    """ 深喉插入 """
    STATUS_SIXTY_NINE = 431
    """ 六九式 """
    STATUS_LEGJOB = 432
    """ 腿交 """
    STATUS_TAILJOB = 433
    """ 尾交 """
    STATUS_FACE_RUB = 434
    """ 阴茎蹭脸 """
    STATUS_HORN_RUB = 435
    """ 阴茎蹭角 """
    STATUS_EARS_RUB = 436
    """ 阴茎蹭耳朵 """
    STATUS_CLEAN_BLOWJOB = 437
    """ 清洁口交 """
    STATUS_BODY_LUBRICANT = 451
    """ 润滑液 """
    STATUS_BIRTH_CONTROL_PILLS_BEFORE = 452
    """ 事前避孕药 """
    STATUS_BIRTH_CONTROL_PILLS_AFTER = 453
    """ 事后避孕药 """
    STATUS_PHILTER = 454
    """ 媚药 """
    STATUS_ENEMAS = 455
    """ 灌肠液 """
    STATUS_DIURETICS_ONCE = 456
    """ 一次性利尿剂 """
    STATUS_DIURETICS_PERSISTENT = 457
    """ 持续性利尿剂 """
    STATUS_SLEEPING_PILLS = 458
    """ 安眠药 """
    STATUS_CLOMID = 459
    """ 排卵促进药 """
    STATUS_PUT_CONDOM = 471
    """ 戴上避孕套 """
    STATUS_SAFE_CANDLES = 472
    """ 低温蜡烛 """
    STATUS_URETHRAL_SWAB = 473
    """ 尿道棉棒 """
    STATUS_TAKE_CONDOM_OUT = 474
    """ 摘掉避孕套 """
    STATUS_NIPPLES_LOVE_EGG = 481
    """ 乳头跳蛋 """
    STATUS_NIPPLE_CLAMP_ON = 482
    """ 戴上乳头夹 """
    STATUS_CLIT_LOVE_EGG = 483
    """ 阴蒂跳蛋 """
    STATUS_CLIT_CLAMP_ON = 484
    """ 戴上阴蒂夹 """
    STATUS_ELECTRIC_MESSAGE_STICK = 485
    """ 电动按摩棒 """
    STATUS_VIBRATOR_INSERTION = 486
    """ 震动棒 """
    STATUS_BIG_VIBRATOR_INSERTION = 487
    """ 加粗震动棒 """
    STATUS_HUGE_VIBRATOR_INSERTION = 488
    """ 巨型震动棒 """
    STATUS_VIBRATOR_INSERTION_ANAL = 489
    """ 肛门振动棒 """
    STATUS_BIG_VIBRATOR_INSERTION_ANAL = 490
    """ 加粗肛门震动棒 """
    STATUS_HUGE_VIBRATOR_INSERTION_ANAL = 491
    """ 巨型肛门震动棒 """
    STATUS_CLYSTER = 492
    """ 灌肠 """
    STATUS_ANAL_PLUG = 493
    """ 肛塞 """
    STATUS_ANAL_BEADS = 494
    """ 塞入肛门拉珠 """
    STATUS_CLYSTER_END = 495
    """ 拔出肛塞 """
    STATUS_NIPPLE_CLAMP_OFF = 496
    """ 取下乳头夹 """
    STATUS_CLIT_CLAMP_OFF = 497
    """ 取下阴蒂夹 """
    STATUS_VIBRATOR_INSERTION_OFF = 498
    """ 拔出振动棒 """
    STATUS_VIBRATOR_INSERTION_ANAL_OFF = 499
    """ 拔出肛门振动棒 """
    STATUS_ANAL_BEADS_OFF = 500
    """ 拔出肛门拉珠 """
    STATUS_NORMAL_SEX = 501
    """ 正常位 """
    STATUS_BACK_SEX = 502
    """ 背后位 """
    STATUS_RIDING_SEX = 503
    """ 骑乘位 """
    STATUS_FACE_SEAT_SEX = 504
    """ 对面座位 """
    STATUS_BACK_SEAT_SEX = 505
    """ 背面座位 """
    STATUS_FACE_STAND_SEX = 506
    """ 对面立位 """
    STATUS_BACK_STAND_SEX = 507
    """ 背面立位 """
    STATUS_STIMULATE_G_POINT = 511
    """ 刺激G点 """
    STATUS_WOMB_OS_CARESS = 512
    """ 玩弄子宫口 """
    STATUS_WOMB_INSERTION = 513
    """ 插入子宫口 """
    STATUS_WOMB_SEX = 514
    """ 子宫姦 """
    STATUS_EXTERNAL_WOMB_MASSAGE = 515
    """ 体外子宫按摩 """
    STATUS_NORMAL_ANAL_SEX = 521
    """ 正常位肛交 """
    STATUS_BACK_ANAL_SEX = 522
    """ 后背位肛交 """
    STATUS_RIDING_ANAL_SEX = 523
    """ 骑乘位肛交 """
    STATUS_FACE_SEAT_ANAL_SEX = 524
    """ 对面座位肛交 """
    STATUS_BACK_SEAT_ANAL_SEX = 525
    """ 背面座位肛交 """
    STATUS_FACE_STAND_ANAL_SEX = 526
    """ 对面立位肛交 """
    STATUS_BACK_STAND_ANAL_SEX = 527
    """ 背面立位肛交 """
    STATUS_STIMULATE_SIGMOID_COLON = 530
    """ 玩弄s状结肠 """
    STATUS_STIMULATE_VAGINA = 531
    """ 隔着刺激阴道 """
    STATUS_URETHRAL_FINGER_INSERTION = 541
    """ 尿道指姦 """
    STATUS_URETHRAL_SEX = 542
    """ 尿道姦 """
    STATUS_MILKING_MACHINE_ON = 601
    """ 装上搾乳机 """
    STATUS_URINE_COLLECTOR = 602
    """ 采尿器 """
    STATUS_BONDAGE = 603
    """ 绳子 """
    STATUS_PATCH = 604
    """ 眼罩 """
    STATUS_WHIP = 605
    """ 鞭子 """
    STATUS_NEEDLE = 606
    """ 针 """
    STATUS_MILKING_MACHINE_OFF = 631
    """ 取下搾乳机 """
    STATUS_URINE_COLLECTOR_OFF = 632
    """ 取下采尿器 """
    STATUS_EXERCISE_SUCKING_AND_SWALLOWING = 681
    """ 练习吮吸与吞咽力 """
    STATUS_EXERCISE_ARMPIT_CLAMPING = 682
    """ 练习腋下夹持力 """
    STATUS_EXERCISE_BREAST_CLAMPING = 683
    """ 练习胸部夹持力 """
    STATUS_EXERCISE_HANDS_FLEXIBILITY = 684
    """ 练习手部灵活度 """
    STATUS_EXERCISE_FOOTS_FLEXIBILITY = 685
    """ 练习足部灵活度 """
    STATUS_EXERCISE_VAGINA_FIRMNESS = 686
    """ 练习阴道紧致度 """
    STATUS_EXERCISE_INTESTINE_FIRMNESS = 687
    """ 练习肠道紧致度 """
    STATUS_EXERCISE_TAIL_FLEXIBILITY = 688
    """ 练习尾巴灵活度 """
    STATUS_EXERCISE_TENTACLE_FLEXIBILITY = 689
    """ 练习触手灵活度 """
    STATUS_UNDRESS = 701
    """ 脱衣服 """
    STATUS_HAT_JOB = 710
    """ 帽子交 """
    STATUS_GLASSES_JOB = 711
    """ 眼镜交 """
    STATUS_EAR_ORNAMENT_JOB = 712
    """ 耳饰交 """
    STATUS_NECK_ORNAMENT_JOB = 713
    """ 脖饰交 """
    STATUS_MOUTH_ORNAMENT_JOB = 714
    """ 口罩交 """
    STATUS_TOP_JOB = 715
    """ 上衣交 """
    STATUS_CORSET_JOB = 716
    """ 胸衣交 """
    STATUS_GLOVES_JOB = 717
    """ 手套交 """
    STATUS_SKIRT_JOB = 718
    """ 裙子交 """
    STATUS_UNDERWEAR_JOB = 719
    """ 内裤交 """
    STATUS_SOCKS_JOB = 720
    """ 袜子交 """
    STATUS_SHOES_JOB = 721
    """ 鞋子交 """
    STATUS_WEAPONS_JOB = 722
    """ 武器交 """
    STATUS_TROUSERS_JOB = 723
    """ 裤子交 """
    STATUS_ORGASM_EDGE_ON = 751
    """ 绝顶寸止 """
    STATUS_ORGASM_EDGE_OFF = 752
    """ 绝顶解放 """
    STATUS_HOLD_CHILD = 801
    """ 抱小孩 """
    STATUS_SING_CHILDREN_SONG = 802
    """ 哼唱儿歌 """
    STATUS_NUIRSE_CHILD = 803
    """ 喂奶 """
    STATUS_CHANGE_DIAPERS = 804
    """ 换尿布 """
    STATUS_TEACH_TALK = 805
    """ 教说话 """
    STATUS_GIVE_TOY = 806
    """ 给玩具 """

    STATUS_EXAMINE_HAIR = 850
    """ 检查头发 """
    STATUS_EXAMINE_HAIR_SMOOTHNESS = 851
    """ 测试头发柔顺度 """
    STATUS_EXAMINE_ORAL = 852
    """ 检查口腔内部 """
    STATUS_EXAMINE_SUCKING_AND_SWALLOWING = 853
    """ 测试口腔吮吸与吞咽力 """
    STATUS_EXAMINE_ARMPIT = 854
    """ 检查腋下 """
    STATUS_EXAMINE_ARMPIT_CLAMPING = 855
    """ 测试腋下夹持力 """
    STATUS_EXAMINE_BREAST = 856
    """ 检查胸部 """
    STATUS_EXAMINE_NIPPLE_AND_AREOLA = 857
    """ 检查乳头与乳晕 """
    STATUS_EXAMINE_BREAST_CLAMPING = 858
    """ 测试胸部夹持力 """
    STATUS_EXAMINE_CILITORIS = 859
    """ 检查阴蒂 """
    STATUS_EXAMINE_HANDS = 860
    """ 检查手部 """
    STATUS_EXAMINE_HANDS_FLEXIBILITY = 861
    """ 测试手部灵活度 """
    STATUS_EXAMINE_FOOT = 862
    """ 检查足部 """
    STATUS_EXAMINE_FOOTS_FLEXIBILITY = 863
    """ 测试足部灵活度 """
    STATUS_EXAMINE_VULVA_AND_SHAPE = 871
    """ 检查外阴形状 """
    STATUS_EXAMINE_VAGINA_AND_FOLDS = 872
    """ 检查内阴褶皱 """
    STATUS_EXAMINE_HYMEN = 873
    """ 检查处女膜 """
    STATUS_EXAMINE_ORIFICE = 874
    """ 检查子宫口 """
    STATUS_EXAMINE_VAGINA_FIRMNESS = 875
    """ 测试阴道紧致度 """
    STATUS_EXAMINE_ANUS = 876
    """ 检查菊穴 """
    STATUS_EXAMINE_INTESTINE_FIRMNESS = 877
    """ 测试肠道紧致度 """
    STATUS_EXAMINE_URETHRA = 878
    """ 检查尿道 """
    STATUS_EXAMINE_URINATION_STATUS = 879
    """ 测试现场排尿 """
    STATUS_EXAMINE_TAIL = 881
    """ 检查尾巴 """
    STATUS_EXAMINE_TAIL_FLEXIBILITY = 882
    """ 测试尾巴灵活度 """
    STATUS_EXAMINE_HORN = 883
    """ 检查兽角 """
    STATUS_EXAMINE_EARS = 884
    """ 检查兽耳 """
    STATUS_EXAMINE_WING = 885
    """ 检查翅膀 """
    STATUS_EXAMINE_RING = 886
    """ 检查光环 """
    STATUS_EXAMINE_TENTACLE = 887
    """ 检查触手 """
    STATUS_EXAMINE_TENTACLE_FLEXIBILITY = 888
    """ 测试触手灵活度 """

    STATUS_PENETRATING_VISION_ON = 901
    """ 开启透视 """
    STATUS_PENETRATING_VISION_OFF = 902
    """ 关闭透视 """
    STATUS_HORMONE_ON = 903
    """ 开启信息素 """
    STATUS_HORMONE_OFF = 904
    """ 关闭信息素 """
    STATUS_HYPNOSIS_ONE = 911
    """ 单人催眠 """
    STATUS_HYPNOSIS_ALL = 912
    """ 集体催眠 """
    STATUS_HYPNOSIS_CANCEL = 913
    """ 解除催眠 """
    STATUS_HYPNOSIS_INCREASE_BODY_SENSITIVITY = 921
    """ 体控-敏感度提升 """
    STATUS_HYPNOSIS_FORCE_CLIMAX = 922
    """ 体控-强制高潮 """
    STATUS_HYPNOSIS_FORCE_OVULATION = 923
    """ 体控-强制排卵 """
    STATUS_HYPNOSIS_BLOCKHEAD = 924
    """ 体控-木头人 """
    STATUS_HYPNOSIS_ACTIVE_H = 925
    """ 体控-逆推 """
    STATUS_HYPNOSIS_ROLEPLAY = 931
    """ 心控-角色扮演 """
    STATUS_HYPNOSIS_PAIN_AS_PLEASURE = 932
    """ 心控-苦痛快感化 """
    STATUS_TIME_STOP_ON = 941
    """ 时间停止流动 """
    STATUS_TIME_STOP_OFF = 942
    """ 时间重新流动 """
    STATUS_CARRY_TARGET = 943
    """ 搬运对方 """
    STATUS_STOP_CARRY_TARGET = 944
    """ 停止搬运对方 """
    STATUS_TARGET_FREE_IN_TIME_STOP = 945
    """ 对方在时停中获得自由 """
    STATUS_TARGET_STOP_IN_TIME_STOP = 946
    """ 对方在时停中再次停止 """


class Behavior:
    """行为id"""

    SHARE_BLANKLY = 0
    """ 发呆 """
    MOVE = 1
    """ 移动 """
    WAIT = 2
    """ 等待 """
    CHANGE_CLOTH = 3
    """ 换衣服 """
    CHARA_DIY_INSTRUCT = 5
    """ 角色自定义指令 """
    EMPTY_INSTRUCT = 99
    """ 空白示范指令 """
    CHAT = 101
    """ 聊天 """
    CHAT_FAILED = 102
    """ 谈话次数过多而失败 """
    STROKE = 103
    """ 身体接触 """
    MASSAGE = 104
    """ 按摩 """
    REST = 110
    """ 休息 """
    SLEEP = 111
    """ 睡觉 """
    TAKE_SHOWER = 112
    """ 淋浴 """
    GET_UP = 113
    """ 起床 """
    FOLLOW = 115
    """ 让NPC跟随玩家 """
    END_FOLLOW = 116
    """ 让NPC停止跟随玩家 """
    APOLOGIZE = 117
    """ 道歉 """
    APOLOGIZE_FAILED = 118
    """ 道歉失败 """
    LISTEN_COMPLAINT = 119
    """ 听牢骚 """
    MAKE_COFFEE = 131
    """ 泡咖啡 """
    MAKE_COFFEE_ADD = 132
    """ 泡咖啡（加料） """
    ASK_MAKE_COFFEE = 133
    """ 让对方泡咖啡 """
    MAKE_FOOD = 134
    """ 做饭 """
    EAT = 135
    """ 进食 """
    REFUSE_EAT = 136
    """ 拒绝进食 """
    BUY_FOOD = 137
    """ 购买食物 """
    PEE = 140
    """ 解手 """
    CLOTH_OFF = 141
    """ 脱掉全部衣服 """
    PUT_SHOWER_CLOTH = 142
    """ 换上浴帽和浴巾 """
    PUT_SLEEP_CLOTH = 143
    """ 换上睡衣和内衣 """
    WEAR_TO_LOCKER = 144
    """ 身上衣服脱到衣柜 """
    LOCKER_TO_WEAR = 145
    """ 衣柜衣服穿回身上 """
    READY_TO_SWIM = 146
    """ 脱掉衣服并换上泳衣并进入要游泳状态 """
    FOOT_CLOTH_TO_LOCKER =147
    """ 袜子和鞋子转移到衣柜里 """
    WEAR_TO_LOCKER_AND_GET_SHOWER_CLOTH = 148
    """ 身上衣服脱到衣柜并换上浴帽和浴巾 """
    CLEAN_WEAR_AND_LOCKER_TO_WEAR = 149
    """ 清空身上的衣服然后穿回衣柜的衣服 """
    SINGING = 151
    """ 唱歌 """
    PLAY_INSTRUMENT = 152
    """ 演奏乐器 """
    WATCH_MOVIE = 153
    """ 看电影 """
    PHOTOGRAPHY = 154
    """ 摄影 """
    PLAY_WATER = 155
    """ 玩水 """
    PLAY_CHESS = 156
    """ 下棋 """
    PLAY_MAHJONG = 157
    """ 打麻将 """
    PLAY_CARDS = 158
    """ 打牌 """
    REHEARSE_DANCE = 159
    """ 排演舞剧 """
    PLAY_ARCADE_GAME = 160
    """ 玩街机游戏 """
    SWIMMING = 161
    """ 游泳 """
    TASTE_WINE = 162
    """ 品酒 """
    TASTE_TEA = 163
    """ 品茶 """
    TASTE_COFFEE = 164
    """ 品咖啡 """
    TASTE_DESSERT = 165
    """ 品尝点心 """
    TASTE_FOOD = 166
    """ 品尝美食 """
    PLAY_HOUSE = 167
    """ 过家家 """
    STYLE_HAIR = 168
    """ 修整发型 """
    FULL_BODY_STYLING = 169
    """ 全身造型服务 """
    LISTEN_INFLATION = 171
    """ 听肚子里的动静 """
    PLAY_WITH_CHILD = 172
    """ 一起玩耍 """
    PL_WIN_IN_BOARD_GAME = 173
    """ 博士在桌游中获胜 """
    PL_LOSE_IN_BOARD_GAME = 174
    """ 博士在桌游中输了 """
    SOAK_FEET = 181
    """ 泡脚 """
    STEAM_SAUNA = 182
    """ 蒸桑拿 """
    HYDROTHERAPY_TREATMENT = 183
    """ 水疗护理 """
    ONSEN_BATH = 184
    """ 泡温泉 """
    AROMATHERAPY_1 = 191
    """ 香薰疗愈_回复 """
    AROMATHERAPY_2 = 192
    """ 香薰疗愈_习得 """
    AROMATHERAPY_3 = 193
    """ 香薰疗愈_反感 """
    AROMATHERAPY_4 = 194
    """ 香薰疗愈_快感 """
    AROMATHERAPY_5 = 195
    """ 香薰疗愈_好感 """
    AROMATHERAPY_6 = 196
    """ 香薰疗愈_催眠 """
    OFFICIAL_WORK = 201
    """ 处理公务 """
    BATTLE_COMMAND = 202
    """ 指挥作战 """
    ASSISTANT_ADJUSTMENTS = 204
    """ 助理相关调整 """
    TRAINING = 205
    """ 战斗训练 """
    EXERCISE = 206
    """ 锻炼身体 """
    CURE_PATIENT = 207
    """ 诊疗病人 """
    RECRUIT = 208
    """ 招募干员 """
    INVITE_VISITOR = 209
    """ 邀请访客 """
    READ_BOOK = 210
    """ 读书 """
    TEACH = 213
    """ 授课 """
    ATTENT_CLASS = 214
    """ 上学 """
    MAINTENANCE_FACILITIES = 215
    """ 维护设施 """
    REPAIR_EQUIPMENT = 216
    """ 维修装备 """
    NPC_WORK_COOK = 217
    """ 干员工作做饭 """
    PRODUCE = 218
    """ 制造产品 """
    PLANT_MANAGE_CROP = 219
    """ 种植与养护作物 """
    DEAL_WITH_DIPLOMACY = 221
    """ 处理外交事宜 """
    MORNING_SALUTATION_1 = 251
    """ 早安问候：叫起床 """
    MORNING_SALUTATION_2 = 252
    """ 早安问候：早安吻 """
    MORNING_SALUTATION_3 = 253
    """ 早安问候：早安咬 """
    NIGHT_SALUTATION_1 = 254
    """ 晚安问候：催睡觉 """
    NIGHT_SALUTATION_2 = 255
    """ 晚安问候：晚安吻 """
    NIGHT_SALUTATION_3 = 256
    """ 晚安问候：晚安咬 """
    NPC_ASSISTANT_COOK = 261
    """ 干员助理做饭 """
    TOUCH_HEAD = 301
    """ 摸头 """
    TOUCH_BREAST = 302
    """ 摸胸 """
    TOUCH_BUTTOCKS = 303
    """ 摸屁股 """
    TOUCH_EARS = 304
    """ 摸耳朵 """
    TOUCH_HORN = 305
    """ 摸角 """
    TOUCH_TAIL = 306
    """ 摸尾巴 """
    TOUCH_RING = 307
    """ 摸光环 """
    TOUCH_WING = 308
    """ 摸光翼 """
    TOUCH_TENTACLE = 309
    """ 摸触手 """
    TOUCH_CAR = 310
    """ 摸小车 """
    HAND_IN_HAND = 311
    """ 牵手 """
    EMBRACE = 312
    """ 拥抱 """
    KISS = 313
    """ 亲吻 """
    LAP_PILLOW = 314
    """ 膝枕 """
    RAISE_SKIRT = 315
    """ 掀起裙子 """
    ASK_FOR_PAN = 316
    """ 索要内裤 """
    ASK_FOR_SOCKS = 317
    """ 索要袜子 """
    TOUCH_CLITORIS = 331
    """ 阴蒂爱抚 """
    TOUCH_VAGINA = 332
    """ 手指插入（V） """
    TOUCH_ANUS = 333
    """ 手指插入（A） """
    MILK = 336
    """ 挤奶 """
    SMELL_UNDERWEAR = 341
    """ 闻内衣 """
    STEAL_PAN = 342
    """ 偷走内裤 """
    STEAL_SOCKS = 343
    """ 偷走袜子 """
    STEAL_SCENE_ALL_PAN = 344
    """ 偷走所有人内裤 """
    STEAL_SCENE_ALL_SOCKS = 345
    """ 偷走所有人袜子 """
    BAGGING_AND_MOVING = 351
    """ 装袋搬走 """
    PUT_INTO_PRISON = 352
    """ 投入监牢 """
    SET_FREE = 353
    """ 解除囚禁 """
    H = 361
    """ 进入H状态 """
    END_H = 362
    """ 结束H """
    DO_H_FAIL = 363
    """ 邀请H失败 """
    H_HP_0 = 364
    """ H时博士体力为零中断 """
    T_H_HP_0 = 365
    """ H时交互对象体力为零中断 """
    H_INTERRUPT = 366
    """ H时被人目击闯入中断 """
    NO_CONSCIOUS_H_END = 367
    """ 结束无意识H """
    ASK_GROUP_SEX = 368
    """ 邀请多P """
    GROUP_SEX_END = 369
    """ 结束多P """
    ASK_GROUP_SEX_FAIL = 370
    """ 邀请多P失败 """
    CONFESSION = 371
    """ 告白 """
    CONFESSION_FAILED = 372
    """ 告白失败 """
    GIVE_NECKLACE = 373
    """ 戴上项圈 """
    GIVE_NECKLACE_FAILED = 374
    """ 戴上项圈失败 """
    SEE_H = 396
    """ 目睹玩家与其他角色H """
    KISS_FAIL = 397
    """ 亲吻失败 """
    HIGH_OBSCENITY_ANUS = 398
    """ 重度猥亵失败 """
    LOW_OBSCENITY_ANUS = 399
    """ 轻度猥亵失败 """
    MAKING_OUT = 401
    """ 身体爱抚 """
    KISS_H = 402
    """ 接吻 """
    BREAST_CARESS = 403
    """ 胸爱抚 """
    TWIDDLE_NIPPLES = 404
    """ 玩弄乳头 """
    BREAST_SUCKING = 405
    """ 舔吸乳头 """
    CLIT_CARESS = 406
    """ 阴蒂爱抚 """
    OPEN_LABIA = 407
    """ 掰开阴唇观察 """
    OPEN_ANUS = 408
    """ 掰开肛门观察 """
    CUNNILINGUS = 409
    """ 舔阴 """
    LICK_ANAL = 410
    """ 舔肛 """
    FINGER_INSERTION = 411
    """ 手指插入(V) """
    ANAL_CARESS = 412
    """ 手指插入(A) """
    MAKE_MASTUREBATE = 413
    """ 命令对方自慰 """
    MAKE_LICK_ANAL = 414
    """ 命令对方舔自己肛门 """
    KEEP_ENJOY = 415
    """ 继续享受 """
    SEDECU = 416
    """ 诱惑对方 """
    ASK_PEE = 417
    """ 命令对方小便 """
    MASTUREBATE = 418
    """ 自慰(女) """
    HANDJOB = 420
    """ 手交 """
    BLOWJOB = 421
    """ 口交 """
    PAIZURI = 422
    """ 乳交 """
    FOOTJOB = 423
    """ 足交 """
    HAIRJOB = 424
    """ 发交 """
    AXILLAJOB = 425
    """ 腋交 """
    RUB_BUTTOCK = 426
    """ 素股 """
    HAND_BLOWJOB = 427
    """ 手交口交 """
    TITS_BLOWJOB = 428
    """ 乳交口交 """
    FOCUS_BLOWJOB = 429
    """ 真空口交 """
    DEEP_THROAT = 430
    """ 深喉插入 """
    SIXTY_NINE = 431
    """ 六九式 """
    LEGJOB = 432
    """ 腿交 """
    TAILJOB = 433
    """ 尾交 """
    FACE_RUB = 434
    """ 阴茎蹭脸 """
    HORN_RUB = 435
    """ 阴茎蹭角 """
    EARS_RUB = 436
    """ 阴茎蹭耳朵 """
    CLEAN_BLOWJOB = 437
    """ 清洁口交 """
    BODY_LUBRICANT = 451
    """ 润滑液 """
    BIRTH_CONTROL_PILLS_BEFORE = 452
    """ 事前避孕药 """
    BIRTH_CONTROL_PILLS_AFTER = 453
    """ 事后避孕药 """
    PHILTER = 454
    """ 媚药 """
    ENEMAS = 455
    """ 灌肠液 """
    DIURETICS_ONCE = 456
    """ 一次性利尿剂 """
    DIURETICS_PERSISTENT = 457
    """ 持续性利尿剂 """
    SLEEPING_PILLS = 458
    """ 安眠药 """
    CLOMID = 459
    """ 排卵促进药 """
    PUT_CONDOM = 471
    """ 戴上避孕套 """
    SAFE_CANDLES = 472
    """ 低温蜡烛 """
    URETHRAL_SWAB = 473
    """ 尿道棉棒 """
    TAKE_CONDOM_OUT = 474
    """ 摘掉避孕套 """
    NIPPLES_LOVE_EGG = 481
    """ 乳头跳蛋 """
    NIPPLE_CLAMP_ON = 482
    """ 戴上乳头夹 """
    CLIT_LOVE_EGG = 483
    """ 阴蒂跳蛋 """
    CLIT_CLAMP_ON = 484
    """ 戴上阴蒂夹 """
    ELECTRIC_MESSAGE_STICK = 485
    """ 电动按摩棒 """
    VIBRATOR_INSERTION = 486
    """ V插入震动棒 """
    BIG_VIBRATOR_INSERTION = 487
    """ 加粗震动棒 """
    HUGE_VIBRATOR_INSERTION = 488
    """ 巨型震动棒 """
    VIBRATOR_INSERTION_ANAL = 489
    """ A插入震动棒 """
    BIG_VIBRATOR_INSERTION_ANAL = 490
    """ 加粗肛门震动棒 """
    HUGE_VIBRATOR_INSERTION_ANAL = 491
    """ 巨型肛门震动棒 """
    CLYSTER = 492
    """ 灌肠 """
    ANAL_PLUG = 493
    """ 肛塞 """
    ANAL_BEADS = 494
    """ 塞入肛门拉珠 """
    CLYSTER_END = 495
    """ 拔出肛塞 """
    NIPPLE_CLAMP_OFF = 496
    """ 取下乳头夹 """
    CLIT_CLAMP_OFF = 497
    """ 取下阴蒂夹 """
    VIBRATOR_INSERTION_OFF = 498
    """ 拔出震动棒 """
    VIBRATOR_INSERTION_ANAL_OFF = 499
    """ 拔出肛门震动棒 """
    ANAL_BEADS_OFF = 500
    """ 拔出肛门拉珠 """
    NORMAL_SEX = 501
    """ 正常位 """
    BACK_SEX = 502
    """ 背后位 """
    RIDING_SEX = 503
    """ 骑乘位 """
    FACE_SEAT_SEX = 504
    """ 对面座位 """
    BACK_SEAT_SEX = 505
    """ 背面座位 """
    FACE_STAND_SEX = 506
    """ 对面立位 """
    BACK_STAND_SEX = 507
    """ 背面立位 """
    STIMULATE_G_POINT = 511
    """ 刺激G点 """
    WOMB_OS_CARESS = 512
    """ 玩弄子宫口 """
    WOMB_INSERTION = 513
    """ 插入子宫口 """
    WOMB_SEX = 514
    """ 子宫姦 """
    EXTERNAL_WOMB_MASSAGE = 515
    """ 体外子宫按摩 """
    NORMAL_ANAL_SEX = 521
    """ 正常位肛交 """
    BACK_ANAL_SEX = 522
    """ 后背位肛交 """
    RIDING_ANAL_SEX = 523
    """ 骑乘位肛交 """
    FACE_SEAT_ANAL_SEX = 524
    """ 对面座位肛交 """
    BACK_SEAT_ANAL_SEX = 525
    """ 背面座位肛交 """
    FACE_STAND_ANAL_SEX = 526
    """ 对面立位肛交 """
    BACK_STAND_ANAL_SEX = 527
    """ 背面立位肛交 """
    STIMULATE_SIGMOID_COLON = 530
    """ 玩弄s状结肠 """
    STIMULATE_VAGINA = 531
    """ 隔着刺激阴道 """
    URETHRAL_FINGER_INSERTION = 541
    """ 尿道指姦 """
    URETHRAL_SEX = 542
    """ 尿道姦 """
    # FACE_LAY_SEX = 551
    # """ 对面卧位 """
    # BACK_LAY_SEX = 552
    # """ 背面卧位 """

    MILKING_MACHINE_ON = 601
    """ 装上搾乳机 """
    URINE_COLLECTOR_ON = 602
    """ 装上采尿器 """
    BONDAGE = 603
    """ 绳子 """
    PATCH = 604
    """ 眼罩 """
    WHIP = 605
    """ 鞭子 """
    NEEDLE = 606
    """ 针 """

    MILKING_MACHINE_OFF = 631
    """ 取下搾乳机 """
    URINE_COLLECTOR_OFF = 632
    """ 取下采尿器 """

    EXERCISE_SUCKING_AND_SWALLOWING = 681
    """ 练习吮吸与吞咽力 """
    EXERCISE_ARMPIT_FLEXIBILITY = 682
    """ 练习腋下夹持力 """
    EXERCISE_BREAST_CLAMPING = 683
    """ 练习胸部夹持力 """
    EXERCISE_HANDS_CLAMPING = 684
    """ 练习手部灵活度 """
    EXERCISE_FOOTS_FLEXIBILITY = 685
    """ 练习足部灵活度 """
    EXERCISE_VAGINA_FIRMNESS = 686
    """ 练习阴道紧致度 """
    EXERCISE_INTESTINE_FIRMNESS = 687
    """ 练习肠道紧致度 """
    EXERCISE_TAIL_FLEXIBILITY = 688
    """ 练习尾巴灵活度 """
    EXERCISE_TENTACLE_FLEXIBILITY = 689
    """ 练习触手灵活度 """

    UNDRESS = 701
    """ 脱衣服 """

    HAT_JOB = 710
    """ 帽子交 """
    GLASSES_JOB = 711
    """ 眼镜交 """
    EAR_ORNAMENT_JOB = 712
    """ 耳饰交 """
    NECK_ORNAMENT_JOB = 713
    """ 脖饰交 """
    MOUTH_ORNAMENT_JOB = 714
    """ 口罩交 """
    TOP_JOB = 715
    """ 上衣交 """
    CORSET_JOB = 716
    """ 胸衣交 """
    GLOVES_JOB = 717
    """ 手套交 """
    SKIRT_JOB = 718
    """ 裙子交 """
    UNDERWEAR_JOB = 719
    """ 内裤交 """
    SOCKS_JOB = 720
    """ 袜子交 """
    SHOES_JOB = 721
    """ 鞋子交 """
    WEAPONS_JOB = 722
    """ 武器交 """
    TROUSERS_JOB = 723
    """ 裤子交 """

    ORGASM_EDGE_ON = 751
    """ 绝顶寸止 """
    ORGASM_EDGE_OFF = 752
    """ 绝顶解放 """

    HOLD_CHILD = 801
    """ 抱小孩 """
    SING_CHILDREN_SONG = 802
    """ 哼唱儿歌 """
    NUIRSE_CHILD = 803
    """ 喂奶 """
    CHANGE_DIAPERS = 804
    """ 换尿布 """
    TEACH_TALK = 805
    """ 教说话 """
    GIVE_TOY = 806
    """ 给玩具 """

    EXAMINE_HAIR = 850
    """ 检查头发 """
    EXAMINE_HAIR_SMOOTHNESS = 851
    """ 测试头发柔顺度 """
    EXAMINE_ORAL = 852
    """ 检查口腔内部 """
    EXAMINE_SUCKING_AND_SWALLOWING = 853
    """ 测试口腔吮吸与吞咽力 """
    EXAMINE_ARMPIT = 854
    """ 检查腋下 """
    EXAMINE_ARMPIT_CLAMPING = 855
    """ 测试腋下夹持力 """
    EXAMINE_BREAST = 856
    """ 检查胸部 """
    EXAMINE_NIPPLE_AND_AREOLA = 857
    """ 检查乳头与乳晕 """
    EXAMINE_BREAST_CLAMPING = 858
    """ 测试胸部夹持力 """
    EXAMINE_CILITORIS = 859
    """ 检查阴蒂 """
    EXAMINE_HANDS = 860
    """ 检查手部 """
    EXAMINE_HANDS_FLEXIBILITY = 861
    """ 测试手部灵活度 """
    EXAMINE_FOOT = 862
    """ 检查足部 """
    EXAMINE_FOOTS_FLEXIBILITY = 863
    """ 测试足部灵活度 """
    EXAMINE_VULVA_AND_SHAPE = 871
    """ 检查外阴形状 """
    EXAMINE_VAGINA_AND_FOLDS = 872
    """ 检查内阴褶皱 """
    EXAMINE_HYMEN = 873
    """ 检查处女膜 """
    EXAMINE_ORIFICE = 874
    """ 检查子宫口 """
    EXAMINE_VAGINA_FIRMNESS = 875
    """ 测试阴道紧致度 """
    EXAMINE_ANUS = 876
    """ 检查菊穴 """
    EXAMINE_INTESTINE_FIRMNESS = 877
    """ 测试肠道紧致度 """
    EXAMINE_URETHRA = 878
    """ 检查尿道 """
    EXAMINE_URINATION_STATUS = 879
    """ 测试现场排尿 """
    EXAMINE_TAIL = 881
    """ 检查尾巴 """
    EXAMINE_TAIL_FLEXIBILITY = 882
    """ 测试尾巴灵活度 """
    EXAMINE_HORN = 883
    """ 检查兽角 """
    EXAMINE_EARS = 884
    """ 检查兽耳 """
    EXAMINE_WING = 885
    """ 检查翅膀 """
    EXAMINE_RING = 886
    """ 检查光环 """
    EXAMINE_TENTACLE = 887
    """ 检查触手 """
    EXAMINE_TENTACLE_FLEXIBILITY = 888
    """ 测试触手灵活度 """

    PENETRATING_VISION_ON = 901
    """ 开启透视 """
    PENETRATING_VISION_OFF = 902
    """ 关闭透视 """
    HORMONE_ON = 903
    """ 开启信息素 """
    HORMONE_OFF = 904
    """ 关闭信息素 """
    HYPNOSIS_ONE = 911
    """ 单人催眠 """
    HYPNOSIS_ALL = 912
    """ 集体催眠 """
    HYPNOSIS_CANCEL = 913
    """ 解除催眠 """
    HYPNOSIS_INCREASE_BODY_SENSITIVITY = 921
    """ 体控-敏感度提升 """
    HYPNOSIS_FORCE_CLIMAX = 922
    """ 体控-强制高潮 """
    HYPNOSIS_FORCE_OVULATION = 923
    """ 体控-强制排卵 """
    HYPNOSIS_BLOCKHEAD = 924
    """ 体控-木头人 """
    HYPNOSIS_ACTIVE_H = 925
    """ 体控-逆推 """
    HYPNOSIS_ROLEPLAY = 931
    """ 心控-角色扮演 """
    HYPNOSIS_PAIN_AS_PLEASURE = 932
    """ 心控-苦痛快感化 """
    TIME_STOP_ON = 941
    """ 时间停止流动 """
    TIME_STOP_OFF = 942
    """ 时间重新流动 """
    CARRY_TARGET = 943
    """ 搬运对方 """
    STOP_CARRY_TARGET = 944
    """ 停止搬运对方 """
    TARGET_FREE_IN_TIME_STOP = 945
    """ 对方在时停中获得自由 """
    TARGET_STOP_IN_TIME_STOP = 946
    """ 对方在时停中再次停止 """

class StateMachine:
    """状态机id"""

    WAIT_5_MIN = 0
    """ 原地待机5分钟 """
    WAIT_10_MIN = 1
    """ 原地待机10分钟 """
    WAIT_30_MIN = 2
    """ 原地待机30分钟，并取消跟随状态 """
    FOLLOW = 6
    """ 跟随玩家 """

    SEE_H_AND_MOVE_TO_DORMITORY = 40
    """ 目睹玩家和其他角色H，然后逃回自己宿舍 """
    REST = 43
    """ 休息一会儿 """
    SLEEP = 44
    """ 睡觉 """
    SINGING = 45
    """ 唱歌 """
    PLAY_INSTRUMENT = 46
    """ 演奏乐器 """
    PEE = 50
    """ 解手 """

    START_SHOWER = 71
    """ 进入要脱衣服（洗澡）状态 """
    WEAR_TO_LOCKER = 72
    """ 当前身上衣服转移到衣柜里 """
    TAKE_SHOWER = 73
    """ 淋浴 """
    GET_SHOWER_CLOTH_AND_CLEAN_LOCKER = 74
    """ 换上浴帽和浴巾并清空衣柜 """
    START_EAT_FOOD = 75
    """ 进入要取餐状态 """
    BUY_RAND_FOOD_AT_FOODSHOP = 76
    """ 在食物商店购买随机食物 """
    EAT_BAG_RAND_FOOD = 77
    """ 食用背包内随机食物 """
    START_SLEEP = 78
    """ 进入要睡眠状态 """
    START_REST = 79
    """ 进入要休息状态 """
    START_PEE = 80
    """ 进入要撒尿状态 """
    LOCKER_TO_WEAR = 81
    """ 衣柜里的衣服穿回身上，如果有浴场flag则置0 """
    SIWM_1 = 82
    """ 进入要换泳衣状态 """
    SIWM_2 = 83
    """ 脱掉衣服并换上泳衣并进入要游泳状态 """
    START_BATHHOUSE_ENTERTAINMENT = 85
    """ 进入要去大浴场娱乐_要更衣状态 """
    FOOT_CLOTH_TO_LOCKER = 86
    """ 袜子和鞋子转移到衣柜里 """
    WEAR_TO_LOCKER_AND_GET_SHOWER_CLOTH = 87
    """ 当前身上衣服转移到衣柜里，并换上浴帽和浴巾 """
    CLEAN_WEAR_AND_LOCKER_TO_WEAR = 88
    """ 清空身上的衣服然后穿回衣柜的衣服，如果有浴场或游泳娱乐flag则置0 """
    START_MILK = 89
    """ 进入要挤奶状态 """
    MAKE_MILK = 90
    """ 挤奶 """
    START_MASTUREBATE = 91
    """ 进入要自慰状态 """
    MASTUREBATE = 92
    """ 自慰 """
    GET_CHARA_NORMAL_CLOTH_AND_DAY_EQIP = 93
    """ 起床（换上正常服装+调整管理白天道具） """
    RESET_SHOWER_STATUS_AND_GET_NORMAL_CLOTH = 94
    """ 清零洗澡状态并换上标准衣服 """
    START_MASTUREBATE_BEFORE_SLEEP = 95
    """ 进入要睡前自慰状态 """

    CHAT_TO_DR = 100
    """ 和玩家聊天 """
    STROKE_TO_DR = 101
    """ 和玩家身体接触 """
    MAKE_COFFEE_TO_DR = 102
    """ 给玩家泡咖啡 """
    MAKE_COFFEE_ADD_TO_DR = 103
    """ 给玩家泡咖啡（加料） """

    CHAT_RAND_CHARACTER = 200
    """ 和场景里随机对象聊天 """
    STROKE_RAND_CHARACTER = 201
    """ 和场景里随机对象身体接触 """
    SINGING_RAND_CHARACTER = 202
    """ 唱歌给房间里随机角色听 """
    PLAY_INSTRUMENT_RAND_CHARACTER = 203
    """ 演奏乐器给房间里随机角色听 """

    WORK_CURE_PATIENT = 301
    """ 工作：诊疗病人 """
    WORK_RECRUIT = 302
    """ 工作：招募干员 """
    WORK_TEACH = 303
    """ 工作：授课 """
    WORK_ATTENT_CLASS = 304
    """ 工作：上学 """
    WORK_LIBRARY_1 = 305
    """ 工作：三成去图书馆，七成原地等待30分钟 """
    WORK_LIBRARY_2 = 306
    """ 工作：三成去图书馆办公室，七成看书 """
    WORK_MAINTENANCE_1 = 307
    """ 工作：进入要检修状态，并随机指定一个检修地点 """
    WORK_MAINTENANCE_2 = 308
    """ 工作：维护设施，并清零检修状态 """
    WORK_REPAIR_EQUIPMENT = 309
    """ 工作：修理装备 """
    WORK_COOK = 310
    """ 工作：做饭 """
    WORK_PRODUCE = 311
    """ 工作：制造产品 """
    WORK_OFFICIAL_WORK = 312
    """ 工作：处理公务 """
    WORK_MASSAGE = 313
    """ 工作：按摩（自动寻找对象） """
    WORK_INVITE_VISITOR = 314
    """ 工作：邀请访客 """
    WORK_PLANT_MANAGE_CROP = 315
    """ 工作：种植与养护作物 """
    WORK_DEAL_WITH_DIPLOMACY = 316
    """ 工作：处理外交事宜 """
    WORK_SEX_EXERCISES = 317
    """ 工作：性爱练习 """
    WORK_COMBAT_TRAINING = 318
    """ 工作：战斗训练 """
    WORK_FITNESS_TRAINING = 319
    """ 工作：健身锻炼 """

    ENTERTAIN_READ = 401
    """ 娱乐：读书 """
    # 402空缺占位
    ENTERTAIN_SINGING = 403
    """ 娱乐：唱歌 """
    ENTERTAIN_PLAY_CLASSIC_INSTRUMENT = 404
    """ 娱乐：演奏传统乐器 """
    ENTERTAIN_PLAY_MODEN_INSTRUMENT = 405
    """ 娱乐：演奏现代乐器 """
    ENTERTAIN_WATCH_MOVIE = 406
    """ 娱乐：看电影 """
    ENTERTAIN_PHOTOGRAPHY = 407
    """ 娱乐：摄影 """
    ENTERTAIN_PLAY_WATER = 408
    """ 娱乐：玩水 """
    ENTERTAIN_PLAY_CHESS = 409
    """ 娱乐：下棋 """
    ENTERTAIN_PLAY_MAHJONG = 410
    """ 娱乐：打麻将 """
    ENTERTAIN_PLAY_CARDS = 411
    """ 娱乐：打牌 """
    ENTERTAIN_REHEARSE_DANCE = 412
    """ 娱乐：排演舞剧 """
    ENTERTAIN_PLAY_ARCADE_GAME = 413
    """ 娱乐：玩街机游戏 """
    ENTERTAIN_SWIMMING = 414
    """ 娱乐：游泳 """
    ENTERTAIN_TASTE_WINE = 415
    """ 娱乐：品酒 """
    ENTERTAIN_TASTE_TEA = 416
    """ 娱乐：品茶 """
    ENTERTAIN_TASTE_COFFEE = 417
    """ 娱乐：品咖啡 """
    ENTERTAIN_TASTE_DESSERT = 418
    """ 娱乐：品尝点心 """
    ENTERTAIN_TASTE_FOOD = 419
    """ 娱乐：品尝美食 """
    ENTERTAIN_PLAY_HOUSE = 420
    """ 娱乐：过家家 """
    ENTERTAIN_STYLE_HAIR = 421
    """ 娱乐：修整发型 """
    ENTERTAIN_FULL_BODY_STYLING = 422
    """ 娱乐：全身造型服务 """
    ENTERTAIN_SOAK_FEET = 423
    """ 娱乐：泡脚 """
    ENTERTAIN_STEAM_SAUNA = 424
    """ 娱乐：蒸桑拿 """
    ENTERTAIN_HYDROTHERAPY_TREATMENT = 425
    """ 娱乐：水疗护理 """
    ENTERTAIN_ONSEN_BATH = 426
    """ 娱乐：泡温泉 """

    MOVE_TO_RAND_SCENE = 501
    """ 移动至随机场景 """
    MOVE_TO_DORMITORY = 502
    """ 移动至所属宿舍 """
    MOVE_TO_PLAYER = 503
    """ 移动至玩家位置 """
    CONTINUE_MOVE = 504
    """ 继续移动 """
    MOVE_TO_TOILET = 511
    """ 去洗手间 """
    MOVE_TO_REST_ROOM = 512
    """ 移动至休息室 """
    MOVE_TO_CLINIC = 513
    """ 随机移动到门诊室（含急诊室）（优先去当前没有人的） """
    MOVE_TO_TRAINING_ROOM = 514
    """ 根据职业自动移动至对应训练室 """
    MOVE_TO_BATH_ROOM = 515
    """ 移动至淋浴室 """
    MOVE_TO_RESTAURANT = 516
    """ 移动至餐馆（随机某个正餐餐馆） """
    MOVE_TO_MAINTENANCE_PLACE = 517
    """ 移动至检修地点 """
    MOVE_TO_PRODUCTION_WORKSHOP = 518
    """ 移动至生产车间 """
    MOVE_TO_KITCHEN = 521
    """ 移动至厨房 """
    MOVE_TO_FOODSHOP = 522
    """ 移动至食物商店 """
    MOVE_TO_DINING_HALL = 523
    """ 移动至食堂 """
    MOVE_TO_CLASSIC_MUSIC_ROOM = 524
    """ 移动至夕照区音乐室 """
    MOVE_TO_MODEN_MUSIC_ROOM = 525
    """ 移动至现代音乐排练室 """
    MOVE_TO_MULTIMEDIA_ROOM = 526
    """ 移动至多媒体室 """
    MOVE_TO_PHOTOGRAPHY_STUDIO = 527
    """ 移动至摄影爱好者影棚 """
    MOVE_TO_AQUAPIT_EXPERIENTORIUM = 528
    """ 移动至大水坑快活体验屋 """
    MOVE_TO_BOARD_GAMES_ROOM = 529
    """ 移动至棋牌室 """
    MOVE_TO_FAIRY_BANQUET = 530
    """ 移动至糖果仙子宴会厅 """
    MOVE_TO_BAR = 531
    """ 移动至酒吧 """
    MOVE_TO_HR_OFFICE = 541
    """ 移动到人事部办公室 """
    MOVE_TO_LIBRARY_OFFICE = 551
    """ 移动到图书馆办公室 """
    MOVE_TO_LIBRARY = 552
    """ 移动到图书馆 """
    MOVE_TO_CLASS_ROOM = 561
    """ 移动到教室 """
    MOVE_TO_TEACHER_OFFICE = 562
    """ 移动到教师办公室 """
    MOVE_TO_GOLDEN_GAME_ROOM = 563
    """ 移动到黄澄澄游戏室 """
    MOVE_TO_DR_OFFICE = 571
    """ 移动至博士办公室 """
    MOVE_TO_AVANT_GARDE_ARCADE = 584
    """ 移动至前卫街机厅 """
    MOVE_TO_WALYRIA_CAKE_SHOP = 585
    """ 移动至瓦莱丽蛋糕店 """
    MOVE_TO_STYLING_STUDIO = 586
    """ 移动至造型工作室 """
    MOVE_TO_HAIR_SALON = 587
    """ 移动至理发店 """
    MOVE_TO_TEAHOUSE = 588
    """ 移动至山城茶馆 """
    MOVE_TO_CAFÉ = 589
    """ 移动至哥伦比亚咖啡馆 """
    MOVE_TO_LIGHT_STORE = 590
    """ 移动至花草灯艺屋 """
    MOVE_TO_PIZZERIA = 591
    """ 移动至快捷连锁披萨店 """
    MOVE_TO_SEVEN_CITIES_RESTAURANT = 592
    """ 移动至七城风情餐厅 """
    MOVE_TO_BURGER = 593
    """ 移动至约翰老妈汉堡店 """
    MOVE_TO_HEALTHY_DINER = 594
    """ 移动至健康快餐店 """
    MOVE_TO_LUNGMEN_EATERY = 595
    """ 移动至龙门食坊 """
    MOVE_TO_BATHZONE_LOCKER_ROOM = 601
    """ 移动至大浴场的更衣室 """
    MOVE_TO_FOOT_BATH = 602
    """ 移动至足浴区 """
    MOVE_TO_SAUNA = 603
    """ 移动至桑拿房 """
    MOVE_TO_SPA_ROOM = 604
    """ 移动至水疗房 """
    MOVE_TO_ONSEN = 605
    """ 移动至温泉 """
    MOVE_TO_BATHZONE_REST_ROOM = 606
    """ 移动至大浴场的休息室 """
    MOVE_TO_SWIMMING_POOL = 611
    """ 移动至游泳池 """
    MOVE_TO_TRAINING_LOCKER_ROOM = 612
    """ 移动至训练场的更衣室 """
    MOVE_TO_GYM_ROOM = 613
    """ 移动至健身区 """
    MOVE_TO_MAINTENANCE_DEPARTMENT = 621
    """ 移动至运维部 """
    MOVE_TO_BLACKSMITH_SHOP = 622
    """ 移动至铁匠铺 """
    MOVE_TO_DIPLOMATIC_OFFICE = 631
    """ 移动至外交官办公室 """
    MOVE_TO_HERB_GARDEN = 641
    """ 移动至药田 """
    MOVE_TO_GREENHOUSE = 642
    """ 移动至温室 """
    MOVE_TO_HUMILIATION_ROOM = 651
    """ 移动至调教室 """

    HELP_BUY_FOOD_1 = 701
    """ 进入要买饭状态 """
    HELP_MAKE_FOOD_1 = 702
    """ 进入要做饭状态 """
    ASSISTANT_MAKE_FOOD = 703
    """ 助理：做饭 """
    MORNING_SALUTATION_FLAG_1 = 704
    """ 进入要早安问候状态 """
    MORNING_SALUTATION_1 = 705
    """ 早安问候：叫起床 """
    MORNING_SALUTATION_2 = 706
    """ 早安问候：早安吻 """
    MORNING_SALUTATION_3 = 707
    """ 早安问候：早安咬 """
    NIGHT_SALUTATION_FLAG_1 = 708
    """ 进入要晚安问候状态 """
    NIGHT_SALUTATION_1 = 709
    """ 晚安问候：催睡觉 """
    NIGHT_SALUTATION_2 = 710
    """ 晚安问候：晚安吻 """
    NIGHT_SALUTATION_3 = 711
    """ 晚安问候：晚安咬 """
    NIGHT_SALUTATION_FLAG_2 = 712
    """ 进入已晚安问候状态 """

    SELF_NIPPLE_CLAMP_SWITCH_CHANEG = 751
    """ 切换自己是否装备道具_乳头夹 """
    SELF_CLIT_CLAMP_SWITCH_CHANEG = 752
    """ 切换自己是否装备道具_阴蒂夹 """
    SELF_V_VIBRATOR_SWITCH_CHANEG = 753
    """ 切换自己是否装备道具_V振动棒 """
    SELF_A_VIBRATOR_SWITCH_CHANEG = 754
    """ 切换自己是否装备道具_A振动棒 """


class Panel:
    """面板id"""

    TITLE = 0
    """ 标题面板 """
    CREATOR_CHARACTER = 1
    """ 创建角色面板 """
    IN_SCENE = 2
    """ 场景互动面板 """
    SEE_MAP = 3
    """ 查看地图面板 """
    FOOD_SHOP = 4
    """ 食物商店面板 """
    FOOD_BAG = 5
    """ 食物背包面板 """
    H_ITEM_SHOP = 6
    """ 成人用品商店面板 """
    MAKE_FOOD = 7
    """ 做饭面板 """
    ALL_NPC_POSITION = 8
    """ 查询与召集面板 """
    EJACULATION = 9
    """ 射精面板 """
    DIRTY = 10
    """ 脏污面板 """
    ITEM = 11
    """ 道具面板 """
    ASSISTANT = 12
    """ 助理面板 """
    COLLECTION = 13
    """ 收藏品面板 """
    UNDRESS = 14
    """ 脱衣服面板 """
    BUILDING = 15
    """ 基建面板 """
    MANAGE_BASEMENT = 16
    """ 管理罗德岛面板 """
    INSTRUCT_FILTER = 17
    """ 指令过滤面板 """
    EVENT_OPTION = 18
    """ 事件选项面板 """
    CHECK_LOCKER = 19
    """ 检查衣柜面板 """
    BORROW_BOOK = 20
    """ 借阅书籍面板 """
    MANAGE_LIBRARY = 21
    """ 图书馆管理面板 """
    DEBUG_ADJUST = 22
    """ DEBUG面板 """
    ORIGINIUM_ARTS = 23
    """ 源石技艺面板 """
    PRTS = 24
    """ 普瑞赛斯面板 """
    NAVIGATION = 25
    """ 导航面板 """
    RECRUITMENT = 26
    """ 招募面板 """
    VISITOR = 27
    """ 访客面板 """
    FRIDGE = 28
    """ 冰箱面板 """
    SYSTEM_SETTING = 29
    """ 系统设置面板 """
    AROMATHERAPY = 30
    """ 香薰疗愈面板 """
    NATION_DIPLOMACY = 31
    """ 势力外交面板 """
    CHAT_AI_SETTING = 32
    """ 文本生成AI设置面板 """
    PHYSICAL_CHECK_AND_MANAGE = 35
    """ 身体检查与管理面板 """


class SecondBehavior:
    """二段结算行为函数"""

    N_orgasm_small = 1000
    """ 结算N小绝顶 """
    N_orgasm_normal = 1001
    """ 结算N普绝顶 """
    N_orgasm_strong = 1002
    """ 结算N强绝顶 """
    B_orgasm_small = 1003
    """ 结算B小绝顶 """
    B_orgasm_normal = 1004
    """ 结算B普绝顶 """
    B_orgasm_strong = 1005
    """ 结算B强绝顶 """
    C_orgasm_small = 1006
    """ 结算C小绝顶 """
    C_orgasm_normal = 1007
    """ 结算C普绝顶 """
    C_orgasm_strong = 1008
    """ 结算C强绝顶 """
    P_orgasm_small = 1009
    """ 结算射精 """
    P_orgasm_normal = 1010
    """ 结算大量射精 """
    P_orgasm_strong = 1011
    """ 结算超大量射精 """
    V_orgasm_small = 1012
    """ 结算V小绝顶 """
    V_orgasm_normal = 1013
    """ 结算V普绝顶 """
    V_orgasm_strong = 1014
    """ 结算V强绝顶 """
    A_orgasm_small = 1015
    """ 结算A小绝顶 """
    A_orgasm_normal = 1016
    """ 结算A普绝顶 """
    A_orgasm_strong = 1017
    """ 结算A强绝顶 """
    U_orgasm_small = 1018
    """ 结算U小绝顶 """
    U_orgasm_normal = 1019
    """ 结算U普绝顶 """
    U_orgasm_strong = 1020
    """ 结算U强绝顶 """
    W_orgasm_small = 1021
    """ 结算W小绝顶 """
    W_orgasm_normal = 1022
    """ 结算W普绝顶 """
    W_orgasm_strong = 1023
    """ 结算W强绝顶 """
    EXTRA_ORGASM = 1026
    """ 结算额外绝顶 """
    SEMEN_DRINKING_CLIMAX = 1027
    """ 结算饮精绝顶 """
    HAPPY_MARK_1 = 1030
    """ 结算快乐刻印1 """
    HAPPY_MARK_2 = 1031
    """ 结算快乐刻印2 """
    HAPPY_MARK_3 = 1032
    """ 结算快乐刻印3 """
    YIELD_MARK_1 = 1033
    """ 结算屈服刻印1 """
    YIELD_MARK_2 = 1034
    """ 结算屈服刻印2 """
    YIELD_MARK_3 = 1035
    """ 结算屈服刻印3 """
    PAIN_MARK_1 = 1036
    """ 结算苦痛刻印1 """
    PAIN_MARK_2 = 1037
    """ 结算苦痛刻印2 """
    PAIN_MARK_3 = 1038
    """ 结算苦痛刻印3 """
    TIME_MARK_1 = 1039
    """ 结算时姦刻印1 """
    TIME_MARK_2 = 1040
    """ 结算时姦刻印2 """
    TIME_MARK_3 = 1041
    """ 结算时姦刻印3 """
    TERROR_MARK_1 = 1042
    """ 结算恐怖刻印1 """
    TERROR_MARK_2 = 1043
    """ 结算恐怖刻印2 """
    TERROR_MARK_3 = 1044
    """ 结算恐怖刻印3 """
    HATE_MARK_1 = 1045
    """ 结算反发刻印1 """
    HATE_MARK_2 = 1046
    """ 结算反发刻印2 """
    HATE_MARK_3 = 1047
    """ 结算反发刻印3 """
    FIRST_KISS = 1050
    """ 结算初吻 """
    FIRST_SEX = 1051
    """ 结算处女 """
    FIRST_A_SEX = 1052
    """ 结算A处女 """
    UNCONSCIOUS_MARK_1 = 1061
    """ 结算无觉刻印1 """
    UNCONSCIOUS_MARK_2 = 1062
    """ 结算无觉刻印2 """
    UNCONSCIOUS_MARK_3 = 1063
    """ 结算无觉刻印3 """
    UNCONSCIOUS_MARK_4 = 1064
    """ 结算无觉刻印4 """
    UNCONSCIOUS_MARK_5 = 1065
    """ 结算无觉刻印5 """
    UNCONSCIOUS_MARK_6 = 1066
    """ 结算无觉刻印6 """

    B_ORGASM_TO_MILK = 1071
    """ 结算因B绝顶而被迫喷乳 """
    U_ORGASM_TO_PEE = 1072
    """ 结算因U绝顶而被迫漏尿 """

    DOUBLE_ORGASM = 1081
    """ 结算双重绝顶 """
    TRIPLE_ORGASM = 1082
    """ 结算三重绝顶 """
    QUADRUPLE_ORGASM = 1083
    """ 结算四重绝顶 """
    QUINTUPLE_ORGASM = 1084
    """ 结算五重绝顶 """
    SEXTUPLE_ORGASM = 1085
    """ 结算六重绝顶 """
    SEPTUPLE_ORGASM = 1086
    """ 结算七重绝顶 """

    N_ORGASM_SUPER = 1090
    """ 结算N超强绝顶 """
    B_ORGASM_SUPER = 1091
    """ 结算B超强绝顶 """
    C_ORGASM_SUPER = 1092
    """ 结算C超强绝顶 """
    V_ORGASM_SUPER = 1094
    """ 结算V超强绝顶 """
    A_ORGASM_SUPER = 1095
    """ 结算A超强绝顶 """
    U_ORGASM_SUPER = 1096
    """ 结算U超强绝顶 """
    W_ORGASM_SUPER = 1097
    """ 结算W超强绝顶 """

    NIPPLE_CLAMP = 1100
    """ 结算乳头夹 """
    CLIT_CLAMP = 1101
    """ 结算阴蒂夹 """
    VIBRATOR_INSERTION = 1102
    """ 结算震动棒 """
    VIBRATOR_INSERTION_ANAL = 1103
    """ 结算肛门振动棒 """
    MILKING_MACHINE = 1104
    """ 结算搾乳机 """
    URINE_COLLECTOR = 1105
    """ 结算采尿器 """
    PATCH = 1106
    """ 结算眼罩 """
    ANAL_BEADS = 1107
    """ 结算肛门拉珠 """
    DIURETICS = 1108
    """ 结算利尿剂 """
    SLEEPING_PILLS = 1109
    """ 结算安眠药 """
    SLEEPING_CLOMID = 1110
    """ 结算排卵促进药 """
    SLEEPING_BIRTH_CONTROL_PILLS_BEFORE = 1111
    """ 结算事前避孕药 """
    SLEEPING_BIRTH_CONTROL_PILLS_AFTER = 1112
    """ 结算事后避孕药 """

    PENIS_IN_HAIR = 1201
    """ 结算发交中 """
    PENIS_IN_FACE = 1202
    """ 结算阴茎蹭脸中 """
    PENIS_IN_MOUSE = 1203
    """ 结算口交中 """
    PENIS_IN_BREAST = 1204
    """ 结算乳交中 """
    PENIS_IN_AXILLA = 1205
    """ 结算腋交中 """
    PENIS_IN_HAND = 1206
    """ 结算手交中 """
    PENIS_IN_VAGINA = 1207
    """ 结算V插入中 """
    PENIS_IN_WOMB = 1208
    """ 结算W插入中 """
    PENIS_IN_ANAL = 1209
    """ 结算A插入中 """
    PENIS_IN_URETHRAL = 1210
    """ 结算U插入中 """
    PENIS_IN_LEG = 1211
    """ 结算腿交中 """
    PENIS_IN_FOOT = 1212
    """ 结算足交中 """
    PENIS_IN_TAIL = 1213
    """ 结算尾交中 """
    PENIS_IN_HORN = 1214
    """ 结算阴茎蹭角中 """
    PENIS_IN_EARS = 1215
    """ 结算阴茎蹭耳朵中 """
    PENIS_IN_RUB_BUTTOCK = 1216
    """ 结算素股中 """

    PENIS_IN_HAT_JOB = 1221
    """ 结算帽子交中 """
    PENIS_IN_GLASSES_JOB = 1222
    """ 结算眼镜交中 """
    PENIS_IN_EAR_ORNAMENT_JOB = 1223
    """ 结算耳饰交中 """
    PENIS_IN_NECK_ORNAMENT_JOB = 1224
    """ 结算脖饰交中 """
    PENIS_IN_MOUTH_ORNAMENT_JOB = 1225
    """ 结算口罩交中 """
    PENIS_IN_TOP_JOB = 1226
    """ 结算上衣交中 """
    PENIS_IN_CORSET_JOB = 1227
    """ 结算胸衣交中 """
    PENIS_IN_GLOVES_JOB = 1228
    """ 结算手套交中 """
    PENIS_IN_SKIRT_JOB = 1229
    """ 结算裙子交中 """
    PENIS_IN_UNDERWEAR_JOB = 1230
    """ 结算内裤交中 """
    PENIS_IN_SOCKS_JOB = 1231
    """ 结算袜子交中 """
    PENIS_IN_SHOES_JOB = 1232
    """ 结算鞋子交中 """
    PENIS_IN_WEAPONS_JOB = 1233
    """ 结算武器交中 """
    PENIS_IN_TROUSERS_JOB = 1234
    """ 结算裤子交中 """

    N_ORGASM_SUPER = 1250
    """ 结算N绝顶被寸止 """
    B_ORGASM_SUPER = 1251
    """ 结算B绝顶被寸止 """
    C_ORGASM_SUPER = 1252
    """ 结算C绝顶被寸止 """
    P_ORGASM_SUPER = 1253
    """ 结算射精被寸止 """
    V_ORGASM_SUPER = 1254
    """ 结算V绝顶被寸止 """
    A_ORGASM_SUPER = 1255
    """ 结算A绝顶被寸止 """
    U_ORGASM_SUPER = 1256
    """ 结算U绝顶被寸止 """
    W_ORGASM_SUPER = 1257
    """ 结算W绝顶被寸止 """

    LOVE_1 = 1301
    """ 结算获得思慕 """
    LOVE_2 = 1302
    """ 结算获得恋慕 """
    LOVE_3 = 1303
    """ 结算获得恋人(含赠予信物) """
    LOVE_4 = 1304
    """ 结算获得爱侣 """
    OBEY_1 = 1305
    """ 结算获得屈从 """
    OBEY_2 = 1306
    """ 结算获得驯服 """
    OBEY_3 = 1307
    """ 结算获得宠物(含赠予信物)  """
    OBEY_4 = 1308
    """ 结算获得奴隶 """

    FERTILIZATION = 1311
    """ 结算获得受精 """
    FERTILIZATION_FAILD = 1312
    """ 结算受精失败 """
    PREGNANCY = 1313
    """ 结算获得妊娠 """
    PARTURIENT = 1314
    """ 结算获得临盆 """
    BORN = 1315
    """ 生产前的对话 """
    POSTPARTUM = 1317
    """ 生产后的对话+获得产后 """
    REARING = 1318
    """ 结算获得育儿 """
    REARING_COMPLETE = 1319
    """ 结算育儿完成 """
    CHILD_TO_LOLI = 1320
    """ 结算幼女长成萝莉 """
    LOLI_TO_GIRL = 1321
    """ 结算萝莉长成少女 """

    FIRST_MEET = 1331
    """ 初次见面 """
    DAY_HELLO = 1332
    """ 每日打招呼 """

    NEW_ROUND_FAREWELL = 1351
    """ 新周目告别 """

    START_FIELD_COMMISSION_AS_LEADER = 1361
    """ 以队长身份出发执行外勤委托 """
    END_FIELD_COMMISSION_AS_LEADER = 1362
    """ 以队长身份完成外勤委托归舰 """

    APPOINNTED_AS_DIPLOMAT_LOCAL = 1371
    """ 被任命为本地外交官 """
    RELIEVED_OF_DIPLOMAT_LOCAL = 1372
    """ 被解除本地外交官的任命 """
    APPOINNTED_AS_DIPLOMAT_OUT = 1373
    """ 被任命为外派外交官 """
    RELIEVED_OF_DIPLOMAT_OUT = 1374
    """ 被解除外派外交官的任命 """

    CHOSEN_AS_ASSISTANT = 1401
    """ 被选为助理 """
    NOT_AS_ASSISTANT = 1402
    """ 不再为助理 """
    AI_FOLLOW_OFF = 1403
    """ 关闭智能跟随 """
    AI_FOLLOW_ON = 1404
    """ 开启智能跟随 """
    COME_TO_OFFICE = 1405
    """ 要求前往办公室 """
    SUPPORT_SERVICE_OFF = 1406
    """ 关闭辅佐服务 """
    SUPPORT_SERVICE_ON = 1407
    """ 开启辅佐服务 """
    SEND_FOOD_SERVICE_OFF = 1408
    """ 关闭送饭服务 """
    BUY_LUNGCH = 1409
    """ 开启帮忙买午饭服务 """
    MAKE_LUNGCH = 1410
    """ 开启亲手做午饭服务 """
    MAKE_THREE_MEALS = 1411
    """ 开启亲手做三餐服务 """
    MORNING_SERVICE_OFF = 1412
    """ 关闭早安服务 """
    MORNING_SALUTATION = 1413
    """ 开启早上叫起床服务 """
    MORNING_KISS = 1414
    """ 开启早安吻服务 """
    MORNING_BLOWJOB = 1415
    """ 开启早安咬服务 """
    NIGHT_SERVICE_OFF = 1416
    """ 关闭晚安服务 """
    NIGHT_SALUTATION = 1417
    """ 开启晚上催睡觉服务 """
    NIGHT_KISS = 1418
    """ 开启晚安吻服务 """
    NIGHT_BLOWJOB = 1419
    """ 开启晚安咬服务 """
    COHABITATION_OFF = 1420
    """ 关闭同居服务 """
    COHABITATION_ON = 1421
    """ 开启同居服务 """
    LOVE_SUPPORT_OFF = 1422
    """ 关闭助攻服务 """
    LOVE_SUPPORT_ON = 1423
    """ 开启助攻服务 """

    ASK_GIVE_PAN_EVERYDAY = 1451
    """ 被要求每天上交内裤 """
    ASK_GIVE_SOCKS_EVERYDAY = 1452
    """ 被要求每天上交袜子 """
    ASK_NOT_WEAR_CORSET = 1453
    """ 被要求以后不再穿胸衣 """
    ASK_NOT_WEAR_CLOTH_IN_SLEEP = 1454
    """ 被要求以后睡觉时不穿衣服裸睡 """
    GIVE_PAN_IN_DAY_FIRST_MEET = 1455
    """ 在每日招呼时上交今天的内裤 """
    GIVE_SOCKS_IN_DAY_FIRST_MEET = 1456
    """ 在每日招呼时上交今天的袜子 """
    ASK_EQUP_NIPPLE_CLAMP_IN_DAY = 1461
    """ 被要求白天时戴着乳头夹 """
    ASK_EQUP_CLIT_CLAMP_IN_DAY = 1462
    """ 被要求白天时戴着阴蒂夹 """
    ASK_EQUP_V_VIBRATOR_IN_DAY = 1463
    """ 被要求白天时V里插着振动棒 """
    ASK_EQUP_A_VIBRATOR_IN_DAY = 1464
    """ 被要求白天时A里插着振动棒 """
    ASK_EQUP_NIPPLE_CLAMP_IN_SLEEP = 1465
    """ 被要求睡觉时戴着乳头夹 """
    ASK_EQUP_CLIT_CLAMP_IN_SLEEP = 1466
    """ 被要求睡觉时戴着阴蒂夹 """
    ASK_EQUP_V_VIBRATOR_IN_SLEEP = 1467
    """ 被要求睡觉时V里插着振动棒 """
    ASK_EQUP_A_VIBRATOR_IN_SLEEP = 1468
    """ 被要求睡觉时A里插着振动棒 """
    ASK_NOT_WASH_SEMEN = 1471
    """ 被要求洗澡时不再清洗阴道内的精液 """
    ASK_MASTURBATION_BEFORE_SLEEP = 1472
    """ 被要求每天晚上睡前都要自慰 """
    ASK_NOT_MASTURBATION = 1473
    """ 被要求禁止自慰 """
    ASK_SUCKING_AND_SWALLOWING_EXERCISES = 1481
    """ 被要求进行吮吸与吞咽力练习 """
    ASK_ARMPIT_CLAMPING_EXERCISES = 1482
    """ 被要求进行腋下夹持力练习 """
    ASK_BREAST_CLAMPING_EXERCISES = 1483
    """ 被要求进行胸部夹持力练习 """
    ASK_HANDS_FLEXIBILITY_EXERCISES = 1484
    """ 被要求进行手部灵活度练习 """
    ASK_FOOTS_FLEXIBILITY_EXERCISES = 1485
    """ 被要求进行足部灵活度练习 """
    ASK_VAGINA_FIRMNESS_EXERCISES = 1486
    """ 被要求进行阴道紧致度练习 """
    ASK_INTESTINE_FIRMNESS_EXERCISES = 1487
    """ 被要求进行肠道紧致度练习 """
    ASK_TAIL_FLEXIBILITY_EXERCISES = 1488
    """ 被要求进行尾巴灵活度练习 """
    ASK_TENTACLE_FLEXIBILITY_EXERCISES = 1489
    """ 被要求进行触手灵活度练习 """

    HAS_BEEN_PRIMARY_HYPNOSIS = 1501
    """ 获得被浅层催眠素质 """
    HAS_BEEN_DEEP_HYPNOSIS = 1502
    """ 获得被深层催眠素质 """
    HAS_BEEN_COMPLETE_HYPNOSIS = 1503
    """ 获得被完全催眠素质 """


class InstructType:
    """指令类型"""

    SYSTEM = 0
    """ 系统 """
    DAILY = 1
    """ 日常 """
    PLAY = 2
    """ 娱乐 """
    WORK = 3
    """ 工作 """
    ARTS = 4
    """ 技艺 """
    OBSCENITY = 5
    """ 猥亵 """
    SEX = 6
    """ 性爱 """


class SexInstructSubType:
    """性爱指令子类型"""

    BASE = 0
    """ 基础 """
    WAIT_UPON = 1
    """ 侍奉 """
    DRUG = 2
    """ 药物 """
    ITEM = 3
    """ 道具 """
    INSERT = 4
    """ 插入 """
    SM = 5
    """ SM """
    ARTS = 6
    """ 技艺 """


class Instruct:
    """指令id"""

    #系统#
    MOVE = 0
    """ 移动 """
    SEE_ATTR = 0
    """ 查看属性 """
    ITEM = 0
    """ 道具 """
    ORIGINIUM_ARTS = 0
    """ 源石技艺 """
    CHARA_DIY_INSTRUCT = 0
    """ 角色自定义特殊指令 """
    SAVE = 0
    """ 读写存档 """
    ABL_UP = 0
    """ 属性升级 """
    OWNER_ABL_UP = 0
    """ 自身属性升级 """
    SEE_DIRTY = 0
    """ 查看污浊情况 """
    INSTRUCT_FILTER = 0
    """ 指令过滤 """
    DEBUG_MODE_ON = 0
    """ 开启debug模式 """
    DEBUG_MODE_OFF = 0
    """ 关闭debug模式 """
    DEBUG_ADJUST = 0
    """ debug数值调整 """
    COLLECTION_NOW_PLACE = 0
    """ 收藏该地点 """
    CANCEL_COLLECTION_NOW_PLACE = 0
    """ 取消收藏地点 """
    SYSTEM_SETTING = 0
    """ 系统设置 """
    CHAT_AI_SETTING = 0
    """ 文本生成AI设置 """
    TALK_QUICK_TEST = 0
    """ 快速测试口上 """

    #日常#
    WAIT = 0
    """ 等待五分钟 """
    WAIT_1_HOUR = 0
    """ 等待一个小时 """
    WAIT_6_HOUR = 0
    """ 等待六个小时 """
    CHAT = 0
    """ 聊天 """
    STROKE = 0
    """ 身体接触 """
    MASSAGE = 0
    """ 按摩 """
    MAKE_COFFEE = 0
    """ 泡咖啡 """
    ASK_MAKE_COFFEE = 0
    """ 让对方泡咖啡 """
    MAKE_FOOD = 0
    """ 做饭 """
    EAT = 0
    """ 进食 """
    GIVE_FOOD = 0
    """ 让对方食用 """
    REST = 0
    """ 休息 """
    DIRAY = 0
    """ 日记 """
    SLEEP = 0
    """ 睡觉 """
    TAKE_SHOWER = 0
    """ 淋浴 """
    BUY_H_ITEM = 0
    """ 购买成人用品 """
    BUY_FOOD = 0
    """ 购买食物 """
    ALL_NPC_POSITION = 0
    """ 干员位置一览 """
    FOLLOW = 0
    """ 邀请同行 """
    END_FOLLOW = 0
    """ 结束同行 """
    APOLOGIZE = 0
    """ 道歉 """
    LISTEN_COMPLAINT = 0
    """ 听牢骚 """
    COLLCET_PANTY = 0
    """ 收起内裤 """
    ASK_DATE = 0
    """ 邀请约会 """
    DRINK_ALCOHOL = 0
    """ 劝酒 """
    PEE = 0
    """ 解手 """
    COLLECT = 0
    """ 摆放藏品 """
    TAKE_CARE_BABY = 0
    """ 照顾婴儿 """
    ORDER_HOTEL_ROOM = 0
    """ 预定房间 """

    #娱乐#
    SINGING = 0
    """ 唱歌 """
    PLAY_INSTRUMENT = 0
    """ 演奏乐器 """
    LISTEN_INFLATION = 0
    """ 听肚子里的动静 """
    PLAY_WITH_CHILD = 0
    """ 一起玩耍 """
    EXERCISE = 0
    """ 锻炼身体 """
    BORROW_BOOK = 0
    """ 借阅书籍 """
    READ_BOOK = 0
    """ 读书 """
    WATCH_MOVIE = 0
    """ 看电影 """
    PHOTOGRAPHY = 0
    """ 摄影 """
    PLAY_WATER = 0
    """ 玩水 """
    PLAY_GOMOKU = 0
    """ 下五子棋 """
    PLAY_CHESS = 0
    """ 下棋 """
    PLAY_MAHJONG = 0
    """ 打麻将 """
    PLAY_CARDS = 0
    """ 打牌 """
    REHEARSE_DANCE = 0
    """ 排演舞剧 """
    PLAY_ARCADE_GAME = 0
    """ 玩街机游戏 """
    SWIMMING = 0
    """ 游泳 """
    TASTE_WINE = 0
    """ 品酒 """
    TASTE_TEA = 0
    """ 品茶 """
    TASTE_COFFEE = 0
    """ 品咖啡 """
    TASTE_DESSERT = 0
    """ 品尝点心 """
    TASTE_FOOD = 0
    """ 品尝美食 """
    PLAY_HOUSE = 0
    """ 过家家 """
    STYLE_HAIR = 0
    """ 修整发型 """
    FULL_BODY_STYLING = 0
    """ 全身造型服务 """
    SOAK_FEET = 0
    """ 泡脚 """
    STEAM_SAUNA = 0
    """ 蒸桑拿 """
    HYDROTHERAPY_TREATMENT = 0
    """ 水疗护理 """
    ONSEN_BATH = 0
    """ 泡温泉 """
    AROMATHERAPY = 0
    """ 香薰疗愈 """

    #工作#
    OFFICIAL_WORK = 0
    """ 处理公务 """
    BATTLE_COMMAND = 0
    """ 指挥作战 """
    FIELD_COMMISSION = 0
    """ 外勤委托 """
    TRAINING = 0
    """ 战斗训练 """
    CURE_PATIENT = 0
    """ 诊疗病人 """
    RECRUIT = 0
    """ 招募干员 """
    CONFIM_RECRUIT = 0
    """ 确认已招募的干员 """
    RECRUITMENT = 0
    """ 招募情况 """
    TEACH = 0
    """ 授课 """
    MAINTENANCE_FACILITIES = 0
    """ 维护设施 """
    REPAIR_EQUIPMENT = 0
    """ 维修装备 """
    ASSISTANT_ADJUSTMENTS = 0
    """ 助理相关调整 """
    BUILDING = 0
    """ 基建系统 """
    VISITOR_SYSTEM = 0
    """ 访客系统 """
    INVITE_VISITOR = 0
    """ 邀请访客 """
    NATION_DIPLOMACY = 0
    """ 势力外交 """
    DEAL_WITH_DIPLOMACY = 0
    """ 处理外交事宜 """
    PRTS = 0
    """ 普瑞赛斯 """
    MANAGE_LIBRARY = 0
    """ 管理图书馆 """
    MANAGE_ASSEMBLY_LINE = 0
    """ 管理流水线 """
    MANAGE_AGRICULTURE = 0
    """ 管理农业生产 """
    MANAGE_VEHICLE = 0
    """ 管理载具 """
    RESOURCE_EXCHANGE = 0
    """ 资源交易 """
    NAVIGATION = 0
    """ 导航 """
    SEE_COLLECTION = 0
    """ 查看收藏品 """
    SEE_FRIDGE = 0
    """ 查看冰箱 """
    MANAGE_BASEMENT = 0
    """ 管理罗德岛 """

    #源石技艺#
    HYPNOSIS_ONE = 0
    """ 单人催眠 """
    DEEPENING_HYPNOSIS = 0
    """ 加深催眠 """
    HYPNOSIS_ALL = 0
    """ 集体催眠 """
    CHANGE_HYPNOSIS_MODE = 0
    """ 切换催眠模式 """
    HYPNOSIS_CANCEL = 0
    """ 解除催眠 """
    HYPNOSIS_INCREASE_BODY_SENSITIVITY = 0
    """ 体控-敏感度提升 """
    HYPNOSIS_FORCE_CLIMAX = 0
    """ 体控-强制高潮 """
    HYPNOSIS_FORCE_OVULATION = 0
    """ 体控-强制排卵 """
    HYPNOSIS_BLOCKHEAD = 0
    """ 体控-木头人 """
    HYPNOSIS_ACTIVE_H = 0
    """ 体控-逆推 """
    HYPNOSIS_ROLEPLAY = 0
    """ 心控-角色扮演 """
    HYPNOSIS_PAIN_AS_PLEASURE = 0
    """ 心控-苦痛快感化 """
    PENETRATING_VISION_ON = 0
    """ 开启透视 """
    PENETRATING_VISION_OFF = 0
    """ 关闭透视 """
    HORMONE_ON = 0
    """ 开启信息素 """
    HORMONE_OFF = 0
    """ 关闭信息素 """
    TIME_STOP_ON = 0
    """ 时间停止流动 """
    TIME_STOP_OFF = 0
    """ 时间重新流动 """
    CARRY_TARGET = 0
    """ 搬运对方 """
    STOP_CARRY_TARGET = 0
    """ 停止搬运对方 """
    TARGET_FREE_IN_TIME_STOP = 0
    """ 对方在时停中获得自由 """
    TARGET_STOP_IN_TIME_STOP = 0
    """ 对方在时停中再次停止 """

    #猥亵#
    MAKE_COFFEE_ADD = 0
    """ 泡咖啡（加料） """
    TOUCH_HEAD = 0
    """ 摸头 """
    TOUCH_BREAST = 0
    """ 摸胸 """
    TOUCH_BUTTOCKS = 0
    """ 摸屁股 """
    TOUCH_EARS = 0
    """ 摸耳朵 """
    TOUCH_HORN = 0
    """ 摸角 """
    TOUCH_TAIL = 0
    """ 摸尾巴 """
    TOUCH_RING = 0
    """ 摸光环 """
    TOUCH_WING = 0
    """ 摸光翼 """
    TOUCH_TENTACLE = 0
    """ 摸触手 """
    TOUCH_CAR = 0
    """ 摸小车 """
    HAND_IN_HAND = 0
    """ 牵手 """
    EMBRACE = 0
    """ 拥抱 """
    KISS = 0
    """ 亲吻 """
    LAP_PILLOW = 0
    """ 膝枕 """
    RAISE_SKIRT = 0
    """ 掀起裙子 """
    ASK_FOR_PAN = 0
    """ 索要内裤 """
    ASK_FOR_SOCKS = 0
    """ 索要袜子 """
    STEAL_PAN = 0
    """ 偷走内裤 """
    STEAL_SOCKS = 0
    """ 偷走袜子 """
    STEAL_SCENE_ALL_PAN = 0
    """ 偷走所有人内裤 """
    STEAL_SCENE_ALL_SOCKS = 0
    """ 偷走所有人袜子 """
    TOUCH_CLITORIS = 0
    """ 阴蒂爱抚 """
    TOUCH_VAGINA = 0
    """ 手指插入（V） """
    TOUCH_ANUS = 0
    """ 手指插入（A） """
    MILK = 0
    """ 挤奶 """
    BAGGING_AND_MOVING = 0
    """ 装袋搬走 """
    PUT_INTO_PRISON = 0
    """ 投入监牢 """
    SET_FREE = 0
    """ 解除囚禁 """
    CHECK_LOCKER = 0
    """ 检查衣柜 """
    PHYSICAL_CHECK_AND_MANAGE = 0
    """ 身体检查与管理 """
    CONFESSION = 0
    """ 告白 """
    GIVE_NECKLACE = 0
    """ 戴上项圈 """
    SLEEP_OBSCENITY = 0
    """ 睡眠猥亵 """
    STOP_SLEEP_OBSCENITY = 0
    """ 停止睡眠猥亵 """
    DO_H = 0
    """ 邀请H """
    DO_H_IN_LOVE_HOTEL = 0
    """ 邀请在爱情旅馆H """
    UNCONSCIOUS_H = 0
    """ 无意识奸 """
    ASK_GROUP_SEX = 0
    """ 邀请多P """

    #性爱#
    WAIT_5_MIN_IN_H = 0
    """ 等待五分钟(H中) """
    END_H = 0
    """ H结束 """
    GROUP_SEX_END = 0
    """ 结束多P """
    MAKING_OUT = 0
    """ 身体爱抚 """
    KISS_H = 0
    """ 接吻 """
    BREAST_CARESS = 0
    """ 胸爱抚 """
    TWIDDLE_NIPPLES = 0
    """ 玩弄乳头 """
    BREAST_SUCKING = 0
    """ 舔吸乳头 """
    EXTERNAL_WOMB_MASSAGE = 0
    """ 体外子宫按摩 """
    CLIT_CARESS = 0
    """ 阴蒂爱抚 """
    OPEN_LABIA = 0
    """ 掰开阴唇观察 """
    OPEN_ANUS = 0
    """ 掰开肛门观察 """
    CUNNILINGUS = 0
    """ 舔阴 """
    LICK_ANAL = 0
    """ 舔肛 """
    FINGER_INSERTION = 0
    """ 手指插入(V) """
    ANAL_CARESS = 0
    """ 手指插入(A) """
    MAKE_MASTUREBATE = 0
    """ 命令对方自慰 """
    MAKE_LICK_ANAL = 0
    """ 命令对方舔自己肛门 """
    ASK_PEE = 0
    """ 命令对方小便 """
    CHANGE_TOP_AND_BOTTOM = 0
    """ 交给对方 """
    KEEP_ENJOY = 0
    """ 继续享受 """
    TRY_PL_ACTIVE_H = 0
    """ 尝试掌握主动权 """
    SEDECU = 0
    """ 诱惑 """
    HANDJOB = 0
    """ 手交 """
    BLOWJOB = 0
    """ 口交 """
    PAIZURI = 0
    """ 乳交 """
    FOOTJOB = 0
    """ 足交 """
    HAIRJOB = 0
    """ 发交 """
    AXILLAJOB = 0
    """ 腋交 """
    RUB_BUTTOCK = 0
    """ 素股 """
    HAND_BLOWJOB = 0
    """ 手交口交 """
    TITS_BLOWJOB = 0
    """ 乳交口交 """
    FOCUS_BLOWJOB = 0
    """ 真空口交 """
    DEEP_THROAT = 0
    """ 深喉插入 """
    CLEAN_BLOWJOB = 0
    """ 清洁口交 """
    SIXTY_NINE = 0
    """ 六九式 """
    LEGJOB = 0
    """ 腿交 """
    TAILJOB = 0
    """ 尾交 """
    FACE_RUB = 0
    """ 阴茎蹭脸 """
    HORN_RUB = 0
    """ 阴茎蹭角 """
    EARS_RUB = 0
    """ 阴茎蹭耳朵 """
    HAT_JOB = 0
    """ 帽子交 """
    GLASSES_JOB = 0
    """ 眼镜交 """
    EAR_ORNAMENT_JOB = 0
    """ 耳饰交 """
    NECK_ORNAMENT_JOB = 0
    """ 脖饰交 """
    MOUTH_ORNAMENT_JOB = 0
    """ 口罩交 """
    TOP_JOB = 0
    """ 上衣交 """
    CORSET_JOB = 0
    """ 胸衣交 """
    GLOVES_JOB = 0
    """ 手套交 """
    SKIRT_JOB = 0
    """ 裙子交 """
    TROUSERS_JOB = 0
    """ 裤子交 """
    UNDERWEAR_JOB = 0
    """ 内裤交 """
    SOCKS_JOB = 0
    """ 袜子交 """
    SHOES_JOB = 0
    """ 鞋子交 """
    WEAPONS_JOB = 0
    """ 武器交 """
    BODY_LUBRICANT = 0
    """ 润滑液 """
    BIRTH_CONTROL_PILLS = 0
    """ 避孕药 """
    PHILTER = 0
    """ 媚药 """
    ENEMAS = 0
    """ 灌肠液 """
    DIURETICS_ONCE = 0
    """ 一次性利尿剂 """
    DIURETICS_PERSISTENT = 0
    """ 持续性利尿剂 """
    SLEEPING_PILLS = 0
    """ 安眠药 """
    CLOMID = 0
    """ 排卵促进药 """
    BIRTH_CONTROL_PILLS_BEFORE = 0
    """ 事前避孕药 """
    BIRTH_CONTROL_PILLS_AFTER = 0
    """ 事后避孕药 """
    PUT_CONDOM = 0
    """ 戴上避孕套 """
    TAKE_CONDOM_OUT = 0
    """ 摘掉避孕套 """
    SAFE_CANDLES = 0
    """ 滴蜡 """
    URETHRAL_SWAB = 0
    """ 尿道棉棒 """
    NIPPLES_LOVE_EGG = 0
    """ 乳头跳蛋 """
    NIPPLE_CLAMP_ON = 0
    """ 戴上乳头夹 """
    NIPPLE_CLAMP_OFF = 0
    """ 取下乳头夹 """
    CLIT_LOVE_EGG = 0
    """ 阴蒂跳蛋 """
    CLIT_CLAMP_ON = 0
    """ 戴上阴蒂夹 """
    CLIT_CLAMP_OFF = 0
    """ 取下阴蒂夹 """
    ELECTRIC_MESSAGE_STICK = 0
    """ 电动按摩棒 """
    VIBRATOR_INSERTION = 0
    """ 插入震动棒 """
    BIG_VIBRATOR_INSERTION = 0
    """ 加粗震动棒 """
    HUGE_VIBRATOR_INSERTION = 0
    """ 巨型震动棒 """
    VIBRATOR_INSERTION_OFF = 0
    """ 拔出振动棒 """
    VIBRATOR_INSERTION_ANAL = 0
    """ 肛门插入振动棒 """
    BIG_VIBRATOR_INSERTION_ANAL = 0
    """ 加粗肛门震动棒 """
    HUGE_VIBRATOR_INSERTION_ANAL = 0
    """ 巨型肛门震动棒 """
    VIBRATOR_INSERTION_ANAL_OFF = 0
    """ 拔出肛门振动棒 """
    CLYSTER = 0
    """ 灌肠 """
    ANAL_PLUG = 0
    """ 肛塞 """
    CLYSTER_END = 0
    """ 拔出肛塞 """
    ANAL_BEADS = 0
    """ 塞入肛门拉珠 """
    ANAL_BEADS_OFF = 0
    """ 拔出肛门拉珠 """
    MILKING_MACHINE_ON = 0
    """ 装上搾乳机 """
    MILKING_MACHINE_OFF = 0
    """ 取下搾乳机 """
    URINE_COLLECTOR_ON = 0
    """ 装上采尿器 """
    URINE_COLLECTOR_OFF = 0
    """ 取下采尿器 """
    BONDAGE = 0
    """ 绳子 """
    PATCH = 0
    """ 眼罩 """
    WHIP = 0
    """ 鞭子 """
    NEEDLE = 0
    """ 针 """
    NORMAL_SEX = 0
    """ 正常位 """
    BACK_SEX = 0
    """ 背后位 """
    RIDING_SEX = 0
    """ 骑乘位 """
    FACE_SEAT_SEX = 0
    """ 对面座位 """
    BACK_SEAT_SEX = 0
    """ 背面座位 """
    FACE_STAND_SEX = 0
    """ 对面立位 """
    BACK_STAND_SEX = 0
    """ 背面立位 """
    STIMULATE_G_POINT = 0
    """ 刺激G点 """
    WOMB_OS_CARESS = 0
    """ 玩弄子宫口 """
    WOMB_INSERTION = 0
    """ 插入子宫口 """
    WOMB_SEX = 0
    """ 子宫姦 """
    NORMAL_ANAL_SEX = 0
    """ 正常位肛交 """
    BACK_ANAL_SEX = 0
    """ 后背位肛交 """
    RIDING_ANAL_SEX = 0
    """ 骑乘位肛交 """
    FACE_SEAT_ANAL_SEX = 0
    """ 对面座位肛交 """
    BACK_SEAT_ANAL_SEX = 0
    """ 背面座位肛交 """
    FACE_STAND_ANAL_SEX = 0
    """ 对面立位肛交 """
    BACK_STAND_ANAL_SEX = 0
    """ 背面立位肛交 """
    STIMULATE_SIGMOID_COLON = 0
    """ 玩弄s状结肠 """
    STIMULATE_VAGINA = 0
    """ 隔着刺激阴道 """
    DOUBLE_PENETRATION = 0
    """ 二穴插入 """
    URETHRAL_FINGER_INSERTION = 0
    """ 尿道指姦 """
    URETHRAL_SEX = 0
    """ 尿道姦 """
    BEAT_BREAST = 0
    """ 打胸部 """
    SPANKING = 0
    """ 打屁股 """
    SHAME_PLAY = 0
    """ 羞耻play """
    BUNDLED_PLAY = 0
    """ 拘束play """
    TAKE_SHOWER_H = 0
    """ 淋浴 """
    BUBBLE_BATH = 0
    """ 泡泡浴 """
    GIVE_BLOWJOB = 0
    """ 给对方口交 """
    UNDRESS = 0
    """ 脱衣服 """
    ORGASM_EDGE_ON = 0
    """ 绝顶寸止 """
    ORGASM_EDGE_OFF = 0
    """ 绝顶解放 """


i = 0
for k in Instruct.__dict__:
    if isinstance(Instruct.__dict__[k], int):
        setattr(Instruct, k, i)
        i += 1


handle_premise_data: Dict[str, FunctionType] = {}
""" 前提处理数据 """
handle_instruct_data: Dict[int, FunctionType] = {}
""" 指令处理数据 """
handle_instruct_name_data: Dict[int, str] = {}
""" 指令对应文本 """
instruct_type_data: Dict[int, Set] = {}
""" 指令类型拥有的指令集合 """
instruct_sub_type_data: Dict[int, int] = {}
""" 指令的子类型数据，指令id:子类id """
instruct_premise_data: Dict[int, Set] = {}
""" 指令显示的所需前提集合 """
handle_state_machine_data: Dict[int, FunctionType] = {}
""" 角色状态机函数 """
family_region_list: Dict[int, str] = {}
""" 姓氏区间数据 """
boys_region_list: Dict[int, str] = {}
""" 男孩名字区间数据 """
girls_region_list: Dict[int, str] = {}
""" 女孩名字区间数据 """
family_region_int_list: List[int] = []
""" 姓氏权重区间数据 """
boys_region_int_list: List[int] = []
""" 男孩名字权重区间数据 """
girls_region_int_list: List[int] = []
""" 女孩名字权重区间数据 """
panel_data: Dict[int, FunctionType] = {}
"""
面板id对应的面板绘制函数集合
面板id:面板绘制函数对象
"""
place_data: Dict[str, List[str]] = {}
""" 按房间类型分类的场景列表 场景标签:场景路径列表 """
cmd_map: Dict[int, FunctionType] = {}
""" cmd存储 """
settle_behavior_effect_data: Dict[int, FunctionType] = {}
""" 角色行为结算处理器 处理器id:处理器 """
settle_second_behavior_effect_data: Dict[int, FunctionType] = {}
""" 角色二段行为结算处理器 处理器id:处理器 """

first_NPC_name_set = {_("阿米娅"),_("凯尔希"),_("可露希尔"),_("特蕾西娅"),_("华法琳"),_("杜宾")}
""" 初始就有的NPC的名字 """

ban_NPC_name_set = {_("普瑞赛斯"),_("老天师"),_("魔王"),_("菈玛莲"),_("塔露拉"),_("莉泽洛特"),_("希尔德加德"),_("坎黛拉"),_("克丽斯腾"),_("爱布拉娜"),_("温德米尔"),_("赫拉提娅"),_("文月"),_("年"),_("夕"),_("令"),_("黍")}
""" 无法直接招募到的NPC的名字 """

special_end_H_list = [Behavior.H_INTERRUPT, Behavior.H_HP_0, Behavior.T_H_HP_0]
""" 意外中断H的行为id列表 """

chat_ai_model_list = ['gpt-3.5-turbo', 'gpt-4', 'gpt-4-turbo', 'gpt-4o', 'gpt-4o-mini', 'gemini-1.5-pro', 'gemini-1.5-flash']
""" 文本生成的AI模型列表 """

sleep_text_list = [_("清醒"), _("疲劳"), _("昏昏欲睡"), _("随时睡着")]
""" 困倦状态文本列表 """

# 协力名单，不分先后 依吹脆香，反R，幻白，无色树，灵鸠伊凛，诺伊，√，はるか