# -*- coding: UTF-8 -*-
"""schedule_handle：教室、全局课表、个人课表、当前课程、上课地点、实习导师"""
from _bootstrap import *  # noqa: F401,F403

section("教室列表与开放判定")
clear_schedules()
cache.rhodes_island.facility_open = {}
base_list = schedule_handle.get_classroom_list()
check("只开三间基础教室", len(base_list) == 3, base_list)
check("基础教室是 理论教室一/实践教室一/大礼堂", base_list == [_("理论教室一"), _("实践教室一"), _("大礼堂")], base_list)
open_all_classroom()
room_list = schedule_handle.get_classroom_list()
check("全开后 10 间教室", len(room_list) == 10, room_list)
check("顺序为 理论→实践→大礼堂", room_list[0] == _("理论教室一") and room_list[5] == _("理论教室六")
      and room_list[6] == _("实践教室一") and room_list[-1] == _("大礼堂"), room_list)
check("按课型筛：理论课 6 间", len(schedule_handle.get_classroom_list(education_constant.COURSE_TYPE_THEORY)) == 6)
check("按课型筛：非法课型为空", schedule_handle.get_classroom_list(99) == [])
check("教室反查课型", schedule_handle.get_course_type_by_classroom(_("理论教室二")) == education_constant.COURSE_TYPE_THEORY
      and schedule_handle.get_course_type_by_classroom(_("实践教室三")) == education_constant.COURSE_TYPE_PRACTICE
      and schedule_handle.get_course_type_by_classroom(_("大礼堂")) == education_constant.COURSE_TYPE_PUBLIC
      and schedule_handle.get_course_type_by_classroom("不存在的教室") == -1)
room_path = schedule_handle.get_classroom_position(_("理论教室一"))
check("教室场景路径可达", room_path and scene_str(room_path) in cache.scene_data, room_path)
check("排序键：中文数字序", [schedule_handle.get_classroom_sort_key(_("理论教室") + w) for w in "一二三四五六"] == [0, 1, 2, 3, 4, 5])

section("全局课表格子")
ROOM1 = _("理论教室一")
ROOM2 = _("理论教室二")
teacher = make_character(101, "教师甲", 151)
teacher_b = make_character(102, "教师乙", 151)
check("初始格子为空", schedule_handle.get_class_cell(ROOM1, 0, 0) is None)
schedule_handle.set_class_cell(ROOM1, 0, 0, 45, 101)
check("写入后可读", schedule_handle.get_class_cell(ROOM1, 0, 0) == [45, 101])
check("教师反查", schedule_handle.get_teacher_cell(101, 0, 0) == (ROOM1, 45))
check("别的教师反查为空", schedule_handle.get_teacher_cell(102, 0, 0) is None)
check("冲突：同节次排进另一间", schedule_handle.judge_teacher_conflict(101, 0, 0, ROOM2) != "")
check("不冲突：同一间", schedule_handle.judge_teacher_conflict(101, 0, 0, ROOM1) == "")
check("不冲突：别的节次", schedule_handle.judge_teacher_conflict(101, 0, 1, ROOM2) == "")
schedule_handle.set_class_cell(ROOM2, 2, 3, 43, 101)
week = schedule_handle.get_teacher_week_schedule(101)
check("教师周表含两格", sum(len(v) for v in week.values()) == 2 and week[2][3] == (ROOM2, 43), week)
schedule_handle.clear_class_cell(ROOM1, 0, 0)
check("清空后为空", schedule_handle.get_class_cell(ROOM1, 0, 0) is None)
schedule_handle.clear_class_cell(ROOM1, 0, 0)
check("重复清空不报错", True)
check("教师候选只列教师岗", sorted(schedule_handle.get_teacher_candidate_list()) == [101, 102])

section("临时实操课覆盖层")
today = cache.game_time.date().toordinal()
sex_class_handle.set_temp_class(today, 2, _("实践教室一"), 70, must_attend=[])
check("覆盖层：今天该节次读到主修科目与教师0", schedule_handle.get_class_cell(_("实践教室一"), cache.game_time.weekday(), 2) == [70, 0])
other_day = (cache.game_time.weekday() + 1) % 7
check("覆盖层不影响别的星期", schedule_handle.get_class_cell(_("实践教室一"), other_day, 2) is None)
check("玩家的教师反查走覆盖层", schedule_handle.get_teacher_cell(0, cache.game_time.weekday(), 2) == (_("实践教室一"), 70))
check("玩家周表并入今天的临时课", 2 in schedule_handle.get_teacher_week_schedule(0).get(cache.game_time.weekday(), {}))
cache.rhodes_island.temp_sex_class = {}

section("个人课表与当前课程")
student = make_character(201, "女儿A", 152, daughter=True, stage=103)
check("初始个人课表为空", schedule_handle.get_selected_course(201, 0, 0) is None)
check("没有养成数据也不会被凭空创建", cache.character_data[201].child_growth is None)
schedule_handle.set_selected_course(201, 0, 0, education_constant.COURSE_TYPE_THEORY, ROOM1)
check("写入后可读", schedule_handle.get_selected_course(201, 0, 0) == [education_constant.COURSE_TYPE_THEORY, ROOM1])
schedule_handle.set_class_cell(ROOM1, 0, 0, 45, 101)
set_time(period_time(0))
now_course = schedule_handle.get_now_course(201)
check("第1节：当前课程解析出科目与教师", now_course is not None and now_course["ability_id"] == 45 and now_course["teacher_id"] == 101
      and now_course["classroom"] == ROOM1 and now_course["period"] == 0, now_course)
check("教师视角 get_now_teaching", schedule_handle.get_now_teaching(101) == {
    "course_type": education_constant.COURSE_TYPE_THEORY, "classroom": ROOM1, "ability_id": 45, "period": 0})
check("学生没排课的节次为 None", (set_time(period_time(1)), schedule_handle.get_now_course(201))[1] is None)
set_time(DEFAULT_TIME.replace(hour=13, minute=0))
check("不在节次内为 None", schedule_handle.get_now_course(201) is None and schedule_handle.get_now_teaching(101) is None)
set_time(period_time(0))
schedule_handle.clear_class_cell(ROOM1, 0, 0)
now_course = schedule_handle.get_now_course(201)
check("教室课被清掉后：科目/教师为 -1", now_course is not None and now_course["ability_id"] == -1 and now_course["teacher_id"] == -1)
schedule_handle.clear_selected_course(201, 0, 0)
check("清空个人课表格子", schedule_handle.get_selected_course(201, 0, 0) is None)
schedule_handle.set_selected_course(201, 0, 0, education_constant.COURSE_TYPE_THEORY, ROOM1)
schedule_handle.set_selected_course(201, 0, 0, education_constant.COURSE_TYPE_PE, _("木桩房"))
check("重选即覆盖（学生撞课结构上不可能）", schedule_handle.get_selected_course(201, 0, 0) == [education_constant.COURSE_TYPE_PE, _("木桩房")])

section("上课地点解析")
pe_course = schedule_handle.get_now_course(201)
pe_place = schedule_handle.get_course_place(pe_course)
check("体育课：木桩房精确到那间房", pe_place and cache.scene_data[scene_str(pe_place)].scene_name == _("木桩房"), pe_place)
interest_cid = next(cid for cid in game_config.config_entertainment if game_config.config_entertainment[cid].class_ok)
schedule_handle.set_selected_course(201, 0, 0, education_constant.COURSE_TYPE_INTEREST, interest_cid)
interest_place = schedule_handle.get_course_place(schedule_handle.get_now_course(201))
check("兴趣课：按 Entertainment.csv 的地点标签解析出场景", bool(interest_place), interest_cid)
intern_work = next(cid for cid in game_config.config_work_type
                   if cid and not game_config.config_work_type[cid].tag and game_config.config_work_type[cid].ability_id
                   and cid not in education_constant.EXCLUDE_INTERN_WORK_TYPE and game_config.config_work_type[cid].place_tag in constant.place_data)
schedule_handle.set_selected_course(201, 0, 0, education_constant.COURSE_TYPE_INTERN, intern_work)
intern_place = schedule_handle.get_course_place(schedule_handle.get_now_course(201))
check("实习课：按 WorkType.csv 的地点标签解析出场景", bool(intern_place), intern_work)
mentor = make_character(103, "在岗干员", intern_work, position=intern_place)
intern_place_2 = schedule_handle.get_course_place(schedule_handle.get_now_course(201))
check("实习课优先去在岗干员所在的那间房", intern_place_2 == mentor.position, intern_place_2)
move_to(201, intern_place_2)
check("实习导师 = 同场景同岗位的干员", schedule_handle.get_intern_mentor(201, intern_work) == 103)
move_to(103, SCENE_DORM)
check("导师离场则无人在岗", schedule_handle.get_intern_mentor(201, intern_work) == -1)
schedule_handle.set_selected_course(201, 0, 0, education_constant.COURSE_TYPE_INTEREST, 99999)
check("目标非法：解析为空列表而不是报错", schedule_handle.get_course_place(schedule_handle.get_now_course(201)) == [])
schedule_handle.set_selected_course(201, 0, 0, education_constant.COURSE_TYPE_THEORY, ROOM1)
check("教室课地点 = 教室场景路径", schedule_handle.get_course_place(schedule_handle.get_now_course(201)) == room_path)

section("行为cid反查")
check("213 → teach", schedule_handle.get_behavior_name_by_cid(213) == "teach")
check("查不到为空串", schedule_handle.get_behavior_name_by_cid(-99) == "")

finish()
